Heroic-Games-Launcher/HeroicGamesLauncher

package.json

Currently, package.json uses a to my knowledge non-standard way of writing the licence name. This MR changes it to use the more standard SPDX licence identifier for the GPL 3.0. I took the liberty to assume you meant GPL 3.0 (only) and not (or later).
See https://spdx.org/licenses/ for a list of identifiers.

fix: use SPDX licence identifier

---

PKGBUILD

A small change to PKGBUILD that creates a symbolic link to be able to launch heroic from the terminal or with a launcher like dmenu.

PKGBUILD: Creates a symbolic link of the executable to /usr/bin/heroic

---

src/App.css

I thought that the header looked a big small when I resized the window because it wasn't changing the font-size, so I set it to a clamp() on `.App .header`. I also thought the toggle switch looked a bit too small so I clamped that too.
I have some doubts about the header font size being a tad too big now, but if you change the preferred size in the clamp on `.App .header` you can make it a bit smaller easily.
How it looks currently: 
How it looks with the clamps:

Changed some of the pixel measurements to clamp()s on the header

---

package.json
public/index.html
src/App.css
src/components/GamePage/GamePage.tsx
src/components/Library.tsx
src/components/Login.tsx
src/components/Settings/GeneralSettings.tsx
src/components/Settings/SyncSaves.tsx
src/components/Settings/WineSettings.tsx
src/components/UI/Header.tsx
src/components/UI/InfoBox.tsx
src/components/UI/SearchBar.tsx
src/components/UI/Update.tsx
src/components/UI/UpdateComponent.tsx
src/components/UI/UserSelector.tsx
src/index.tsx
src/state/GlobalState.tsx
yarn.lock

I had to rename `Update` to `UpdateComponent` because of a name conflict.
I wanted to import it as a different name but it didn't work with `import Update as UpdateIcon from ...`
(fixes #174)
Google Fonts removed in #181
I don't know how adding those two npm packages affect the build size. I hope it uses treeshaking.

Use local material icons

---

electron/main.ts
electron/utils.ts
package.json
src/App.css
src/components/GamePage/GamePage.tsx
src/components/GamePage/GamesSubmenu.tsx
src/components/Library.tsx
src/components/Settings/index.tsx
src/components/UI/GameCard.tsx
src/components/UI/Header.tsx

- Fix: #120 and #178 
- Adds old DXVK installation method fixed since Winetricks does not install VKD3D.
- Other small fixes

Minor fixes 6

---

.gitignore
electron/utils.ts
package.json
src/components/Settings/index.tsx

Fixed #256 
The bug was introduced with the latest fix I sent related with the custom wine 🤦🏽 . Shit happens.
It happens not only in ubuntu, but all distros since Heroic starts a never-ending loop when looking for custom wine on new installations.
Added a check to skip looking for custom wine/proton when there is no config file.

Fix: Not starting on new installations

---

.eslintrc
.prettierignore
.prettierrc.json
electron/legendary_utils/library.ts
electron/main.ts
electron/utils.ts
package.json
src/App.test.tsx
src/components/Navbar/components/UserSelector/index.tsx
src/components/Navbar/index.tsx
src/components/UI/Header/index.tsx
src/components/UI/LanguageSelector/index.tsx
src/components/utils.ts
src/helpers/index.ts
src/index.tsx
src/screens/Game/GamePage/index.tsx
src/screens/Game/GameSubMenu/index.tsx
src/screens/Library/components/GameCard/index.tsx
src/screens/Library/index.tsx
src/screens/Login/index.tsx
src/screens/Settings/components/GeneralSettings/index.tsx
src/screens/Settings/components/OtherSettings/index.tsx
src/screens/Settings/components/SyncSaves/index.tsx
src/screens/Settings/components/Tools/index.tsx
src/screens/Settings/components/WineSettings/index.tsx
src/screens/Settings/index.tsx
src/state/ContextProvider.tsx
src/state/GlobalState.tsx
yarn.lock

I found that prettier was (still) not set up properly, and was conflicting with some ESLint rules (I couldn't figure out the root cause). I found one of them in #263. 
Also, all the rules we defined in Prettier were available and autofixable in ESLint anyways, so I decided that it was more hassle than it was worth, and removed it. It will also simplify our pre-commit and pre-push workflows.
This is just a proposal so that we can discuss the merits and demerits of this.
----
Functionally, only a few tabs got shifted around and the dangling commas got removed.

Remove Prettier.

---

electron/game_config.ts
electron/games.ts
electron/main.ts
electron/protocol.ts
package.json

Fixes #307.
Implementation based on what I read here:
https://github.com/electron-userland/electron-builder/issues/4035
https://github.com/electron/electron/issues/4857
Scheme is a lot like HTTP, except that there's no domain name.
Like `heroic://launch?appName=Hazelnut`.

Implement a basic URL scheme.

---

.github/workflows/build.yml
.github/workflows/draft-release.yml

Switches to using Yarn instead of npm for releases, as recommended by electron-builder's README.
Spliced from #312.

ci: Use Yarn for building and deploying releases.

---

electron/protocol.ts
src/components/Navbar/components/UserSelector/index.tsx
src/screens/Login/index.tsx

I'm a certified fuckwad who knew this would happen but forgot to fix it before the refactor PR was merged. Please drown me in lava.
NOTE: You **_CANNOT_** `import` `ipcRenderer`, you have to use `require`.
Oh yeah this PR also amends some protocol stuff I guess.
---
Fixes #329, fixes #330.

frontend: Fix erroneous use of `import`, fixes 1.5.8-dontuse.

---

.github/workflows/build.yml
.github/workflows/draft-release.yml
.github/workflows/lint.yml
.github/workflows/test.yml

This should fix the issues we've been having with deploying tests on CI. Now we use Node 14 everywhere.
See https://github.com/actions/setup-node for details.
Also, since we're having issues with coverage plugins, I think we should just run tests for now, coverage can come later.

ci: Switch to Node 14 for all tasks, don't report coverage (for now).

---

electron/main.ts
electron/utils.ts

Now we can check for even the patch version.
Also, versions aren't floats, and they shouldn't be treated as such.
Also fixes the Python check, supersedes #420.

More robust version checks.

---

src/screens/Settings/components/SyncSaves/index.tsx

After the windows version this feature of finding the right save folder was broken on Linux. So now its fixed.

Fix Save folder when its proton

---

electron/constants.ts

Uses the custom shell (provided by every user) instead of bash by default. In case it's not set, it uses bash.

Use $SHELL instead of bash in Linux and Mac

---

electron/legendary/games.ts
electron/types.ts

I've added desktop shortcuts for Linux (GNOME)
Not applicable:
Fixes #140
Depends on the protocol launch command to be fixed. (#445)

Add Desktop shortcuts(backend)

---

electron/__tests__/constants.test.ts
electron/constants.ts
electron/tsconfig.json
package.json
yarn.lock

We only use eletron-util to fix asar paths. This is just a simple string replace, so we don't need a whole library for that.

Removed electron-util

---

src/index.css
src/screens/Game/GamePage/index.css
src/screens/Game/GamePage/index.tsx
src/screens/Game/GameSubMenu/index.css
src/screens/Game/GameSubMenu/index.tsx

I got some user feedback about how difficult its sometimes to realise that we have a submenu under the game page. Some people think that that settings button is to open the game settings. so I think its better to keep it always visible from now on.

Change submenu to be always visible on game page

---

package.json
src/screens/Game/GamePage/index.tsx

Fix 'The Spectrum Retreat' page not opening due to missing title

---

src/components/UI/Header/index.tsx
src/helpers/helpers.test.ts
src/helpers/library.ts
src/screens/Game/GamePage/index.tsx
src/screens/Library/components/GameCard/index.tsx

Since legendary its not supporting the feature, until we develop a Queue, Heroic won't allow starting a new download until the other has finished.

Avoid paralell downloads for now

---

electron/legendary/games.ts
electron/legendary/library.ts
electron/main.ts

Another fix to this issue. Last time I forgot a few commands weren't using the `execOptions`.

Fix using wrong shell on linux for some commands

---

CHANGELOG.md
package.json
src/screens/Library/components/GameCard/index.tsx
src/screens/Settings/index.tsx
src/state/GlobalState.tsx

- Fixes a bug where a game wasn't shown as installed after finishing the installation. #604 
- Changes default and minimal Heroic window size to accommodate lower resolutions.
- Fixed a small bug where the return button on settings was leading to the Game page instead of the Library when coming from there.

Several Fixes from 1.9.1

---

src/components/UI/LanguageSelector/index.tsx

"韓國語" same as "한국어" but in traditional Chinese characters.
When writing in Korean language, almost only Hangul (Korean character) is preferred.
So, like other languages' label, there is no need to add "韓國語".

Fix Korean language label on Language Selector

---

src/screens/Library/components/GameCard/index.tsx

Some game card background images are zoomed in too much / skewed.
issue: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/603
As recommended per the linked issue by @LukeVader-IV , stretching the images instead of setting the images to cover, fixes this.
A few examples:
`background-size: cover`
`background-size: 100% 100%`
`background-size: cover`
`background-size: 100% 100%`

[fix: issue-603] adjust library game card background coverage

---

electron/constants.ts
electron/legendary/games.ts

Use `xdg-user-dir DESKTOP` on linux systems to get the correct Desktop folder path that depends on the system language.
My system is in spanish, so my `Desktop` folder is actually `Escritorio`, using the `xdg-user-dir` command returns the full path to that directory.
This is only implemented for linux since adding shortcuts to desktop is only implemented on linux.
Closes #721
I couldn't add a test since I would have to stub the system command somehow which feels too hacky, but I accept any suggestion on how to add a test for this fix!

Get the desktop folder from the system instead of hardcoding '/Desktop'

---

electron/legendary/games.ts
src/screens/Game/GameSubMenu/index.tsx

This PR implements the functionality of adding shortcut icons on Windows when the user clicks the `Add shortcut` action in the game page.
It also implements removing the shortcuts when the game is uninstalled.
I tried to make the `Add desktop shortcuts automatically` and `Add games to start menu automatically` settings work but there's some issue on Windows with the install callback that is not fired properly and it was getting too complicated to do both things on 1 PR so I decided to leave that for another moment.
I'm not really sure how to add tests for this since it's too tied to the system.
Closes #724 

Support adding desktop and start menu shortcuts on windows

---

electron/games.ts
electron/legendary/games.ts
electron/main.ts
src/screens/Game/GameSubMenu/index.tsx
src/screens/Settings/components/OtherSettings/index.tsx
src/state/GlobalState.tsx

This PR enables the settings to automatically create desktop and start menu shortcuts on windows.
I moved the trigger of those function to the GlobalState class (the execAsync callback was never triggered on windows).
I'll add some comments on the diff.
Again, I'm not really sure how to add automated tests for this but I accept any advice on how to do that.
Closes #726 

Enable shortcuts config on windows and refactor

---

src/screens/Library/components/InstallModal/index.tsx
src/screens/Settings/components/Tools/index.tsx
src/screens/Settings/components/WineSettings/index.tsx

Add WinePrefix to Install Modal with auto naming

---

electron/legendary/games.ts

Just a typo fix with the Discord RPC saying what platform Heroic is running on (from "MacOS" to "macOS")

Fixed typo with Discord RPC indicating macOS is "MacOS" when it should be "macOS"

---

electron/legendary/games.ts

Changed a way of creating prefix for Proton. Instead of preparing `mkdir` command it uses mkdirSync from graceful-fs library.
Same for Wine prefixes. Before running `wineboot`, creates directory recursively.  
Fixes one problem out of two in
#840 

Fix wine prefixes not being created

---

electron/main.ts
src/App.tsx
src/components/UI/Header/index.css
src/components/UI/SvgButton/index.tsx
src/screens/Library/components/GameCard/index.css
src/screens/Library/components/GameCard/index.tsx
src/screens/Library/components/InstallModal/index.css
src/screens/Library/index.css
src/screens/Library/index.tsx

This PR adds the `enable-spatial-navigation` flag so the app can be navigated using the arrow keys so the keyboard accessibility is better (and this may enable the spatial navigation to use with the gamepad). The PR includes some refactoring that fixed the bugs with the browser's native spatial navigation, this way we don't have to use a javascript solution.
I had to make some refactoring to fix the spatial navigation:
- the library screen header is not position: sticky, now the listings are wrapped in a div and that div has scroll, so the header won't break the spatial navigation
- because of the previous change, I had to add a small fix to the install modal that was offset
- I made a big refactor of the gameCard/gameListItem component so the same html works for both formats
- I replaced …

[General] Refactor and enable spatial navigation

---

src/components/UI/ToggleSwitch/index.css

This PR updates the css of the switch in the ToggleSwitch component to only display the focus outline when using the keyboard to focus an element but not when using a mouse.
I also updated the ouline style to be the oposite to the current color (so if the switch is off -white- the outline is yellow, and when the switch is on -yellow- the outline is white)
Closes #876 
---

Show the switch focus outline only with keyboard, not mouse

---

public/locales/en/translation.json
src/screens/Settings/index.css
src/screens/Settings/index.tsx
yarn.lock

First things first, I noticed that the "Copy All Settings to Clipboard" button in the settings menu actually says "Setting" instead of "Settings." I'm not entirely sure if I need to do anything to update the translations, but I've fixed it where it appeared in the code. 
The other thing I added was just a small styling improvement (in my opinion) to that same button. When clicked, it now changes the text to "Copied to Clipboard!" and changes the text color to green on hover (success variable) for 3 seconds, after which it changes back to normal.
Hope you like the changes, and let me know if I should fix anything
---

Fix typo and add extra styling to copy to clipboard button

---

electron/main.ts
electron/types.ts
package.json
public/index.html
src/components/UI/SearchBar/index.tsx
src/helpers/gamepad.ts
src/helpers/virtualKeyboard.ts
src/index.css
src/index.tsx
src/screens/Library/components/GameCard/index.tsx
src/types.ts
yarn.lock

This PR adds support to control Heroic using a gamepad.
Implemented:
- using the Gamepad API
- invoke methods on electron to simulate key presses and wheel
- navigate the app using pad or left stick
- scroll the main window using right stick
- repeat actions when holding a button/stick
- trigger a `click` on the currently focused element when pressing A in an Xbox controller
- Xbox, PS3, PS5 and Gamecub layouts
- interacting with select tags
- virtual keyboard
TODO:
- ~~try other controllers (I only have an Xbox controller to test this)~~
- ~~I cannot find a way to trigger the dropdown for `select` tags (tried with the `click()` method, simulating a `Return` key press and simulating a `mouseDown` event with electron), maybe we need to display a custom dropdown when using a gamepad~~
Ideas …

Support nagivating Heroic using a gamepad

---

src/helpers/shortcuts.ts
src/index.tsx

This PR adds the code to handle Ctrl+F and CMD+F shortucts to move the cursor to the search bar if we are in the library screen.
Closes #867 
---

Support Ctrl+F and CMD+F shortcut to focus search bar

---

electron/main.ts
electron/utils.ts

The app was closed if the python version doesn't match the requirement (>=3.8).
Removed python check since legendary executable does not need it.
#924 
---

[Bugfix] Removed python check.

---

electron/__tests__/logger.test.ts
electron/legendary/library.ts
electron/logger/logger.ts

- Added timestamp for each logged message
- Lined logs so it looks similiar to a table
---

[General] Add timestamp and relined logs

---

electron/main.ts

There was a problem, where the creation of folder  'C:/ProgramData/Epic/EpicGamesLauncher/Data/Manifests' failed, because mkdirSync wasn't called with recursive option. With recursive set to true, folder should be created now.
---

[Windows] Fixed manifest path creation for egsSync

---

README.md

Added installation instructions for Heroic in MacOS via Homebrew. Heroic is available in Homebrew as a cask. https://formulae.brew.sh/cask/heroic#default
---

Add installation on MacOS via Homebrew

---

electron/main.ts
src/state/GlobalState.tsx

Added a timeout to avoid that race condition error. Hopefully it is fixed

[Fix] Trying to run native game through wine

---

electron/main.ts

The current `second-instance` handling function blindly passes `argv[1]` to `handleProtocol`. This is problematic, as `argv[1]` might not always be the protocol.  In my case (when adding simple logging to the function), I've found that it was always `--enable-crashpad`, so protocol links were not working if Heroic was already running.
This is now fixed, by iterating over every element in `argv` and checking if it starts with `heroic://`
---

Fixup protocol handling when Heroic is already running

---

electron/launcher.ts

Before, all necessary launch options were inserted into a string with pre-defined spaces. This caused issues, as when an option wasn't set, a space was still inserted.
Now, the "command parts" are collected in a list, which is then filtered to remove empty entries, and then joined together with spaces.
---

Remove unnecessary spaces from launch commands

---

electron/config.ts

In `getCrossover`, we're returning early if CX is not found. This makes a later if statement always be true. I've removed this statement
---

[Linux] Remove redundant if statement in getCrossover

---

.github/workflows/build-prs.yml
electron/config.ts
electron/constants.ts
electron/dxvk.ts
electron/game_config.ts
electron/gog/games.ts
electron/launcher.ts
electron/legendary/games.ts
electron/logger/logger.ts
electron/main.ts
electron/utils.ts

This PR addresses two things:
- Paths are now combined with [`path.join()`](https://nodejs.org/api/path.html#pathjoinpaths) instead of just combining them together as strings
- On Windows, a workaround is used to display files in a folder. This fixes the "Show log file in folder" button not doing anything
**It is very likely that I missed a path when moving to join**. Please double- and triple-check everywhere and let me know if you find any issues.
---

[All] Truly use `path.join()` everywhere (Fix "Show log file in folder" and wrong game settings path)

---

electron/logger/logger.ts
electron/utils.ts

- Remove the workaround for showing a file, as `shell.showItemInFolder` actually works fine (it just didn't work back when we mixed / and \ in paths
- Properly remove forbidden characters from log filename
---

[Windows] Fix "Show log file in folder" once and for all

---

src/screens/Settings/components/OtherSettings/index.tsx

This is a easy fix.
Closes #1107 

[Fix] Not able to enable Steam Runtime

---

src/screens/Library/components/InstallModal/index.tsx

On game installation dialog
- Available languages are now displayed as human readable names instead of codes
- Attempt to select by default language that matches the language of the application interface
Preview:
---

[General] Improvements in language selector when installing game

---

.editorconfig
package.json

Added addition options to .editorconfig
Disable eslint validation during development
Rationale:
The reason to disable it is that it's infuriating to develop anything with eslint enabled.
You comment single line for then you get bombarded with unused variables and import which must also be commented which will cause new errors.
Moving code around is impossible without getting perfect indents.
I don't see any value with checking that during development, especially since prettier will take care of it anyway.
They'll still be checked during build and pipeline execution.
---

[Tech] Disable eslint during development, added options to editorconfig

---

electron/launcher.ts
electron/main.ts
electron/protocol.ts
electron/tools.ts
electron/utils.ts

Change dialogs (message boxes and file selection) to be modal (attached to window) so they will block application window until user closes dialog.
Sadly it doesn't work for file selection dialogs because of bug in electron: https://github.com/electron/electron/issues/32857 but I expect it will work after they fix it.
---

[Fix] Dialogs hiding behind app window

---

electron/legendary/library.ts
electron/utils.ts
src/App.tsx
src/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/helpers/index.ts
src/screens/Game/GameSubMenu/index.tsx
src/screens/WebView/index.tsx

This PR fixes #863 by making the stores open in the webview instead of a popup.
I did a small refactor:
- moved the epic url generation at the loading of the file so `gameInfo.store_url` works for both gog and epic
- we can open the generic page with no language code and the epic store will use the user's language
- I cleaned a little bit of the webview url handling for the `login/:runner` routes
---

Open game store page in webview and refactor

---

README.md

Some guy uploaded an app to the Microsoft Store that conflicts with "heroic", so winget now just says that "Multiple packages found matching input criteria. Please refine the input." if you enter winget install heroic. I've edited the readme so that it has the whole "HeroicGamesLauncher.HeroicGamesLauncher" package name in it that works.
Example: https://i.imgur.com/VaRH1R2.png
---

update winget command

---

CHANGELOG.md

This PR updated the CHANGELOG.md up to Version 2.2.6.
It also Introduces an standardization in the Changelog as following:
- Changes should be marked with either [General], [Linux], [Windows], [MacOS], [Bugfix] or [i18n] and sorted in the same order
- If a bugfix is Platform Specific the Platform should be added behind a `|`
- Are there multiple platforms for one change they should be seperated by a `/` 
---
I've tried to apply these standardizations retrospectively, but errors might have occured during this process, so please correct me if you spot anything.
---
Additionally, the prettier check doesn't seem to have passed, help with fixing that would be greatly appreciated

Update & Standardize CHANGELOG.md

---

electron/shortcuts.ts

Heroic add the MimeType=x-scheme-handler/heroic to all shortcuts. The MimeType line means, that the App, that belongs to this .desktop file can open this MimeType. In this case, it says basically, that Game xy can open heric:// links,what is not true. Only Heroic itself can do that.

Remove MimeType from Shortcut

---

package.json
src/state/GlobalState.tsx

This PR fixes #1216 by not resetting the value of `filterText` in the state when refreshing the library.
---

[FIX] Don't reset the filterText when refreshing the library

---

package.json
src/screens/Library/components/GameCard/index.css

This is a simple fix for #1214. Just moved the `:hover` selector to the card instead of to the images.
Closes #1214
---

Fix grayscale/color for games with logo image

---

src/components/UI/Header/index.tsx
src/screens/Library/constants.ts
src/screens/Library/index.tsx
src/state/GlobalState.tsx

This PR changes the order of the games in the library to display installed games first, then games that are being installed, and then games that are not installed nor installing.
This also removes the selector of All / Ready / Not Ready / Downloading to simplify the UI.
Closes #977 
Closes #878
---

Order games by status

---

src/screens/Settings/components/LogSettings/index.css

This PR improves the readability of the Log viewer:
- use more space when available
- not collapse empty lines
- preserve indentation from the original file
- preserve white spaces for alignment
- monospace font
---

Improve logs readability

---

src/screens/WineManager/index.tsx

This PR fixes #1235. The `useEffect` call was returning a value and that was triggering that React error shown in the issue description.
After the error, the application was broken when changing screens.
---

Don't return value in useEffect call in Wine Manager

---

electron/main.ts

Closes #1000 
The problem was the object set when there's nothing yet in the recent games, the `else` was setting the property `game` instead of `appName`. Check the linked issue for the content of the config with this bug.
I'm also filtering out recent games data with no appName property (to clean that from users with the problem).
---

Fix keys in config file for recent games

---

src/screens/WineManager/components/WineItem/index.css
src/screens/WineManager/components/WineItem/index.tsx
src/screens/WineManager/index.tsx

This fixes #933 
I had to refactor the code to use one single SvgButton because rendering different elements made it lose the focus of the current button and navigating back (to cancel, for example) was really annoying.
I also included a small fix on the responsiveness, on small screens the buttons were outside the viewport.
---

Allow installing wine versions using the controller

---

src/screens/Library/components/GameCard/index.css
src/screens/Library/components/GameCard/index.tsx

This is an idea by flavio over discord, hidden games have a log opacity so you can indentify them better in the list when showing hidden games.
You can see an example with the second Batman game and with A Short Hike:
---

Dim hidden games

---

electron/gog/library.ts

This possibly fixes #1276 
Seems like `vertical_image` can be undefined/null in some cases.
---

Use vertical_image value only if present

---

electron/gog/user.ts
electron/legendary/user.ts
electron/main.ts
src/App.tsx
src/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/components/UI/Sidebar/components/SidebarUtils/index.tsx
src/screens/Game/GamePage/index.tsx
src/screens/Library/index.tsx
src/screens/Login/components/Runner/index.tsx
src/screens/Login/components/SIDLogin/index.tsx
src/screens/Login/index.tsx
src/screens/WebView/index.tsx
src/state/ContextProvider.tsx
src/state/GlobalState.tsx
src/types.ts

This PR is a refactor around the login/logut actions to address a few issues:
- logged in user affects all the app, makes more sense that it's something in the global context so we can use react's reactivity to propagate login changes
- components that needed the current user/s were reading the user from the electron stores each time
- the login flow was using a refresh function with a setTimeout
- the SidebarLinks component was handling redirection to the login (this was a problem because it makes more sense to handle that at the router level and also because it was preventing access to the Accessibility section, which users might need before log in)
- the find-in-page event was triggering multiple times
Now, the login for both epic and gog is handled by the GlobalState component and the …

Refactor: Handle login in a single place

---

README.md

Fixes three typos and (markdown) adds language to fenced code blocks to remain consistent with the rest of the file.

Fixes typos, markdown

---

electron/launcher.ts
electron/legendary/games.ts
src/helpers/library.ts
src/screens/Game/GamePage/index.tsx
src/screens/Library/components/GameCard/index.tsx
src/state/GlobalState.tsx

This fixes the issue we are having now where it is not possible to skip an update when launching a game.
I changed the logic to check the update on frontend and show the message before even launching the game instead of waiting for an error from Legendary.
---

[Fix] Check for game updates before launch

---

electron/main.ts

This PR adds the feature of opening the main window when double clicking the icon in the Tray/Taskbar.
This DOES NOT work on linux, the events that we need to listen to only work on window and mac as stated in the Electron docs https://www.electronjs.org/docs/latest/api/tray/#event-double-click-macos-windows
There is no possible workaround for Linux until electron adds support for it.
---

[UX] Open main window on tray double click

---

electron/launcher.ts

GOG Setup instructions were not ran due to a missing `await`
I've also reverted the changes about not running Wineboot since otherwise, a Proton prefix would only count as "updated" if the root folder was created by Heroic (so if the user deletes all files inside it, it would still not run the setup instructions)
---

Run GOG setup again + don't skip Wineboot for Proton

---

electron/utils.ts

This changes the Steam Runtime path from `~/.local/share/Steam/...` to `~/.steam/root/...`. This makes the Steam Runtime work on Ubuntu-based distributions
---

Change Steam Runtime search path

---

electron/main.ts
electron/protocol.ts

Launching Heroic without the UI is now possible with this parameter. Together with launching a game (`heroic://launch/AppName`), this now allows for a fully headless game launch, similar to HBL (HBL's still faster, since we have to load all of Heroic first)
Closes #1361
---

Add new `--no-gui` parameter

---

electron/launcher.ts

With this patch, you can now enter wrappers into the environment variable section of the game settings again & they will be properly executed instead of being added as empty variables
---

Allow specifying wrappers in the env var section again

---

electron/launcher.ts
flatpak/local.heroic.yml

- When the Steam Runtime is used for Proton, `STEAM_COMPAT_APP_ID` and `SteamAppId` are set to 0. This avoids a ProtonFix crash for GE-Proton
- User-defined environment variables are now set in `setupEnvVars` (they were in `setupWineEnvVars` before). Not sure why I did it that way back then. Because of that, setting these variables on native games works again now.
---

Set Steam App ID variables when using the Runtime on Proton + fixup setting user-defined env vars on native games

---

electron/config.ts
electron/constants.ts
package.json
yarn.lock

Added a helper function to read from `libraryfolder.vdf` and add the libraries to the `steampaths` 
---

[Linux] Search for Proton on all steam libraries

---

electron/tools.ts

Changed the `WINE` env var to use `PATH` as suggested by @CommandMC.
---

[Linux - Fix] Winetricks on Flatpak

---

electron/games.ts
electron/gog/games.ts
electron/legendary/games.ts
src/screens/Library/index.tsx

Fix how we chack `isNative` on GOG and Legendary.
---

[Fix] Proper Check if a game is native or not

---

electron/launcher.ts

Proton copies over a ready-made default prefix when it detects that it needs to update, so running `wineboot` afterwards will always say that it wasn't updated. This changes `verifyWinePrefix` so it (1) returns early if a Proton prefix is already present & (2) returns true if Proton created a prefix
This is still somewhat naive since it relies on the `pfx` directory (not) being present, but it's still better than not working at all
---

Fixup verifyWinePrefix for Proton... again

---

electron/launcher.ts

Try to fix macOS not launching CX

---

electron/tools.ts

Before, we were not downloading Winetricks if the file already existed. This resulted in very outdated Winetricks versions (for example, I was unknowingly running a version from Feb. 2021)
---

Always update Winetricks if we are online

---

src/helpers/library.ts
src/screens/Game/GameSubMenu/index.tsx
src/screens/Library/components/InstallModal/index.tsx
src/screens/Settings/components/GeneralSettings/index.tsx
src/screens/Settings/components/OtherSettings/index.tsx
src/screens/Settings/components/Tools/index.tsx
src/screens/Settings/components/WineSettings/index.tsx
src/screens/Settings/index.tsx

This is a small quality of life improvement. 
When opening dialogs, the starting folder will be more specific to the setting instead of being generic and opening the recent files.
---

[UX] Use better paths on open dialog

---

electron/config.ts
electron/game_config.ts
electron/gog/games.ts
electron/launcher.ts
electron/legendary/games.ts
electron/shortcuts.ts
src/App.css
src/components/UI/SelectField/index.css
src/screens/Settings/components/SyncSaves/index.tsx
src/screens/Settings/components/Tools/index.tsx
src/screens/Settings/components/WineSettings/index.tsx
src/screens/Settings/index.css

- Remove error dialog for strings with ERROR and CRITICAL since it will create false positives
- Add small fix to relative paths on wineprefix for old configs
- Fixed some styling issues on wine settings and save-sync settings
---

[Fix] Styling and error Dialogs 

---

src/screens/Settings/components/SyncSaves/index.tsx

This fixes an old bug where the Force Upload and Force Download were not working on languages other than English.
Also improves the logic since the previous approach was too convoluted
---

[Fix] Sync saves not working on different languages than english

---

electron/launcher.ts
src/helpers/index.ts
src/screens/Library/components/InstallModal/selective_dl.ts
src/screens/Settings/components/Tools/index.tsx
src/screens/WebView/index.tsx

Add SDL list for `Suphalak`
Cannot test this one since I don't own this game, actually have no idea which game is that.
Got the list from legendary API
It seems the game is total war warhammer 2
- Also removed an unnecessary check that was causing login to now always work (I believe)
- Fixed an issue for `runExe` with spaces on the path.
---

[Fix] Fix run exe on prefix when having spaces + updated SDL list + updated legendary

---

src/screens/Library/components/InstallModal/index.tsx

This PR fixes #1446 by using different ids for each ToggleSwitch element.
Tested it with Fortnite.
---

Fix toggle switch ids in install dialog

---

src/helpers/gamepad.ts

This PR fixes #1437 . The configuration value was not being read at boot.
I also tweaked the treshold used to detect sticks being moved, it was too sensitive and a small drift or move by mistake was triggering the actions.
---

Disable controller on boot

---

src/components/UI/SearchBar/index.tsx
src/helpers/gamepad.ts

This PR fixes the detection of the searchbar to know if the virtual keyboard should be open when using gamepad navigation.
Added a comment in the search component to prevent this from happening again since it depends on the element's id.
---

Fix detection of search bar focus to open virtual keyboard

---

electron/legendary/games.ts

Another issue that was originally caused by the launch refactor. Seems to work fine, but I could only try it for one game
Something else I've noticed: The install progress seems to start at 45% for Fortnite for some reason? Legendary is reporting it correctly
---

Pass SDL list as multiple arguments

---

electron/launcher.ts

It seems like arrays are passed by reference in JS, which means the getRunnerCallWithoutCredentials function was altering the actual commandParts passed to Legendary/GOGDL. By copying the array before passing it, this no longer happens
---

[General] Fix: No longer replace token/sid with redacted

---

electron/game_config.ts
electron/launcher.ts
src/screens/Library/components/InstallModal/index.tsx

This PR fixes #1465 by using keys that apply only for games when creating the config file for a game during installation instead of copying the complete object.
I understand this should also fix that issue that was reported where the solution was to go to the settings and make one change so the settings got updated with correct data.
This also fixes an issue where all games were created with the current language code in the `language` setting which was unnecessary and broke the language override feature (the `language` setting should be empty by default to fallback to Heroic's setting).
**How to test/QA**
Install a game that you have never configured before (if you want to try with a game that you used, delete the config file first at `~/.config/heroic/GameConfig/`).
Compare the JSON file …

Store only game setting keys in game config file during installation

---

electron/launcher.ts
electron/main.ts
src/screens/Settings/components/AdvancedSettings/index.tsx
src/screens/Settings/index.tsx

This PR fixes #1463 by only writting settings when they change, and only after they are completely loaded. This applies for both Heroic's settings and games' settings.
This should improve the consistency of settings, we were storing things so many times while things where loading (I've seen up to 16 writes during the initial render!!) that it probably created some issues with race conditions having that many writes to the same files all at once.
**How to test/QA**
I added a call to `logInfo` that prints information on the logs every time call to writeConfig is done. You can play around with the settings while checking at the logs to see this is working as expected.
Note that the diff in the Files changed tab of the PR is a mess, it doesn't really reflect the changes properly, github gets …

[Fix] multiple settings writes

---

electron/main.ts
electron/protocol.ts
src/state/GlobalState.tsx

With the current code, we process the protocol/args 3s after Heroic starts, this value is sometimes too much (if heroic starts really fast) and sometimes not enough (in slow computers like my Mac it takes more than those 3 second for the frontend to be ready).
Instead of having that delay, with this PR I added a message from the frontend to the backend to tell it it's ready, and then we process the protocol.
This will also help with issue I had with the desktop shortcut feature on Mac, since I think this was causing the problem described in my comment (my mac being slow taking more than 3 seconds to have the frontend ready) https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/723
**How to Test/QA:**
Change the `electron` script in package.json to be something like:
``` …
```

Refactor/fix: Wait until frontend is ready before processing protocol/args

---

electron/legendary/games.ts

Wasn't entirely sure how this worked in #1443, didn't test it enough to find this issue
To test, just install Fortnite (or any other game that supports SDL) and see that important files (like the actual executable) are now getting downloaded
---

[Epic] Fix: Pass empty SDL tag properly

---

electron/launcher.ts
electron/utils.ts

Small thing, but we weren't quoting environment variables in the getCommand function, leading to commands like this:
```
WINEPREFIX=/home/commandmc/Games/Heroic/Prefixes/Akalabeth - World of Doom WINEFSYNC=1 ...
```
That's now fixed:
```
WINEPREFIX="/home/commandmc/Games/Heroic/Prefixes/Akalabeth - World of Doom" WINEFSYNC=1 ...
```
This is *not* a change relating to how commands are ran, this is just how they're represented
---

[Fix] Quote environment variables in generated command

---

src/screens/Library/components/InstallModal/index.tsx

`installPath` is set to "default" by default. We were calling `setInstallPath` when this was the case, but the rest of the function still continued with the `default` value (according to some googling, this is because states are only updated once per rendering cycle ([SO thread](https://stackoverflow.com/a/58877875)))
This is now fixed by checking `installPath` again right before passing it to 'checkDiskSpace', and swapping in the correct path if it's `default`
---

[Fix] "default not writable"/"Path might not be writable" error

---

electron/games.ts
electron/gog/games.ts
electron/launcher.ts
electron/legendary/games.ts
electron/main.ts
electron/protocol.ts
electron/shortcuts.ts
electron/tools.ts
electron/types.ts
electron/utils.ts
src/helpers/library.ts

Main changes:
- Logs are now live (meaning new output is written to the file immediately instead of waiting for game exit)
- If an error happens, part of the log is still written (as much info as possible is provided, to help debug the issue)
- Errors themselves are now logged with a stacktrace (not too helpful in production since function & file names are minified, but might help in development)
- The "Error log"/"Game log" (stdout & stderr) split was removed, it's both in "Game log" again now
- The log now contains a timestamp
Other changes:
- `getRunnerCallWithoutCredentials` is exported again since it's needed for the new log behavior
- Some code cleanup, didn't bother to open a separate PR for just that
---
Use the following Checklist if you have changed something on the Backend or …

[General] Logging & launching improvements

---

src/components/UI/Header/index.css
src/components/UI/Sidebar/index.css
src/components/UI/ToggleSwitch/index.css
src/screens/Settings/index.css

This PR fixes a few issues found when testing Heroic with some languages. It fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1502 and also:
Note the sidebar item and the toggle text here with Ukranian:
After:
And now the Header buttons can grow more if the translation for `ALL` is longer:
---

Some UI fixes for long strings on translations

---

electron/game_config.ts

This PR should fix the 2 issues mentioned here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1491 by adding more customization around which settings are stored for a game depending on the platform. I think there's still room for improvement there (like... gamemode, mongohud, audio fix, and more can be moved to only linux), but I wanted to fix the issue related to the wine config first before moving more things around and have more tests.
The issues I noticed in the original code:
- we were defaulting to the complete global settings if no config file for a game, this is not necesarilly bad but we just dumped everything there without any sanity check
- we were trying to do a `winePrefix.replace` even on windows on mac, which is not only not needed but also failed in …

[Tech] Refactor game settings with fallbacks 

---

electron/main.ts

This fixes another issue I found on my jurney to add shortcuts on MacOS. On this pr https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1501 I was testing opening heroic with arguments, but I didn't test opening heroic by letting the OS handle the `heroic://launch` url.
When I tested that, I notices that the `open-url` event happens before the mainWindow object is even created, and it was trying to `handleProtocol` with no mainWindow object. Then the `process.argv` variable was empty in the other `handleProtocol` in the `frontendReady` callback becuase it was not passed as an argument to the process by the OS.
In this PR I'm checking first if the mainWindow is exists, if it does it just calls `handleProtocol`, it if doesn't then it stores the url somewhere so it can be used …

Fix: Don't 'handleProtocol' if mainWindow doesn't exist yet

---

src/screens/Settings/components/GeneralSettings/index.tsx

I found that ThemeSelector is present in both Accessibility and General Settings screens. Removed the extra one from General Settings.
I can remove it from the Accessibility screen instead. 
---

[Fix] Delete duplicate ThemeSelector element

---

electron/wine/runtimes/runtimes.ts

[Fix] Extract runtimes properly

---

electron/main.ts
electron/utils.ts

On Startup, we now check if the 64- and 32-bit-versions of the [Visual C++ Runtime](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) are installed and display a message if they aren't. These runtimes are required for a few games (Fall Guys for example), but they're expected to already be installed (*I think* the EGL installs them when it's installed?)
Some remarks:
- The way I'm checking for the runtimes can probably have false positives (for example if someone has the actual development environment installed), although I don't think that's too big of an issue since you should still be fine if you have *more* than just the runtimes
- The messages in the dialog boxes could be improved a bit (which is why I didn't …

[Windows] Prompt for Visual C++ Runtime installation when not found

---

src/components/UI/SearchBar/index.tsx
src/helpers/gamepad.ts
src/helpers/virtualKeyboard.ts

This PR fixes the virtual keyboard ketpress handler that had the wrong selector to write in the search box.
This fixes #1607 and should also fix #1510 
---

Fix virtual keyboard keypress

---

electron/gog/library.ts
src/screens/Game/GamePage/index.tsx
src/screens/Library/components/GamesList/index.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1578 by checking if a game is installed to set the hasUpdate variables and not just the statuses array.
Before:
After:
Installed games still show the correct indicator:
---

Don't show update notification after uninstalling a game with available updates

---

src/screens/Game/GameSubMenu/index.tsx

The Enable/Disable EOS Overlay in the Tools screen should be displayed for Epic games only. Doesn't make sense to display for GOG games.
---

[Fix] Show Tools EOS Overlay button for Epic games only

---

electron/constants.ts
electron/main.ts
src/components/UI/Sidebar/components/SidebarLinks/index.tsx

If passed via cli, heroic will start fullscreen without window decoration. Like on the steam deck game mode, window size is not stored via electron-store.
**Should be merged after beta becomes stable.**
---

[General] Add cli option "--fullscreen"

---

electron/launcher.ts

Proton enables Esync/Fsync by default. Instead of enabling it with `WINEESYNC`/`WINEFSYNC`, you use `PROTON_NO_ESYNC`/`PROTON_NO_FSYNC` to disable it.
We weren't setting these variables correctly (we just always used `WINEESYNC`/`WINEFSYNC`). That's now fixed
---

[Fix] Esync/Fsync toggle buttons for Proton

---

electron/main.ts
src/helpers/library.ts
src/state/GlobalState.tsx

This fixes two things:
- Recent games were fetched in the order "Epic -> GOG", which resulted in Epic games always appearing first
- When a game was launched, the recent game list was not updated
Note: This is done in a somewhat hacky way that relies on the backend first setting the recent games and then sending the `playing` game status update. I would've liked to use `configStore.onDidChange('games.recent', callback)` here, but the callback is for some reason never called
---

Refresh recent games when game is launched + no longer sort them on a per-store basis

---

electron/gog/setup.ts

This will fix some issues with older games. Especially when executable name contains `{app}` variable.
By replacing it earlier we avoid using `Z:/path/to/game` on Linux, which caused issues

[GOG setup] Fix invalid executable paths

---

electron/main.ts
src/screens/Settings/components/Tools/index.tsx
src/screens/Settings/index.tsx

This fixes not being able to run Winetricks/winecfg/any executable via Wine for GOG games
---

[Fix] Pass `runner` in `callTool` IPC call

---

electron/logger/logger.ts
electron/tools.ts

- live logging of winetricks
- somehow the catch block catched a error and stopped winetricks, which was on my system not a error to stop winetricks.
---

[Fix] Run winetricks with spawn

---

public/locales/pl/translation.json
src/screens/Game/GameSubMenu/index.tsx

Fixed also a bug where we skipped checking of added to steam and shortcuts on windows. This two functions are available on any os.
---

[Fix] Skip fetch/check of tools if game is not installed

---

electron/gog/library.ts
src/components/UI/Sidebar/components/SidebarLinks/index.tsx

This small fix was introduced on #1646. It breaks heroic on redirect from the login to library.
---

[Fix] App breaking after GOG login

---

src/components/UI/ControllerHints/index.tsx
src/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/state/ContextProvider.tsx
src/state/GlobalState.tsx
src/types.ts

This PR makes the sidebar show the Quit button when a controller is activated. The button is hidden again if the controller is disconnected.
I added a new `activeController` property in the global state so we only need to listen to the window event in one place.
This fixes #1666 
---

[General] Show quit button if controller is activated

---

src/screens/Library/components/GameCard/index.tsx

Hide the unnecessary Install option in the gamecard (_right-click menu_) of an uninstalled game while another game is being downloaded.
**Screenshot:**
---

[Fix] Hide Install when downloading a game

---

electron/__tests__/shortcuts/nonesteamgame.test.ts
electron/shortcuts/nonesteamgame/nonesteamgame.ts
electron/utils.ts

Current heroic flatpak freezes in gamemode, because electron can't show a notification.
- Disable notifications on gamemode
- Disable notifications if they are not supported by the system. (https://www.electronjs.org/de/docs/latest/api/notification#notificationissupported)
---

[Fix] Disable notifications if they are not supported. (E.g. Steamdeck Gamemode)

---

src/screens/Library/components/GameCard/index.tsx

This PR fixes #1698 . The problem is better explained in the linked issue but basically, when killing a game using the `(x)` button in the library, the libraryStatus global state got corrupted because of the line I'm now removing.
This line is not used when killing a game in the Game Page component so I understand it's safe to remove and it fixes the problem.
---

Remove extra game status change when killing a game

---

src/screens/Library/components/RecentlyPlayed/index.tsx

This fixes the issue of showing the recent played games lane with a empty list.
---

[FIX] Don't show Recent Games if the list is empty

---

appveyor.yml
package.json

I noticed that the portable and setup artifacts had the same name so the portable was being overwritten by the Setup and not being uploaded to the releases page.
---

[Tech] Fix Windows artifacts naming and builds

---

src/backend/legendary/library.ts

[Fix] Check if Legendary's `metadata` folder exists before trying to read it

---

electron/constants.ts
electron/main.ts
src/screens/Settings/components/WineSettings/index.css
src/screens/Settings/components/WineSettings/index.tsx

- Create coloured hyperlink
- Open link in browser
This PR fixes two things -
1. The WinePrefix FAQ under (_Settings->Wine->Wine Prefix InfoBox_) is displayed like a simple text. Thus, users don't know that it is actually a link. 
2. Moreover, the link opens up the web page in the Heroic window itself and there's no way to go back to Heroic.
---

[Fix] WinePrefix FAQ link

---

src/frontend/screens/Settings/index.tsx

My last pull request #1538 (for issue #1032) did not save the new option within the config file. So after closing heroic the option got lost.
---

[Fix] Not permanently saving downloadNoHttps config option

---

electron/utils.ts

- wmic is deprecated in win11 and since win10 21H1. See https://www.bleepingcomputer.com/news/microsoft/microsoft-starts-killing-off-wmic-in-windows-will-thwart-attacks/#:~:text=%22The%20WMIC%20tool%20is%20deprecated,the%20command%2Dline%20management%20tool.
- According to this article it is not good to use wmic and Win32_product:
https://devblogs.microsoft.com/scripting/use-powershell-to-find-installed-software/
- Replaced wmic with the solution suggest in the article above.
- Added `child.on('error')`, else heroic will close all the time, because of uncaught exception.
- Didn't tested this, because i don't have a windows machine. Will test with people reported the problem.
---

[Windows - Fix] Replace wmic with powershell command, because it is deprecated.

---

src/components/UI/CachedImage/index.tsx

This PR changes the CachedImage component to not try to use the cache when the src of the img is relative.
Relative paths are local files so we don't really need to cache them and the cache handler fails to download that file since it's not a valid complete url. This avoid some errors in the backend for games with no image that has to use the fallback and makes the component easier to re-use without worring about the url passed as src.
---

Try to use image cache for images with full url

---

electron/main.ts
src/index.tsx

This PR adds an `error` event listener in the frontend so we can send the error message to the backend to log frontend error messages in the log files.
This should make it easier to debug problems and we won't have to ask users to open the dev tools > go to console steps to find frontend errors.
At least with my tests, things like the images cache miss don't show up so that's a good thing (those are expected for example) but I'm not sure if there are other errors that might not show up that are important, but I tested breaking the app on purpose and the error is handled by the backend.
---

Log frontend errors in log files

---

src/backend/legendary/library.ts
src/backend/legendary/user.ts
src/backend/main.ts
src/frontend/screens/Settings/components/Tools/index.tsx

We never checked if `installed.json` and `assets.json` exist. Passing an empty string to `JSON.parse()` will throw `Unexpected end of JSON`.
- Added try/catch around reading of `installed.json` and `assets.json`.
---

[Fix] TypeError: Unexpected end of json

---

.github/workflows/codecheck.yml
.github/workflows/lint.yml
.husky/pre-push

[Tech] Add codecheck to pre push and workflow

---

src/frontend/components/UI/ProgressDialog/index.css
src/frontend/index.css
src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.css
src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
src/frontend/screens/DownloadManager/components/ProgressHeader/index.css
src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
src/frontend/screens/DownloadManager/index.css
src/frontend/screens/DownloadManager/index.tsx
src/frontend/screens/Library/index.css

css and layout changes

---

src/frontend/screens/Library/components/LibraryHeader/index.tsx

This PR fix the discrepancy in game count between the game count in the All Games section of the library and the sum of the ones on the Epic Games and the Gog sections. Now it is also coherent with the number of game shown.
Fix #1877 
---

[Fix] Discrepancy in game count

---

src/frontend/hooks/useSetting.ts

This PR fixes an issue after the settings refactor that the useSetting was not triggering a re-render other components after setting the new value.
It was using some useEffects/useStates but they were actually not needed.
---

Fix setting not updating after another setting changes

---

src/frontend/screens/Library/index.css

- Match the border and color with theme color
- Reduce opacity when not hovered
https://user-images.githubusercontent.com/74495920/194710202-62b09dca-4f06-428c-9c7d-7d205ba2d340.mp4
---

[UI] Tweak backToTopBtn color theme

---

src/backend/launcher.ts

These are largely copied over from Proton's source code, and should make some more games work OOTB (as an example, Drone Racing League Simulator, which is free on the EGS right now)
Looking at the launch command now, I believe a new way we print that out is in order soon:tm:
---

[Linux] Set some more Wine-related env vars when launching with built-in libraries

---

src/backend/shortcuts/nonesteamgame/nonesteamgame.ts

The unicode appears in the dialog box because i18next escapes the value to avoid XSS injection attacks by default. 
Solved by turning off the escaping flag.
Related Issue:
#1867 
---

[Fix] Unicode chars in non-steam-game error dialog

---

src/frontend/screens/Game/GamePage/index.scss
src/frontend/screens/Game/GamePage/index.tsx

This PR is a quick fix moving the game menu next to the game's title instead of the top-right corner as described https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1841#issuecomment-1272344083
Tested with different title lengths too:
---

Move game menu next to the title

---

src/frontend/screens/Settings/components/WineSettings/WinePrefix.tsx

After the settings refactor (#1726), I noticed that the "Wine Prefix" setting was missing from the game settings. Took a quick look at the code, this bit at the start of the WinePrefix component seems to be the issue
---

[Linux] Fixup: Show Wine Prefix in Game Settings again

---

README.md
src/backend/main.ts

This PR allows for disabling the installation of the React dev tools by setting the `HEROIC_NO_REACT_DEVTOOLS` env var before running `yarn dev`.
I'm currently developing on a somewhat older machine, and I've noticed that this leads to just a *little* bit faster load times. And that little time goes a long way when you're restarting Heroic ~50 times a day :^)
---

[Tech] Make it possible to disable the React developer tools

---

src/frontend/screens/Game/GameSubMenu/index.tsx

When opening the game page for a GOG game, we are currently checking if the EOS overlay is installed, which will always be false for GOG games.
This PR skips that check.
---

Do not check the EOS overlay for GOG games

---

src/frontend/screens/Settings/components/Tools/index.tsx

This PR removes the `draggable` attribute of the button. The button supports dragging and dropping a file ON the button, but the button itself does not need to be draggable.
I think this is causing issues when clicking that button on the Steam Deck (it might be trying to trigger the `drag` instead of clicking it). I'm not sure how to test this directly on the device though but it's the only difference I can see comparing this button with the other buttons that open a file picker dialog.
Click and dropping files on the button still work fine after this change.
The `return`s were not needed
---

Remove `draggable` from `Run EXE on Prefix` button

---

src/backend/gog/games.ts
src/backend/legendary/games.ts

I noticed the feature to automatically add games to the desktop/menu was not working, and seems like I broke it a year ago https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/740/files :see_no_evil:
This PR re-adds the method call to `addShortcuts` that takes care of adding the shortcuts after a game is installed if needed.
---

Fix automatic shortcuts creation

---

src/backend/main.ts
src/backend/utils.ts

This improves game launch speed by caching system info that won't change while the app is running.
Time to launch was reduced from 20 seconds to 9 seconds with League of Legends on Windows. 
It also speeds up Heroic launch time by ~5 seconds. Before, we were unnecessarily awaiting getSystemInfo before launching the main window. Now it runs asynchronously.
---

[Tech] System info cache

---

src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx

This PR fixes an issue I just noticed while working on another PR.
Steps to reproduce the issue before this fix:
- go to Manage Accounts
- click Login for any store
- click Settings
- react app crashes with an error in the console, blank screen
The issue is that the url for the logins is `/loginweb/legendary` or `/loginweb/gog` and the sidebar component does a `split` on that url and was considering `legendary` and `gog` as runners like it happens for game page urls `/gamepage/legendary/someGame` but the was no appName in the url.
This PR fixes that by only linking to a game setting if we have an app name
---

Fix error when clicking "Settings" when the current screen is a login webview

---

src/backend/legendary/games.ts

This PR adds the configuration Legendary has to launch a game before Heroic's modification (i.e: what's configured in its config.ini).
This should help debug problems that had happen some times in the past, people following some tutorial or instructions that tells them to modify legendary's config.ini and they forget and we have no visibility of this information in the logs.
Now the logs will include this information after the game's settings:
```
...
}
Game launched at: Mon Oct 17 2022 01:00:50 GMT-0300 (hora estándar de Argentina)
Legendary's base config from config.ini:
{
"game_parameters": [],
"game_executable": "absolutedrift.exe",
"game_directory": "/home/ariel/Games/Heroic/AbsoluteDrift",
"launch_command": [
"wine"
],
"working_directory": "/home/ariel/Games/Heroic/AbsoluteDrift", …
```

Log Legendary's launch info/config when launching games

---

src/backend/legendary/games.ts

*Someone* (me) mistakenly applied the spread operator (...) to `offlineFlag` when passing it to Legendary. I'd say that instead of removing it there again, let's put the variable in line with all the other flags being `string[]` (even if it's just one string)
---

[Fix] Pass `--offline` correctly again

---

src/frontend/components/UI/Dialog/components/Dialog.tsx
src/frontend/components/UI/Dialog/index.css
src/frontend/screens/Library/components/GameCard/index.tsx

This PR fixes 3 issues with dialogs:
- Uninstall dialog was adding an empty space in grid view in library Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1930
- Clicking at the left empty are of the buttons was closing the dialog https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1931
- Selecting text in some cases was closing the dialog (no issue for this I just noticed it while testing the other fixes)
A comment on the last fix, the bug is present only when selecting text from different HTML elements, for example selecting text from the title and the content. That triggered a `click` event with the parent dialog as the target (since it can trigger an event with the 2 targets). To reproduce this issue before this fix, select text like this for …

Some dialog fixes

---

.husky/pre-push
src/backend/logger/__tests__/logfile.test.ts
src/backend/logger/__tests__/logger.test.ts
src/backend/main.ts
src/backend/wine/runtimes/__tests__/runtimes/utils.test.ts

Removes the duplicate 'kill' handler added in from download manager PR which causes issues with other ipcMain handlers.
Also removed the pre-push test command and added os checks to certain tests that are only written for linux.
---

[Fix] Duplicate kill listener

---

src/frontend/components/UI/FormControl/index.css
src/frontend/styles/_colors.scss
src/frontend/themes.css

Use separate variables for the action icons found in the library page.
- Default : `--action-icon`
- Hover : `--action-icon-hover`
- Active : `--action-icon-active`
---

[UI] Refactor Action Icons

---

README.md

Just an update to the setup documentation.

Use yarn start instead of yarn dev

---

package.json
tsconfig.json

Using these settings can reduce the time required by eslint to check the project before pushing. On my case it went from 1 minute to less than 4 seconds (if we don't use the --cache option we still have a good benefit -from 1 minute to less than 10 seconds on my system-).
---

Optimize eslint settings

---

README.md
package.json
src/backend/logger/ipc_handler.ts
src/frontend/components/UI/ActionIcons/index.tsx
src/frontend/components/UI/Header/index.css
src/frontend/components/UI/PlatformFilter/index.tsx
src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/frontend/components/UI/Sidebar/index.tsx
src/frontend/components/UI/StoreFilter/index.tsx
src/frontend/screens/DownloadManager/index.tsx
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
src/frontend/screens/Login/index.tsx
src/frontend/screens/Settings/components/LogSettings/index.tsx
src/frontend/screens/WebView/index.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

[UI/UX] Pre-release Fixes

---

src/backend/api/helpers.ts
src/backend/games.ts
src/backend/gog/games.ts
src/backend/launcher.ts
src/backend/legendary/games.ts
src/backend/main.ts
src/backend/sideload/games.ts
src/common/types.ts
src/frontend/helpers/index.ts
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
src/frontend/screens/Settings/components/SyncSaves/gog.tsx
src/frontend/screens/Settings/components/SyncSaves/legendary.tsx

This brings runWineCommand closer to how callRunner works for example. The same `commandParts` idiom is used to make it possible to exactly specify what the arguments are that should be passed to `wine`  
In practice, this now means that commands like `winepath` or `reg` can be ran successfully again
In the process, I've also made the `wait` variable actually work again (with spawn, we're no longer using a shell, so we have to put in a little more work than adding `&& <extra_command>` to run another command after the first one finishes)
---

[MacOS/Linux] Fix up runWineCommand

---

src/backend/protocol.ts

This fixes the issue we discovered on latest 2.5.0.beta.1 release that prevents gog games from launching using protocol.  
Fixed it by checking for underlying value of a object returned by getGameInfo methods, since empty object `{}` is always true in boolean expressions

[General/Protocol] Fix protocol not launching gog games

---

src/frontend/screens/Library/components/ContextMenu/index.tsx

This is an **incomplete** fix to issue #1908 
It fixes the issue most of the times. It does not always work for games near/at the bottom of the window/screen, where the context menu is rendered on top of the clicked item (GameCard or install button) triggering the hover effect (darker color).
Another idea is to disable the hover effect entirely when using the keyboard/gamepad navigation, not sure how to go about that though.
---

[Fix] context menu selection/hovering

---

src/frontend/components/UI/ControllerHints/index.css
src/frontend/styles/_colors.scss

Adds a new css variable to allow the controller hint bar to be styled independently in themes.
---

[UI] Add css variable for controller hints background

---

src/backend/launcher.ts
src/backend/legendary/eos_overlay/eos_overlay.ts
src/backend/main.ts
src/common/types.ts

This will prevent Heroic from running any Wine commands unless all files required in a Wine/Proton prefix are actually present, which will in turn prevent us from creating invalid Proton prefixes (note that this will not fix already broken Proton prefixes)
This is achieved by checking for known-required prefix files in `runWineCommand`. If any are missing, `verifyWinePrefix` is used to create / hopefully fix the prefix.  
Because of that, Proton will no longer get skipped in `verifyWinePrefix` (even though `wineboot` itself doesn't actually get ran, which is fine since Proton creates the prefix itself)
If you really have to disable this check when running commands (`verifyWinePrefix` uses `runWineCommand` to create the prefix for example), pass `skipPrefixCheckIKnowWhatImDoing` to …

[Fix] Verify that a valid Wine/Proton prefix exists before running any Wine command

---

src/frontend/components/UI/DialogHandler/components/MessageBoxModal/index.css
src/frontend/components/UI/ProgressDialog/index.css

This PR fixes this visual issue I just found when showing an error dialog:
Before:
https://user-images.githubusercontent.com/188464/200153300-f53a8754-74dd-4642-8150-9edf70747fb1.mp4
After:
https://user-images.githubusercontent.com/188464/200153335-6cedbb6e-1aaf-4f19-8eca-9cbb164eee1c.mp4
A similar issue happens for the winetricks dialog:
And the same fix applies.
I also removed the style for the `.....collapsed` variants, since it was the same calc as without `collapsed` and I couldn't really find anywhere in the code that sets that class on those element.
---

[UI] Fix dialog content width

---

src/frontend/screens/Game/GamePage/index.scss

This PR addresses an issue reported on Discord:
were scrolling moved all the content instead of only scrolling the info section.
I applied 3 changes mainly:
- only the info section scrolls now
- the title of the game and the menu button are now sticky to the top so they are always visible when scrolling
- added some bottom padding so the bottom of the content doesn't end up that close to the bottom
With this changes:
https://user-images.githubusercontent.com/188464/200140652-d08ceea2-129b-46f8-a73a-7451814e95c8.mp4
---

[UI] Fixes game page scroll when content doesn't fit the screen

---

src/frontend/components/UI/SearchBar/index.tsx

By default, the clear button (X) is always visible even if there's no input or text. 
Instead, display the clear button whenever the user starts typing into the search bar and disable it when cleared.
https://user-images.githubusercontent.com/74495920/200341520-b262f7ba-ad62-4bee-bc14-884880180ae4.mp4
---

[UI] Hide Clear button for Library's Search Bar

---

src/backend/gog/games.ts
src/backend/launcher.ts
src/backend/legendary/games.ts
src/backend/sideload/games.ts
src/backend/utils.ts

Small fix moving the `--filesystem` param to the `prepareLaunch` command
---

[Fix] Steam runtime making games fail to launch

---

src/backend/legendary/games.ts

When we launch an Epic game, we request a json object with launch information. If legendary fails to return this information for any reason, the output is invalid JSON, causing an exception and the game is not executed.
This PR adds a try/catch there so if there's any issue that prevents legendary to respond with valid JSON then we just ignore this info in the logs and print the actual output from legendary to help debugging.
---

[Logs] Catch invalid JSON outputs from legendary when launching games

---

src/frontend/screens/Settings/SettingsContext.tsx
src/frontend/screens/Settings/components/EnableEsync.tsx
src/frontend/screens/Settings/components/EnableFSR.tsx
src/frontend/screens/Settings/components/EnableFsync.tsx
src/frontend/screens/Settings/components/ShowFPS.tsx
src/frontend/screens/Settings/components/SteamRuntime.tsx
src/frontend/screens/Settings/index.tsx
src/frontend/screens/Settings/sections/GamesSettings/index.tsx
src/frontend/types.ts

This PR fixes a regresion after refactoring the settings that some wine settings where showing up for native games (native linux, window or mac).
With this PR, all the wine-related settings (wine, prefix, extensions, fps, fsr, fsync, esync, system libraries) are only shown in linux for non-native games.
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1998
---

[UI] Hide wine-related settings for games when Wine is not used

---

src/backend/legendary/library.ts

When reading out Legendary's `metadata` folder & adding the names of those files to our `allGames` set, we were assuming that there are no dots (`.`) in the actual app_name. If there were, we would fail once we try to read out the file
In practice this makes little difference, since the affected "games" are Unreal Engine-related files, which are skipped anyways, but it's still neat to get rid of those "Failed to parse ..." messages on startup
---

[Fix/Epic] Handle metadata files with dots in their name correctly

---

src/backend/main.ts

After making the recent changes in #2004, I've noticed that an issue became more frequent: We're (trying to) reload our LegendaryLibrary before Legendary/we have finished writing the file.
Apparently, NodeJS' `watch` function is notorious for double-firing events like this (I initially assumed it was caused by the file being written in chunks, but I'm not so sure anymore).
One solution would be to switch to a 3rd party library, but I believe that would be overkill for such a small part of Heroic.
Instead, we now start a timeout of 500ms when a write occurs. If another write happens during this timeframe, our old timeout is stopped & a new one is started
---

Add a timeout when watching Legendary's `installed.json`

---

src/frontend/helpers/library.ts
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/state/GlobalState.tsx

this resolves #2043
Adds cloud syncing when launching from the Game Card page, or when launched via the CLI.
---

[FIX] Auto Sync Saves not working on No-GUI mode

---

src/backend/save_sync.ts

With Legendary 0.20.31, a new hidden `--accept-path` flag got added to the sync-saves command. With it, we can just accept the path Legendary computed for us, instead of fiddling around with parsing its output.
This makes our job a lot easier
---

Use new `--accept-path` flag in save sync

---

src/backend/legendary/user.ts

When logging out from Legendary, we were **clearing out our entire configStore**, which in turn reset all settings and, since the `settings` key was no longer present in the store, lead to issues where this new functionality was used
As far as I can tell, the only thing that actually needs to be deleted when logging out is the `userInfo` key. So let's only delete that
Closes #1965
---

[Fix/Epic] Only delete `userInfo` key from configStore when logging out

---

package.json
src/frontend/hooks/usePaginatedList.ts
src/frontend/screens/Library/components/GamesList/index.tsx

Virtual pagination included in game list, using infinite scroll, to smoothly render large lists. An improvement would be to send the paginated list directly from the backend and include it in the other lists
P.S. This is my first contribution to this project, I hope it helps if you need it
---

[Feature] add virtual pagination in game list (library)

---

src/backend/gog/library.ts
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2112 (and probably that problem for other games).
We were passing `en-US` for all games when getting the download info, but some games like Roller Coaster Tycoon display `0`. When using `en-us` it works fine.
What this PR is doing is:
- first try with `en-US` (most games are fine with this from my tests)
- if the list of languages in the install info does NOT include `en-US`, check which languages are valid
- if `en-us` is a valid language, use it, else, use the first language in the list
---

[GOG] Retry GOG install info if invalid language

---

src/backend/__tests__/utils.test.ts
src/backend/constants.ts
src/backend/gog/library.ts
src/backend/launcher.ts
src/backend/legendary/library.ts
src/backend/logger/__mocks__/logfile.ts
src/backend/logger/__tests__/logfile.test.ts
src/backend/logger/logfile.ts
src/common/types.ts

This PR adds new log files to store all the output of Legendary and GOGdl.
The new files are stored next to heroic's general logs but the names are `legendary-....log` and `gogdl-.....log` instead of `heroic-....log` and the same logic to delete old logs still applies to these new ones.
There's no frontend view of these logs but they can be accessed using the same `Show log file in folder` button for the general logs.
I also fixed an issue where logs were being deleted when the month changed instead of when they were a month old (the 1st of each month it was we were deleting all files from last month).
---

[Logs] Add GOGdl and Legendary verbose log for any command output for better troubleshooting

---

src/frontend/screens/Library/components/GameCard/index.css
src/frontend/screens/Library/components/GameCard/index.tsx

This is a workaround for https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2115
There are two changes:
- added a new `isLaunching` state in the card component to be able to disable the button while we wait for the game to start (we should detect that it's doing a save sync and show that in the UI)
- only do sync saves if the user enables the option instead
---

[Library] Disable Play button while launching game

---

src/backend/gog/library.ts
src/backend/legendary/library.ts
src/backend/save_sync.ts
src/common/types.ts
src/common/types/legendary.ts

- No longer `verifyWinePrefix` if the game is native
- No longer pass `setupWineEnvVars(...)` to Legendary if the game is native
- Store correct default save folder on Mac
---

[Fix] Save sync for native games

---

src/backend/config.ts

The promise to get all wine versions for macOS was failing when no WineSkin folder was found due to a missing check to see if the folder exists or not.
---

[FIX] Crossover not found on macOS

---

src/backend/legendary/library.ts
src/common/types/legendary.ts

This PR should fix an issue reported over Discord:
```
09:41:30) ERROR:   [Legendary]:        TypeError: Cannot read properties of undefined (reading 'CloudSaveFolder')
at R.loadFile (/app/bin/heroic/resources/app.asar/build/electron/main.d61a4184.js:35:12005)
at /app/bin/heroic/resources/app.asar/build/electron/main.d61a4184.js:35:13035
at Set.forEach (<anonymous>)
at R.loadAll (/app/bin/heroic/resources/app.asar/build/electron/main.d61a4184.js:35:13018)
at R.getGames (/app/bin/heroic/resources/app.asar/build/electron/main.d61a4184.js:35:7787)
at /app/bin/heroic/resources/app.asar/build/electron/main.d61a4184.js:112:9238
at node:electron/js2c/browser_init:193:567
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11606)
at EventEmitter.emit (node:events:527:28)
```
Looks …

[Legendary] Handle cases where CustomAttributes is undefined when getting cloud saved folder

---

src/frontend/screens/Settings/sections/GeneralSettings/index.tsx

This PR adds the theme-related options in the General Settings screen.
It was reported a few times that some people cannot find the theme selector because they expect it to be in the general settings and don't think it would be in the accessibility screen. With this change it shows in both places so it's in a common place for most users and it's also in the Accessibility screen for users that need to change the theme for accessibility reasons.
---

Theme selector in general settings

---

.github/workflows/build-prs-linux.yml
.github/workflows/build-prs-mac.yml
.github/workflows/build-prs-windows.yml
.github/workflows/build.yml
.github/workflows/codecheck.yml
.github/workflows/lint.yml
.github/workflows/test.yml

This PR updates the github workflows to trigger also on PRs against the `stable` branch.
Should I remove the `beta` from there? maybe after we are comfortable with the new workflow?
---

Update github workflows for 'stable' branch

---

src/backend/howlongtobeat/electronStores.ts
src/backend/howlongtobeat/utils.ts
src/backend/utils.ts
src/frontend/components/UI/HowLongToBeat/index.tsx
src/frontend/screens/Game/GamePage/index.tsx

Moved the squares with the info a bit down since it was causing a annoying layout shift when opening the game page, even with cached data.
---

[UI/UX] Cache HowLongtoBeat Data and move squares down

---

src/frontend/screens/WineManager/index.tsx

This PR fixes a couple of issues in the Wine Manager present in the latest release:
- Proton items were not showing any status update (installing/progress/unzipping)
- After making a change in a Proton item, it was re-rendering the list for Wine-GE instead
---

[WineManager] Fix status update

---

.github/workflows/build-prs-linux.yml
.github/workflows/build-prs-mac.yml
.github/workflows/build-prs-windows.yml
.github/workflows/build.yml
.github/workflows/codecheck.yml
.github/workflows/draft-release-linux.yml
.github/workflows/draft-release-mac.yml
.github/workflows/lint.yml
.github/workflows/test.yml
package.json
yarn.lock

This adds an arm64-optimized build for macOS.
Note:
ARM packages will show as damaged since they are not signed by an Apple ID certified Developer, so this command is required to make it work:
`xattr -d com.apple.quarantine | mdfind kMDItemCFBundleIdentifier = "*heroic"`
---

[macOS] Add arm64 build

---

src/frontend/components/UI/ActionIcons/index.tsx

This PR fixes #1878 
Icons in the library had an `active` color that had no real meaning, since the meaning is the icon itself and not the color.
Now icons are always white except when hovered.
Only exception for this change was the Favorites icon that should eventually be moved to a `filters` dropdown to turn filters on/off instead as described here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1881#issuecomment-1272342402 by billie.
---

[UI] Remove 'active' color from library icons

---

src/backend/__mocks__/electron.ts
src/backend/__tests__/main_window.test.ts
src/backend/dialog/dialog.ts
src/backend/downloadmanager/downloadqueue.ts
src/backend/downloadmanager/utils.ts
src/backend/games.ts
src/backend/gog/games.ts
src/backend/legendary/games.ts
src/backend/main.ts
src/backend/main_window.ts
src/backend/online_monitor.ts
src/backend/protocol.ts
src/backend/recent_games/recent_games.ts
src/backend/shortcuts/nonesteamgame/nonesteamgame.ts
src/backend/tray_icon/tray_icon.ts
src/backend/utils.ts
src/backend/wine/manager/ipc_handler.ts
src/backend/wine/manager/utils.ts

This PR is a refactor related to how we interact with the main window. It removes some duplication and also while adding tests I found a bug.
Some comments on the changes:
- moved the code that creates the main BrowserWindow object into its own module
- the module takes care of the BrowserWindow object creation with the saved size/position and the sending of the messages to the frontend (abstracting the `window.webContents.send` logic)
- the module takes care of the logic of checking if a window exists before sending a message, so we can remove a lot of duplication
- by doing this I was able to remove the reference to the main window that Game objects had as `this.window`, it makes more sense for games to not depend on that
- I found a bug in the window creation logic, the condition to …

[Refactor] Main window creating and send message to the frontend

---

.github/ISSUE_TEMPLATE/bug_report.yaml

This PR adds a small change in the PR template to let users know which one is the latest version of Heroic, in case someone tries to report a bug in an older version.
Also moved the version to a dropdown so it's easier to pick between `Latest Stable` `Latest Beta` and `main branch from GitHub`.
This is how it looks:
Putting this here as an idea, I understand if there's a concern that this can get outdated and you prefer not to use this.
---

Indicate latest heroic version in bug report template

---

src/backend/gog/games.ts
src/backend/gog/setup.ts
src/backend/utils.ts

Changed `execAsync ` for `spawn `so the Setup won't fail when there is space in the game name folder, that was the main cause of this issue. Also, `Start-Process` was not being recognized since it was being used on cmd instead of `powershell`. so it was failing because of that as well.
Another issue was that sometimes it was failing because it was trying to access Wine configurations and they were undefined since it is not Linux/mac.
---

[Fix] GOG games Setup on Windows

---

src/frontend/components/UI/SearchBar/index.css

The result box based on the search bar input was positioned slightly to the right. This made it look out of place.
This PR aims to fix that by vertically aligning the autoComplete result box to the search box by altering the top and left margins.
Old PR #2240 
---

[UI] Fix autoComplete list box position

---

src/backend/gog/games.ts
src/backend/gog/library.ts
src/backend/legendary/games.ts
src/backend/legendary/library.ts
src/common/types.ts
src/common/types/epic-graphql.ts
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Game/GameRequirements/index.tsx

This PR fixes #1160 
Instead of trying to generate a url for an Epic game based on its title, this PR changes that to use the response of the API we use to get the requirements which also includes the `_slug` property.
It's important to clear heroic's cache to test this (or at least clear the `./config/heroic/lib-cache/gameinfo.json` file), since we cache the games extra info in an electron store.
---

[Fix] Get store links for Epic from API response

---

src/frontend/screens/Library/index.tsx

This PR changes the InstallModal import to not be lazy-loaded.
This fixes 2 problems:
- since it was lazy loaded, Suspense was triggered and rendering a Loading screen for a moment, making the UI flash
- because of the Suspense changing the content, the list was re-rendered completely after
---

[UI] Prevent flash when opening an installation dialog for the first time

---

src/backend/api/helpers.ts
src/backend/gog/games.ts
src/backend/gog/library.ts
src/backend/legendary/games.ts
src/backend/legendary/library.ts
src/backend/main.ts
src/common/typedefs/ipcBridge.d.ts
src/common/types.ts
src/common/types/epic-graphql.ts
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Game/GameRequirements/index.tsx

This PR includes a few tweaks and fixes related to the extra info of games:
- The extra info is now only fetched when entering the game page and not when fetching any gameInfo data, that should reduce the first render of the library significantly since we where waiting for 2 extra requests per epic game to get the extra info (one graphql request to get a page slug and one to get the actual info)
- We were using `language` from the app config but the language value is stored in the configStore actually
- If the language was undefined for any reason, the url was invalid, now it has an `en` fallback
- If we couldn't find a page slug we were falling back to the appName but that's probably never valid, now it converts the game title into a slug (it fixes a missing description for rocket league …

Extra info tweaks and improvements

---

src/frontend/themes.css

This PR fixes two issues with the visibility of elements in the Alternative Login flow in 2 themes.
1 - It fixes #2244 by using a lighter color for the input field in the Default themes
before:
after:
2 - It fixes the `alternative login` epic logo in the Nord Light theme:
before:
after:
---

Alternative Login visibility fixes

---

src/backend/main.ts

We have the new feature to remove the game settings/logs when uninstalling a game and I noticed it was not deleting the `...-lastPlay.log` file.
This PR adds that and a small refactor since I was adding a third block or similar code.
---

Remove `lastPlay` log when uninstalling a game

---

src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.css
src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
src/frontend/screens/DownloadManager/index.tsx

This PR fixes 3 issues I found in the download manager.
- When a game finishes downloading and a new one starts, the new game has the previous game's picture
- When a game finishes downloading, the next elements in the queue have the wrong image from the previous element in the list
- Some images have images with a different aspect ratio (like Far Cry 5)
Issues 1 and 2 only are noticeable if looking at the Downloads screen when a game finishes and there are elements in the queue (re-entering the Downloads page fixes the images)
Before the aspect-ratio fix:
After:
---

[Download Manager] Some images fixes

---

src/backend/game_config.ts

There's an issue in the current stable release (and probably present since a long time ago) were the list of env variables in the default settings would show env variables that are NOT configured as default values but that are configured in games.
There's no issue in github and no easy way to test the actual error if you are not currently experiencing it, but once the problem is there it seems to happen 100% of the time.
There was a discussion in the `#gaming` channel in discord ending with the confirmation that this change fixes the problem for users experiencing it https://discord.com/channels/812703221789097985/818939492244258826/1056785006833438730
The problem was: When reading settings for games, we initially get the default settings and then we override values from the actual …

Prevent default settings env variables corruption

---

src/backend/shortcuts/nonesteamgame/nonesteamgame.ts

When removing games from steam, if the shortcut cannot be removed because of an error, we are currently not logging the error because there's a check to avoid notifications that happens too soon.
This PR changes that a bit to only ignore the notification IF there's no errors during the removal. If there's any error, show the notification and log the information.
---

Ignore remove from steam notification only if no errors

---

src/frontend/helpers/gamepad.ts

When I implemented the gamepad support to navigate heroic, I added a bunch of `console.log` to help debug issues. We haven't had any major problem with the controller that would require logs so far and it's adding A LOT of noise in the devtools console, hiding other more important messages.
This PR just comments out the code that logs things, if we need to debug anything we can just uncomment this in the future.
---

Stop logging all controller interactions

---

src/frontend/components/UI/UninstallModal/index.tsx
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/state/GlobalState.tsx

I found some issues when uninstalling and running games and the frontend not updating the status accordingly. The issues seem to happen when trying to uninstall/run a game in the same Heroic session when the game was installed (but from the solutions I think it some problems could affect other cases that I couldn't identify better).
The may problems were:
- we were not triggering a new refresh from the frontend after a game was uninstalled
- the GameCard's game info was not updating properly when a game was uninstalled
- the game card was not updating the status to the `playing` status (button was not changing properly)
How to test the original issue in the current `stable` branch:
- install a game
- without closing heroic, uninstall the game (game still shows up as installed, sometimes …

[FIX] Game status detection when uninstalling/running games

---

src/backend/__mocks__/config.ts
src/backend/config.ts
src/backend/constants.ts
src/backend/game_config.ts
src/backend/gog/games.ts
src/backend/gog/setup.ts
src/backend/launcher.ts
src/backend/legendary/games.ts
src/backend/legendary/user.ts
src/backend/main.ts
src/backend/recent_games/recent_games.ts
src/backend/shortcuts/nonesteamgame/nonesteamgame.ts
src/backend/shortcuts/shortcuts/shortcuts.ts
src/backend/tray_icon/__tests__/tray_icon.test.ts
src/backend/tray_icon/tray_icon.ts

This PR is a refactor on the way we load the application settings to make it synchronous.
There are a few benefits of this:
- usually, sync code is easier to manage than async code (it's easy to miss awaits)
- because of the load being async, we were actually loading the config multiple times because promises were running in parallel until one of the promises finished and it was stored in memory, now we only read the files once and store the settings in memory, I noticed this problem while debugging this issue https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2262
- I was able to convert other functions that were async into sync too
- I was able to remove a magic ignore ts linter comment, handling config being undefined properly by making it protected
---
Use the following …

[Refactor] Load settings synchronously

---

src/backend/legendary/eos_overlay/eos_overlay.ts
src/backend/main.ts
src/backend/sideload/games.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/components/UI/UninstallModal/index.tsx
src/frontend/screens/Game/GameSubMenu/index.tsx
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Settings/sections/AdvancedSettings/index.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

This is another PR that I'm extracting from the original game status refactor PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1857
Since that PR got too out of date and it's hard to rebase it, I found it easier to extract smaller and easier-to-review PRs to eventually move all that code.
With these changes, status updates for uninstalling/moving/repairing games and installing/updating/uninstalling the EOSOverlay installation are pushed from the backend to the frontend, the same way other status updates are handled for game installation or game progress.
This makes it more consistent to always push updates from the backend and the updates are pushed closer to the source of actual action.
With this I was also able to remove the `handleGameStatus` function in the …

[Refactor] Push status updates from the backend to the frontend

---

public/locales/en/gamepage.json
src/frontend/screens/Library/components/GameCard/index.tsx

This PR adds a new item in the game card's context menu with the text `Details` that opens the game page.
This is an attempt to add some discoverability of that page, since many users do not know it exists.
---

[UX] Open the game page from the card's context menu

---

src/backend/logger/__tests__/logfile.test.ts

When generating a 1-month-ago date, we were handling month 0 in a special case (and then not correctly handling it). This is actually not necessary, since JS takes care of this on its own
---

[Fix] Log file deletion logic

---

src/backend/utils.ts
src/frontend/screens/Settings/components/AltGOGdlBin.tsx
src/frontend/screens/Settings/components/AltLegendaryBin.tsx

After the refactor of the settings, I introduced by mistake some setting variables changes and in the case of the alternative binaries there was even a problem with the logic (setting was changed with one key using the settings context and with a different key updating the configStore explicitly). The problem was that removing the binary didn't update the values properly.
This PR fixes that by removing that extra code and using the binary we actually display in the settings.
The problem before this PR was easy to reproduce:
- set an alternative binary
- check the logs that it's using the alt binary to check its version
- remove the alternative binary
- check the logs, it still uses the previous alt binary to check the version instead of the built in binary
- set the built in binary as the …

[Settings] Update Alternative binary settings correctly

---

src/frontend/components/UI/ControllerHints/index.tsx

This changes a regex to match for vendor id for Sony controllers, that way all their devices will have Sony prompts
This fixes the issue with DS4 having Xbox prompts

[Gamepad] Match sony devices by vendor id

---

src/frontend/components/UI/Sidebar/index.css

The sidebar's main items undergo a minimal scaling effect when hovered, just like the game cards.
This effect does not apply to the sub-items. 
_Demo:_
https://user-images.githubusercontent.com/74495920/209443184-1279f2f5-d0d1-4567-b61d-e9a6bbb44674.mp4
---

[UI] Add scaling effect on sidebar hover

---

src/backend/launcher.ts

Winemenubuilder is responsible for adding application shortcuts & managing file associations. For most users, it it more known as the reason all their `.ini` files are suddenly opening in Wine's Notepad
Disabling it is, in my opinion, the more sensible option. It is, for example, also done by Lutris (see [their FAQ](https://lutris.net/faq#winemenubuilder))
---

Disable Winemenubuilder when launching with Wine

---

src/frontend/state/GlobalState.tsx

A few days ago I made this PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2257 fixing some issues with the handling of the game status updates, the fix for the `playing` status was incorrect (it catched some of the problems just by luck)
This PR has a proper fix for that an a small refactor to remove a lot of the duplication.
The main problem is that, when installing multiple games at once and then trying to run them without restarting heroic, in some cases the `playing` status was not handled correctly and it was showing the game as not playing.
---

Proper "playing" status detection

---

src/backend/main.ts

I found this by accident, apparently when using middle click some ui parts were able to launch new window, which was obviously broken.
So I added the open handler which prevents mainWindow.webContents of using `window.open()` for spawning new windows for internal links.

[UX] Prevent spawning separate window of heroic ui

---

src/backend/launcher.ts

In #2298, I had *intended* to append the WineMenuBuilder override to an already-set `WINEDLLOVERRIDES` variable if one is present. While doing that however, I was accidentally searching for a variable with the name "WINEMENUBUILDER" instead
That's now fixed
---

[Fix] Actually search for WINEDLLOVERRIDES when disabling WineMenuBuilder

---

src/backend/tools.ts

Either old or debug code was left behind in the tools-installation routine, which blindly wrote data to a file using `exec()` without escaping either the data nor the file name, leading to errant writes when the game title contained one or more spaces.
This patch simply deletes the operation as a correct routine to write the file immediately follows it.
This fixed #2335.
---

Remove debug code leftover

---

src/backend/main.ts

This PR fixes a regression, sideloaded apps are not launching, failing with an error in the backend:
```
(22:43:44) ERROR:   [Gog]:              Could not get game info for vNj6P8g9LTCQskZ8bzPkip, returning empty object. Something is probably gonna go wrong soon
Error occurred in handler for 'launch': TypeError: Cannot read properties of undefined (reading 'platform')
at _GOGGame.isNative (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.53e831e0.js:4068:37)
at /home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.53e831e0.js:13651:18
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
at async node:electron/js2c/browser_init:193:551
```
This changes the order to first check if it's a sideloaded app, and, if not, then it will check if it's a …

[Sideload] Only check extGame if not sideloaded app

---

src/backend/games.ts
src/backend/gog/games.ts
src/backend/legendary/games.ts
src/backend/main.ts
src/common/types.ts

When using the `Run EXE in prefix` option, the file is not executed in the file's directory as the working dir. This is a problem because it can break executables that reference other files relative to the current working dir.
This PR does 2 things:
- update `runWineCommand` for games to have the same signature as the generic `runWineCommand`
- pass the exe's dir as the `startFolder` to run the commands
The way I'm testing this is with Rayman 2 The Great Escape from GOG (I think it was a giveaway). It has a `GXSetup.exe` file in the install folder that needs to run with the correct working dir or it fails.
---

Use the exe's dir as the working dir to run exe in prefix

---

src/frontend/screens/Game/GamePage/index.scss

For small screens (like the steam deck), when the controller hints appear there's a double scrollbar and you can see the store logo is outside the space. This PR fixes that.
Before:
After:
---

[UI] Remove double scrollbar in game page for small screens

---

src/frontend/screens/Library/components/GamesList/index.tsx

I noticed this bug that, if you type in the search field a few characters relatively fast (not really that fast), after a moment the search result was the one from the first character press and not the last. This was because the new letter updated things and a the useEffect of GameList was triggering without cleaning up the previous useEffect.
---

[UX] Prevent old search to step on new search

---

src/frontend/screens/Game/GamePicture/index.css

In some combinations of theme and game cover, the `back` button is kinda hard to see. This PR adds a small faded shadow behind that button. For example:
Before:
After:
---

[UI] Improve contrast of back button in game page

---

src/backend/api/downloadmanager.ts
src/backend/games.ts
src/backend/gog/games.ts
src/backend/jest.config.js
src/backend/legendary/games.ts
src/backend/shortcuts/nonesteamgame/__tests__/nonesteamgame.test.ts
src/backend/sideload/games.ts
src/backend/tray_icon/__tests__/tray_icon.test.ts
src/backend/wiki_game_info/__tests__/wiki_game_info.test.ts
src/backend/wiki_game_info/applegamingwiki/__tests__/utils.test.ts
src/backend/wiki_game_info/howlongtobeat/__tests__/utils.test.ts
src/backend/wiki_game_info/pcgamingwiki/__tests__/utils.test.ts
src/backend/wiki_game_info/wiki_game_info.ts
src/backend/wine/manager/downloader/__test__/main/getter.test.ts
src/backend/wine/manager/downloader/main.ts
src/backend/wine/runtimes/__tests__/runtimes/utils.test.ts

Originally part of #2176
Jest now knows about our `baseUrl`, making imports from `backend/...`/`common/...` possible. Nothing groundbreaking, just a nice-to-have when writing tests
---

[Tech] Resolve `baseUrl` in tests

---

src/backend/config.ts
src/backend/wine/manager/downloader/constants.ts
src/backend/wine/manager/downloader/main.ts
src/backend/wine/manager/downloader/utilities.ts
src/backend/wine/manager/utils.ts
src/common/types.ts
src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/frontend/screens/WineManager/index.tsx
src/frontend/state/GlobalState.tsx

This PR adds the ability to install Wine-crossover and Wine-Staging versions for macOS, making it even more simple for macOS user to play Windows games.
---

[Feat] Enable Wine Manager on macOS

---

src/frontend/screens/Settings/sections/GamesSettings/index.tsx

This PR fixes the wrong Settings options displayed for sideloaded games with the install platform as native (Linux/macOS).
It also refactors the way how games are identified as native using `window.api.isNative()`
---

[UI] Fix Incorrect Sideload settings and Refactor nativeGame

---

src/backend/launcher.ts

We are adding the `--filesystem=install_path` argument even if the value is undefined because we only check if the property exists in the object.
This PR changes that to check the actual value instead.
I had to use the `['install_path']` syntax because `install_path` does not exist for sideloaded games and typescript complains if I use the `.install_path` syntax.
---

Add --filesystem only if it install_path has a value

---

src/frontend/screens/Accessibility/index.css

Makes the zoom slider's appearance match the selected theme.
_Nord Dark_
---

[UI] Match Zoom slider look to theme

---

public/locales/en/gamepage.json
public/locales/pt_BR/gamepage.json
src/frontend/screens/Game/GamePage/index.tsx

This PR changes the `sync save` unsupported message as request here #2330
Thought about how to summarize the message to not just specify a platform. Feel free to give any sugestion!
---

[UI/Help] Changing unsupported sync save message

---

src/backend/gog/electronStores.ts
src/backend/gog/games.ts
src/backend/gog/library.ts
src/backend/save_sync.ts
src/backend/utils.ts
src/common/typedefs/ipcBridge.d.ts
src/common/types/electron_store.ts
src/frontend/helpers/index.ts
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
src/frontend/screens/Library/components/InstallModal/index.tsx

Basically the title.
cache the GOG install info by platform and also simplifies the Download Dialog that was doing some weird stuff to get the `installInfo` and the platform list.
---

[Tech] Refactor Download Dialog + Cache GOG Install Info

---

public/locales/en/translation.json
src/backend/online_monitor.ts
src/frontend/components/UI/OfflineMessage/index.tsx

This fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2389
Users for china may experience slow `online` detection because of the urls we ping to detect connectivity. This PR adds a clourflare url based on feedback by a user from China.
---

[Backend] Add cloudflare url to ping for connectivity check

---

src/backend/wiki_game_info/__tests__/wiki_game_info.test.ts

We didn't fixate the Date/Time in this test, causing it to fail if the test is run right before a second passes (so the test expects the "old" second while the tested function returns the new one)
This is now fixed using Jest's Fake Timers
---

[Fix] Flaky wiki_game_info test

---

src/backend/legendary/library.ts
src/frontend/state/GlobalState.tsx

We weren't checking for game updates when Heroic was launched. Now we are again!
See commit messages for details
I don't feel entirely confident about this fix (after all, the `library` check was *probably* there for a reason), but nothing seemed to explode when removing it
---

[Fix] Run game update check when Heroic starts

---

README.md

--no-quarantine makes brew skip the quarantine flag to the app bundle
---

[README] Add --no-quarantine for brew

---

package.json
src/backend/shortcuts/shortcuts/shortcuts.ts

Sanitize game title for shortcut creation.
Previously games like `Ruined King: A League of Legends Story` will silently fail and create an invalid shortcut named `Ruined King` in windows, due to not filtering reserved characters.
---

Sanitize shortcut names

---

src/backend/gog/setup.ts

This PR fixes a bug I noticed testing the new givewaway `Alien Breed: Impact`.
The script has this step:
```
"install": {
"action": "setIni",
"arguments": {
"conditions": [
"onLanguageChange"
],
"filename": "{app}\\AlienBreedEp1Game\\Config\\DefaultEngine.ini",
"keyName": "Language",
"keyType": "string",
"keyValue": "int",
"section": "Engine.Engine",
"utf8": false
}
},
```
And the section key is `Engine.Engine`.
We use the `ini` module that loads the `DefaultEngine.ini` into  js object and the structure is:
```
{
...
Engine: {
Engine: {
Language: ...
...
}
}
...
}
```
Without this change, we were doing `config[section]` which is actually `config["Engine.Engine"]` instead of `config["Engine"]["Engine"]`, causing the game to always fails with a Heroic error the first time (the game fails to …

[GOG] Handle nested keys in setIni action

---

src/frontend/themes.scss

This PR adds a few small fixes to some themes.
Dracula was showing many elements in light blue instead of white, and the library sort/filter icons didn't have a `hover` color.
In NordLight, options dropdown in the settings had a dark backround with dark text.
In Marine, Zombie, and Old School, the library sort/filter icons didn't have a `hover` color.
In some themes, the `heroic version` badge at the bottom left was showing the light blue text from the default theme and it looked weird with the color schema of the theme so I changed some of those. Also for this badge, the `hover` color on NordLight was too dark on a dark background.
---

[UI] Some themes fixes

---

src/frontend/helpers/gamepad.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2284
When using the steam deck, it's really common to switch between mouse/gamepad controller layout, there's an issue that if you prefer to use the mouse layout to controller heroic but, for any reason, you use the gamepad layout (like right after exiting or before starting a game) then you are locked in that heroic interface (without the settings/play buttons).
This PR changes that by detecting when the mouse moves and revering the layout.
Users can move back and forth between layouts by just using the different controller layouts and Heroic adapts.
---

[UX] Remove controller hints when using mouse

---

public/locales/en/gamepage.json
src/frontend/screens/Library/components/GameCard/index.tsx

This PR adds a `Logs` item in the game card's context menu:
We've had many users mentioning that they couldn't find the logs so this menu item should help with the UX of that.
I also moved the `Settings` up in the list, I think it makes more sense to have it next to the `Details` item.
---

[UX] Show game logs from card's context menu

---

src/frontend/screens/Library/components/GameCard/index.css
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Library/components/GamesList/index.tsx
src/frontend/screens/Library/index.tsx
src/frontend/types.ts

This is an alternative to https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2447
Instead of pagination, it renders all the library elements but for the ones that are outside of the viewport it renders an empty div until the element has to be displayed. Then it uses the IntersectionObserver to actually render the real content.
I'll add some comments in the PR.
There are still improvements that can be made (because of how react works, all hooks has to be defined before rendering the empty div, so there's extra unnecessary work there, also cards are re-rendered multiple times) but I'll leave those things for another PR.
You can see the empty divs using devtools and how they are updated when scrolling:
---
Use the following Checklist if you have changed something on the …

Render an empty div for game cards until they inter the viewport

---

src/frontend/hooks/hasStatus.ts

This PR fixes a bug in a maybe uncommon use case: if you install a game and, without restarting heroic, remove its folder, after refreshing the library the game does NOT show up as not available.
The issue was that, when a game is installed, the status in the frontend's state is set to `done` and that was preventing the `notAvailable` status to be considered.
---

Fix non-available status for games just installed

---

src/backend/gog/games.ts
src/backend/legendary/games.ts
src/backend/sideload/games.ts
src/backend/utils.ts

it may be dangerous, but we kill the game process anyways, so I don't think it matters too much if we kill the wineserver too, this would kill leftover wine processes (e.g game launchers) in the prefix when the kill button is pressed, which is crucial when side loading games. 

[Fix] Kill leftover wine processes after stop button is pressed

---

src/backend/gog/games.ts
src/backend/legendary/games.ts
src/common/types.ts
src/frontend/components/UI/Sidebar/components/CurrentDownload/index.tsx
src/frontend/hooks/hasProgress.ts
src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx

This fixes the problem with the inaccuracy of the download and disk speed.
The problem was that either legendary or child_process does not write/read stdout at the same time. Means we get actually two calls to `onInstallOrUpdateOutput` with one time the `eta` and `bytes` and the other time with the `disk` and `down` speed. We did not handled it and just returned earlier if `eta` or `bytes` is empty. The fix just stores the last values of the progress and send the progress if all values are fetched.
Applied the same strategy to gog aswell.
Here a video which shows that the change should fixed it:
https://user-images.githubusercontent.com/61798668/221420102-3c0265b2-1bf5-45dd-8c39-a4bb58e9765d.mp4
---

[Fix]: Inaccuracy of disk and down speed

---

src/frontend/components/UI/Sidebar/index.tsx

Sall fix by disabling the mouse pointer events on the `webview` element when dragging.
---

[FIX] Sidebar drag when on Webview Elements

---

src/backend/gog/games.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2303
using the `force: true` option, if the directory doesn't exist it won't throw an exception, allow the uninstall process to complete.
---

[GOG] Allow uninstalling gog games when not available

---

src/frontend/helpers/gamepad.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1975
We were checking the `isSelect` before the `insideInstallDialog` so the B button was getting captured by that element's behavior. Now being inside the install dialog has priority.
---

[UX] Close install dialog with B when select is focused

---

src/backend/gog/library.ts

This should improve the user experience for users loading the GOG library for the first time like https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1485
Instead of waiting for the images to be fetched before showing the library, this PR makes it so the GOG library is initially rendered with a fallback Heroic image and it triggers the images loading in the background.
Also, it splits the number of requests that are done in chunks of 20 requests to make them in parallel so for example a list of 100 games will be split into 5 chunks of 20 and the duration of the process is only the sum of the slowest request of each chunk instead of the sum of 100 requests.
After everything is processed, the information is stored and the frontend is notified to reload the library.
The …

[GOG] Fetch images in the background to speed up initial library render

---

package.json
public/webviewPreload.js
src/backend/api/misc.ts
src/backend/main.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/screens/WebView/index.tsx

This PR is a replacement of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1762
I think I found a simpler approach. Instead of overriding the epic functions, the injected JS just adds an `onload` function that, when the expected json response is present, will send a message to the host (the react app) with the code.
It is similar to the current login method but we don't rely on `find-in-page` and we don't mess with the user's clipboard.
The only thing I'm not sure about is that I was not able to make the `contextBridge.exposeInMainWorld` code work so I can't seem to hide the ipcRenderer under a function, but I'm only using it in a callback so I think it's still isolated?
---

[EPIC] Login with preload script

---

src/backend/main.ts

This PR closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2478
When launching a game, we have to remember if the window was visible and only show the main window when the game closes in that case.
---

[UX] Do not restore the window visibility if hidden when launch a game

---

.husky/pre-push

We run `yarn prettier` as part of our GH Workflows, but weren't running it when you actually tried to push. Thus, you might forget to run it locally, only for the workflow to then fail & you having to make a "lint commit" / force-push.
Most of us have our editors/IDEs configured to lint on save, but I'd say this is still a good safety net in case something goes wrong there.
The original reason to not do this ([here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2010#discussion_r1017058383)) was that `prettier-fix` changes file permissions, but just running Prettier without writing changes shouldn't touch those (please correct me if I'm wrong there, I cannot test this on Windows).
---

[Fix/Tech] Run Prettier on pre-push action

---

.eslintignore
.eslintrc
package.json
src/backend/__mocks__/electron.ts
src/backend/__tests__/constants.test.ts
src/backend/__tests__/main_window.test.ts
src/backend/__tests__/skip.ts
src/backend/logger/__tests__/logfile.test.ts
src/backend/logger/__tests__/logger.test.ts
src/backend/shortcuts/nonesteamgame/__tests__/nonesteamgame.test.ts
src/backend/wiki_game_info/applegamingwiki/__tests__/utils.test.ts
src/backend/wiki_game_info/pcgamingwiki/__tests__/utils.test.ts
src/backend/wine/runtimes/__tests__/runtimes/utils.test.ts
tsconfig.eslint.json

We weren't linting files outside of the "main" code (namely, tests). Now we do!
Note that I've disabled some rules for test files specifically that might be annoying there (you often "stub out" a function or use `any` in a mock, we don't want ESLint yelling at us there)
This has the nice benefit of our IDEs (at least Webstorm) no longer providing false errors on `backend/`, `common/` and `frontend/` imports, as those test files now actually belong to a project, as well as those weird errors around `.replaceAll` disappearing
---

[Tech] Lint all TS/TSX files in the project

---

public/locales/en/translation.json
src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx

Just added a title on the estimated time on the downloading page. Without a title, it's hard to understand what this time means.
---

[UI] title on ETA

---

src/backend/main.ts

This fixes this issue I get when running the app from source:
---

[EPIC] Add file:// to the preload protocol for login

---

src/backend/launcher.ts
src/backend/utils.ts

This PR fixes an issue where we were storing all the output of gogdl/legendary/wine/etc in memory for the duration of those processes. That means that for any process with extensive output we were storing maybe megabytes and megabytes of strings for no real use.
This PR changes that to only store the last 50 message (50 is a kinda arbitrary number thinking that we would care about the last messages of an output if needed (like to detect some error message).
This should have a beneficial impact in memory usage, specially when running games that output a lot of data when running through Wine-GE or for long installations (I've had installations extending for hours and we were storing a lot of text every single second).
In some cases the number of lines was so high that converting them to a …

[Performance] Do not store all the output of commands in memory

---

public/locales/en/login.json
src/frontend/components/UI/LanguageSelector/index.tsx
src/frontend/screens/Login/components/SIDLogin/index.css
src/frontend/screens/Login/components/SIDLogin/index.tsx

Added Features:
- Displays login URL
- Button to Copy the URL to the clipboard
- Button to Open Link in the Browser
Related Issue: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2245
Before: 
After: 
---

[UI] Display/allow user to copy alternate Epic login URL

---

package.json
yarn.lock

This resolves issues related to `check-disk-space`. We'll ultimately have to find *some* solution to this, as staying on Vite 3 doesn't sound like a good idea.
---

[Tech] Downgrade back to Vite 3

---

src/backend/shortcuts/utils.ts

This is simple addition that will load icon from API instead of using squashed cover:
Before:  
After:  
It may be necessary to manually delete icon from icons directory so new ones can be pulled.
**Note** squashed covers will still be used as fallback if for some reason API call fails

[Shortcuts] Use icon from api for gog shortcuts

---

src/frontend/screens/Game/GamePage/index.scss

Some elements in the game page are too wide and it's confusing that clicking on the right side of the screen can actually toggle on the popups for info/scores/etc.
This PR makes those elements only use the size they need and also limits the width of the `launch options` dropdown.
Before:
You can see the `Click to open` title floating on the right side, you can't tell what it will open
After:
In the after you can see the dropdown now matches the width of the button and also the outline of the element is just the space needed for the element.
---

[UI] Limit width of elements in game page

---

src/backend/sideload/games.ts

Whenever you started playing a sideloaded game, the status would be stuck on launching, this patch fixes that so that it now says playing!

[FIX] Fix sideload statuses

---

src/backend/gog/library.ts
src/backend/legendary/library.ts
src/frontend/state/GlobalState.tsx

This might fix the login issues that seems to be caused by 2 calls to `legendary list` happening at the same time.
We were doing 2 calls: one to refresh the library and, if checking updated, one to process the updates.
With this change we only do 1: if we are checking updates we don't do the first one (since checking updates now calls the same method), if we are NOT checking updates then we only do the first one.
---

Call `legendary list` only once when refreshing the library

---

src/backend/gog/library.ts

I noticed a regression caused by my refactor to load GOG images async. The `art_cover` was being set incorrectly, missing the protocol and the extension based on the previous code https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2480/files#diff-b81a7a1b73f7704fde02ec68ba60851c261a0139471d91fce4893769f9844330L637
This only happens in the main branch.
If you have this issue already in your configuration files you might need to delete the gog_store/library.json and store_cache/gog_library.json files so it gets updated (I guess clearing heroic cache should fix that too)
---

[Fix regression] Set correct horizontal image url for GOG games

---

src/backend/main.ts
src/backend/save_sync.ts
src/backend/tray_icon/__tests__/tray_icon.test.ts
src/backend/utils.ts

This PR includes two minor improvements to our save sync code, hopefully reducing the amount of questions we get about it
- As mentioned in the title, instead of returning the save path with variables (`{AppData}/SomeApp`, for example) when the actual path can't be computed, an empty string is returned instead
- The `Promise.race` in the IPC function was removed. Apart from the reason outlined in the commit message, it is also the only way *I* could test the first change (on a somewhat slow laptop, everything takes a little longer)
To test this change:
1. Open your `~/.config/legendary/installed.json` and locate a game with a `save_path` (if you don't have one, "Loop Hero" is quick to install). Delete that property, then mark the file as read-only.
2. Start Heroic, head to the same game; …

[Fix] Return an empty string when save path calculation fails

---

package.json
src/backend/gog/games.ts
src/backend/gog/library.ts
src/backend/utils.ts
src/frontend/helpers/library.ts
src/frontend/screens/Game/GamePage/index.scss
src/frontend/state/GlobalState.tsx

- Fix an issue with GOG games keep asking for an update after an update since the ETAG was not being updated on installed.json file.
- Fix an issue where when changing a GOG game path on macOS games, it was not adding the .app folder to the path.
- Fix an issue with importing native GOG macOS games, where we could not select the .app file, only the folder.
---

[FIX] GOG Fixes

---

src/backend/launcher.ts

self explanatory
desktop files were still being created and stuff, hopefully this fixes it
https://wiki.winehq.org/FAQ#How_can_I_prevent_Wine_from_changing_the_filetype_associations_on_my_system_or_adding_unwanted_menu_entries.2Fdesktop_links.3F

FIX: Fix winemenubuilder not being disabled

---

src/frontend/components/UI/SearchBar/index.tsx

As the title says, when you select an item from the autocomplete list, it will take you to the game page for that item rather than currently searching normally and just showing the single item on the grid.
Note: sorry the previous pull request got closed, I was trying to fix the git history and it deleted the branch and it wasn't giving me an option to reopen it
---

[Enhancement]: When selecting item from search bar, it will take you directly to item's game page

---

src/backend/main.ts

This PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2563/files introduced a regression. Because we are calling `writeFileSync` in the 2 places, the second call (system info) replaces the content of the file that had the content of the first call (the game settings).
Now it uses writeFileSync for the game settings and then appendFileSync for the system info to not override the content.
The game settings are now the first part of the file, before the 2.7 release the system info was first. This is not that easy to avoid since the system info fetch is async on purpose cause it can get stuck, so we can't wait for it to be the beginning of the file.
---

Fix missing game settings info in logs

---

src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx

This PR makes the store feature by adding a simple logic:
- Open epic store by default
- Open gog store only if gog account logged in
Solves #2620 
Tested with both epic and gog logged in, only epic logged in and only gog logged in.
---

[Enhancement] Add logic to Stores feature

---

src/frontend/components/UI/SearchBar/index.css

This PR intends to give a consistent look for the autoComplete box with the search bar. 
It also avoids search result items from getting crammed.
Before:
After:
---

[Fix] Searchbar and autoComplete UI

---

src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx

Fixes #2607
Adds a timeout of 3.5 seconds to get the image, otherwise gives up and uses the fallback.
Also keeps the field empty so people can see the placeholder that states that you can paste an URL there since some people were missing it.
---

[FIX] Image search on Add Game Screen blocking finish button

---

src/backend/storeManagers/gog/library.ts

This PR fixes a regression, when downloading gog games the image url is missing parts.
---

[GOG] Fix url for horizontal images for GOG downloads

---

src/backend/__tests__/cache.test.ts
src/backend/cache.ts
src/backend/storeManagers/gog/electronStores.ts
src/backend/storeManagers/legendary/electronStores.ts
src/frontend/helpers/electronStores.ts

This PR adds a tweak to the CacheStore class to allow `null` as the lifespan for the cache values. With that added I configured the libraries to not expire.
Another option is to move these back to a normal ElectronStore but I think this change is simpler.
This should fix some issues users have reported opening heroic for the first time in a given day:
- library going blank when offline for a day
- library getting re-fetched completely after a day
---

Allow 'null' as lifespan so cachestore does not expire

---

src/backend/api/misc.ts
src/backend/main.ts
src/frontend/components/UI/Sidebar/index.tsx

This pull request adds several hotkeys to improve the user experience of our application. The new hotkeys are as follows:
CommandOrControl+R: Reloads the app
CommandOrControl+Q: Quits the app
CommandOrControl+Shift+I: Opens the dev tools
CommandOrControl+K: Opens the Heroic settings screen on the frontend
CommandOrControl+L: Opens the library screen
CommandOrControl+J: Opens the downloads screen
---

[UX] Add Keyboard global shortcuts

---

src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts

This PR fixes a regression in 2.7.1 where the installation progress is not reported properly to the frontend.
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2680
---

Fix installation/update progress reports to the frontend

---

src/backend/api/misc.ts
src/backend/main.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/helpers/shortcuts.ts

This PR is an adaptation of the current globalShortcuts feature, instead of using globalShorcuts that are causing issues, it uses an event listener in the frontend and based on the different combinations it sends a message to the backend to be processed
This fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2676 and fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2671
---

[Fix] Handle shortcuts from the frontend without depending on menu

---

src/backend/storeManagers/gog/library.ts

Due to the error in obtaining the installation info for them, Linux-native (GOG) games were being installed on the system but not added to the Launcher as reported in #2678 . This workaround gets the Windows install info instead, proceeding with successful installation.
---

[Fix] Linux native games failing to add to launcher

---

src/frontend/state/GlobalState.tsx

Fix an issue that happens sometime when the GOG cache was cleared and heroic is restarted and the GOG library is empty. 
---

[FIX] Empty GOG library due to lack of cache update

---

src/frontend/screens/Login/components/SIDLogin/index.css
src/frontend/screens/Login/index.scss
src/frontend/screens/Login/index.tsx
src/frontend/themes.scss

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2703 and a few related issues I found while working on it:
- now both the login screen and the alt dialog are more responsive
- scrollbars appear when going to small
- many themes were missing the css variable for the backdrop/layer semi transparent black
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/32f6c657-82c3-4870-b06c-409ff4512e09
---

Make login screen more responsive

---

public/locales/en/gamepage.json
public/locales/en/translation.json
src/backend/api/downloadmanager.ts
src/backend/config.ts
src/backend/downloadmanager/downloadqueue.ts
src/backend/launcher.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/legendary/library.ts
src/common/typedefs/ipcBridge.d.ts
src/common/types.ts
src/common/types/legendary.ts
src/frontend/components/UI/DLCList/DLC/index.scss
src/frontend/components/UI/DLCList/DLC/index.tsx
src/frontend/components/UI/DLCList/index.scss
src/frontend/components/UI/DLCList/index.tsx
src/frontend/components/UI/UninstallModal/index.tsx
src/frontend/helpers/library.ts
src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Game/GameSubMenu/index.tsx
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/DLCDownloadListing.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
src/frontend/screens/Library/components/InstallModal/index.css

This PR adds the ability to:
- Select individual DLCs to be installed for Epic games, instead of installing all or nothing.
- Adds a new item on the Game Page SubMenu to open a DLC manager dialog where is possible to install and uninstall available DLCs.
- Works only for Epic for now, GOG keeps the current behavior until GogDL adds this feature as well.
- When selecting the DLCs on the install dialog, they will be added to the download Queue just after the main game.
---

[Feat] Add DLCs manager for Epic Games

---

src/frontend/components/UI/Sidebar/components/SidebarLinks/index.css
src/frontend/components/UI/Sidebar/index.scss

Ever since the scale hover effect was implemented on the Sidebar links (by me), I found it a bit weird over time.
This PR brings in a new and simple hover effect that slides the item to the left on hover.
[SidebarHover.webm](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/74495920/f4d14098-028f-4e06-8f1e-1274669fdfbb)
---

[UI] sidebar link effect

---

src/backend/main.ts

This fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2594
We were forcing the focus on the main window after a game was closed which was not great UX.
The are many scenarios when starting a game:
- game was started with no GUI (in this case the autofocus was already ignored)
- game was started from the try (in this case the autofocus was already ignored)
- game was started from the gui (the windows is back on focus after closing a game anyway since it was the last window with focus, even after removing these lines)
- main window is minimized/close while a game is loading (in this cases the window was forced to gain focus after close, even if the user explicitly move it out of the way, not it's not)
- sometimes a game takes a long time to actually end after …

[UX] Do not force focus on main window after closing game

---

src/backend/shortcuts/shortcuts/shortcuts.ts
src/backend/storeManagers/sideload/games.ts
src/backend/storeManagers/sideload/library.ts

This PR fixes two issues:
- Heroic was adding shortcuts for DLCs, but in general launching a DLC directly wouldn't work.
- Shortcuts creation/deletion failed for sideloaded apps
This fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2756
---

[BUG] Don't add shortcut for DLCs. Fix adding sideload app shortcuts

---

src/backend/storeManagers/legendary/library.ts

The issue with `legendary list --third-party` running twice at boot causing a race condition and invalidating the auth token has been back for a while.
This PR removes the extra call to `.refresh` so it will now run that only once (the frontend is triggering the refresh too)
Should fix https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2753
---

[Legendary] Refresh legendary only once at boot

---

src/frontend/screens/Settings/components/DownloadNoHTTPS.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2721
The onClick handler was always setting this to `false`
---

[Bug] Fix "no https" toggle not working

---

public/locales/en/gamepage.json
src/backend/api/library.ts
src/backend/cache.ts
src/backend/storeManagers/gog/electronStores.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/gog/library.ts
src/backend/wiki_game_info/gamesdb/utils.ts
src/common/types.ts
src/common/types/gog.ts
src/frontend/components/UI/ActionIcons/index.tsx
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Library/index.tsx
src/frontend/state/GlobalState.tsx

This is a test of trying to replicate how GOG Galaxy loads the library.  
We achieve this using galaxy-library endpoint which contains games from all connected integrations (updated by client), and GOG (updated internally). We filter out all the gog games and use those.  
If we decided to go hardcore we could maybe support those integrations in the future in some way.   
Of course this can be further extended in terms of caching and deciding whether to fetch new data for games.
One proposition is to verify if we have up to date data when opening the game page.  
~~For now I'm marking it as wip (library pagination is still to be done)~~
Additionally the galaxy-library endpoint provides us with certificates that somehow in pair with GOG access token allow us to get data from gamesdb that …

[GOG]: Switch to Galaxy way of loading library

---

src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/gog/library.ts

This caused issues like install path being root folder of all installed games. Upon uninstalling it removed all of them

[GOG]: avoid removing folder_name between library refresh

---

public/locales/en/translation.json
src/backend/shortcuts/shortcuts/shortcuts.ts
src/frontend/screens/Settings/components/Shortcuts.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2810
With this PR we can configure if shortcuts for games should be added to Launchpad on Mac, so there's better feature parity between OSes.
---

[Mac] Allow disabling automatic Applications shortcut creation

---

src/backend/wiki_game_info/__tests__/wiki_game_info.test.ts
src/backend/wiki_game_info/protondb/__tests__/utils.test.ts
src/backend/wiki_game_info/protondb/utils.ts
src/backend/wiki_game_info/wiki_game_info.ts
src/common/types.ts

Support in getting compatibility information from ProtonDB
Tests pending approval of basic logic.
---

[Feature]: Provide Protondb information on game page

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

This PR updates the issues templates to remove the `[Bug]` and `[Feature Request]` prefixes.
I also removed the option to pick Heroic Beta in the version selector and added Stable Flatpak because I think it's something important in many cases and people is not always clear with that.
---

Remove prefix from issue template title, remove Beta

---

src/frontend/components/UI/PopoverComponent/index.scss
src/frontend/components/UI/PopoverComponent/index.tsx

This PR fixes an issue where the popover component was not visible when used inside a modal.
Because of how the MaterialUI `Popover` component works, it was added to the document body, and it was always behind the `dialog` element and it was impossible to bring it to the front.
I tried many options of the Popover component to put it inside the dialog which partially fixed this but then the positioning was broken.
At the end I decided to go with a simpler solution implementing a similar functionality to have more control and to avoid all the weird things the MUI component was doing (adding styles, extra elements, scrolling the container, etc).
I tried this in:
- the settings as a normal page
- in game settings in a dialog
- in the `installation information` `time information` etc links in …

[Bug] Fix popover inside settings dialog

---

src/backend/constants.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/legendary/library.ts

Legendary's configuration will now be stored in a Heroic-specific location. This avoids issues where users change their `config.ini` and in turn change Heroic's behavior.
Existing configuration data will be migrated automatically, meaning anyone testing this PR *should* not notice anything out of the ordinary.
The original issue I've aimed to solve here was reported on our Discord ([here](https://discord.com/channels/812703221789097985/1093506682673446983)): When launching a game, we used to run `legendary launch <AppName> --json --offline` to get Legendary's original launch configuration for the game. This is problematic on macOS systems without CrossOver installed, as Legendary will crash when trying to auto-detect a version.
With us now controlling the config file, we simply don't have …

Set Legendary's config path to a Heroic-specific location

---

src/backend/storeManagers/gog/library.ts
src/common/types/gog.ts

This should prevent packs that are not games itself like  [The Incredible Machine Mega Pack](https://www.gogdb.org/product/1207658799) from displaying in library.

[GOG]: ignore pack game type

---

src/frontend/screens/Library/components/GameCard/index.css
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Library/components/GamesList/index.tsx
src/frontend/screens/Library/index.css

Although this is not part of the Figma design, I thought of using the cover art for the just recently played game. Kind of like how several game launchers do.
This PR introduces the `justPlayed` property for the `Card` interface that is set to`true` for the first game under the Recently Played `GamesList`. If `true`, the `GameCard`' uses game's `art_cover` as the `src`.
The covert art box occupies two grids for correctly containing the art.
---

[UI] Use cover art for the most recently played game

---

src/backend/storeManagers/gog/library.ts
src/frontend/screens/Library/components/GamesList/index.tsx
src/frontend/screens/Library/index.tsx

Like #2862 it fixed the recent layout. 
Also added higher res icons for GOG horizontal artwork
While looking into GamesList I added more unique key for GameCard component, which should prevent some appName collisions

[FIX] Favourites layout

---

src/frontend/screens/Library/components/RecentlyPlayed/index.tsx

When using the only show installed option, it shows the wrong number of gamecards, this PR fixes that. 

[FIX] Show correct number of gamecards in recently played.

---

src/backend/storeManagers/nile/games.ts

This is small PR. Basically we avoid running post install instructions on Linux and Mac, since they will be ran every time prefix gets updated, like changing it's location or wine version.

[NILE] run PostInstall setup after install only on Windows

---

src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/utils/compatibility_layers.ts

When launching GPTK, Heroic simply uses the underlying `wine64` binary. This binary is a (mostly) normal Wine binary, meaning it's meant to be launched with the WINEPREFIX environment variable set to the desired Wineprefix & a single argument (the executable to run). `gameportingtoolkit` on the other hand is the wrapper around Wine, not taking in a WINEPREFIX & instead requiring two arguments (the prefix, then the executable to run)
We were running `wine64`, but were passing it parameters intended for `gameportingtoolkit`. I'm not sure how this ever worked
While touching the responsible function (getWineFlags) I've also made it a little more type-safe & removed the unused `gameSettings` parameter
Note that I cannot test this myself, as I don't have a device running macOS, however there …

[Fix] Treat GPTK Wine like regular Wine

---

src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/gog/library.ts

Due to recent CDN issues, this change switches to updated `_version=2` API, which provides fallback CDNs.

[GOG]: fix obtaning manifest for updates check

---

src/backend/launcher.ts
src/backend/storeManagers/legendary/library.ts
src/backend/storeManagers/nile/library.ts
src/backend/storeManagers/nile/user.ts
src/frontend/components/UI/UninstallModal/index.tsx
src/frontend/state/GlobalState.tsx

This PR includes 3 fixes:
- a different fix for the issue where people got logged out from legendary (because the `list --third-party` command ran twice in parallel). The previous fix introduced a problem (the refresh library button was not working correctly for epic games). This PR reverts the previous change and, instead, it adds a new measure: when running a `runner` command, if the command is currently running we return the same promise instead of running the command twice in parallel.
This will also prevent an issue we have during development because of react's double rendering of components in strict mode: if a component runs a command to (for example) get the game install info, it was running twice before, with this the command is running and the second call would pick the previous …

[Fix] Library refresh issues

---

src/frontend/screens/Library/components/RecentlyPlayed/index.tsx

In the new version of Heroic we are properly ignoring DLCs in listings, but in previous versions you can still click `Play` in a DLC and it will fail but the game is still added in the `Recently played` list.
Because we are now hiding DLCs properly, if the element happens to be the first in the list, it's ignored but then the feature to display the first element bigger breaks because the indexes change and the `justPlayed` class is not set, and there's no way to remove the non-visible element from the list to manually fix the issue (apart from editing the config files manually).
This PR fixes that by ignoring DLCs when getting the list of recently played games.
---

[Fix] Skip DLCs when listing recently played games

---

src/frontend/screens/Game/GamePage/index.tsx

GamePage will request and show install info only when online 

[UX]: request install info only when online

---

src/backend/storeManagers/nile/library.ts
src/backend/utils.ts
src/common/types/nile.ts
src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/frontend/components/UI/StoreFilter/index.tsx
src/frontend/screens/Library/index.tsx
src/frontend/screens/Login/index.tsx
src/frontend/screens/WebView/index.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

- Updated nile to store install size in `installed.json`   
- Additionally I reproduced how nile creates folder names to avoid miss matches
- Changed how we determine if user is logged in, as username can be empty (added a fallback for login page to `Unknown` for that case)

[FIX]: Multiple Amazon Games bugs

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/workflows/update-bug-template-on-release.yml

This PR does 2 things:
- Updates the `Latest version` in the bug template
- Adds a github workflow that runs when we publish a new release that will automatically create a PR doing this change
You can check it working here in this test repo: https://github.com/arielj/release-update-template/pull/6
---

Update version in bug report template, and add workflow to automate this

---

src/frontend/screens/Game/GamePage/index.scss

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2915
The menu was rendered with z-index: 0 by default and the elements like `Installed Information` `Game Scores` etc had the same z-index value, because they come after in the DOM they had the focus.
---

[Fix] Fix three-dots menu closing when hovering certain items

---

src/backend/launcher.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2916 and fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2905
I added some code to prevent running the same command twice in parallel (to prevent the epic logout issue), but I didn't know that `then` and `catch` on promises does NOT change the current promise but it actually returns a new object, so I was storing/caching the current promise without handling the catch.
Because the first step installing the overlay is to get the size and then abort the command, it was throwing an exception instead of handling it silently.
---

[Fix] Installation of EOS Overlay

---

package.json
src/backend/launcher.ts
src/backend/save_sync.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/__tests__/games.test.ts
src/backend/storeManagers/legendary/commands/auth.ts
src/backend/storeManagers/legendary/commands/base.ts
src/backend/storeManagers/legendary/commands/cleanup.ts
src/backend/storeManagers/legendary/commands/eos_overlay.ts
src/backend/storeManagers/legendary/commands/import.ts
src/backend/storeManagers/legendary/commands/index.ts
src/backend/storeManagers/legendary/commands/info.ts
src/backend/storeManagers/legendary/commands/install.ts
src/backend/storeManagers/legendary/commands/launch.ts
src/backend/storeManagers/legendary/commands/list.ts
src/backend/storeManagers/legendary/commands/move.ts
src/backend/storeManagers/legendary/commands/status.ts
src/backend/storeManagers/legendary/commands/sync_saves.ts
src/backend/storeManagers/legendary/commands/uninstall.ts
src/backend/storeManagers/legendary/eos_overlay/eos_overlay.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/legendary/library.ts
src/backend/storeManagers/legendary/user.ts
src/backend/storeManagers/nile/games.ts
src/backend/utils.ts
src/backend/utils/compatibility_layers.ts
src/common/types/game_manager.ts
yarn.lock

This PR adds strict type checking to Legendary commands using [Zod](https://zod.dev/). Before a command can be ran, the caller of `runLegendaryCommand` has to verify that, for example, strings that should be non-empty are actually non-empty, numbers are integers & positive (if necessary), paths are valid paths, and so on
Details on how this is achieved / what the design decisions behind things were are in the commit messages
~~I've only tested this on Linux, I can test it on Windows in the coming days~~
Seems to be working fine on both Windows & Linux
---

[Tech] Type-check Legendary commands

---

public/locales/en/translation.json
src/backend/storeManagers/storeManagerCommon/games.ts

Closes #2938  
Heroic will now confirm if you want to close the window if website prevents the unload

[Browser]: handle before unload event properly

---

src/backend/utils.ts

Prevents wineboot -k from starting the prefix rather than stopping it when the prefix wasn't init in the first place.

[FIX] Use wineserver -k when available

---

src/backend/main.ts
src/backend/main_window.ts
src/common/types.ts
src/common/types/electron_store.ts

Closes #2850
One small thing though, window will not remember it's original size in non-maximized state, as this is behaviour of getBounds 

[FIX]: remember if window is maximized

---

src/frontend/components/UI/DLCList/DLC/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/DLCDownloadListing.tsx

This fixes an issue that was happening when toggling the 'Install all DLCS' for Epic games. All DLCs were not being added to the Queue, only one of them.
tested with Dying Light Enhanced Edition and Fallout New Vegas.
---

[FIX] Install all DLCs not adding them to the queue

---

src/backend/storeManagers/legendary/library.ts

86e2e11ce6b4639b186da7fdcac3c3ea6482d2f0 completely broke updating, fix that up by also supplying the `appName` for the `update` subcommand.
---

[FIX] Unbreak legendary update command.

---

public/locales/en/translation.json
src/backend/api/misc.ts
src/backend/utils/ipc_handler.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/screens/Login/components/Runner/index.css
src/frontend/screens/Login/components/Runner/index.tsx
src/frontend/screens/Login/index.scss
src/frontend/screens/Login/index.tsx

This PR disables the login buttons if we detect the OS is MacOS older than version 12 and shows a message to the user to clarify that.
Even with the readme and the information in the downloads page in the websites, users of MacOS 10/11 still try to run Heroic and ask for support when it doesn't work.
This PR makes it more explicit in the Log In page itself so the users can see the answer there without the need to ask in discord.
This is how it would look:
(I don't have that version of MacOS so I faked some values to generate the image, but I know the logic works since I also tested using version 14 as the limit (and I have MacOS 13) and the message was displayed)
This partially fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2071, but not completely since I …

[Mac] Disable the login buttons for MacOS older than version 12

---

src/frontend/screens/Settings/sections/LogSettings/index.tsx

This PR brings adds a simple visual feedback for the user when the log is copied to the clipboard.
The ContentCopyIcon is replaced by the Done icon for a couple seconds. The user can be sure that the log has been successfully copied.
---

[UI] Add user feedback when copying log to clipboard

---

public/locales/en/gamepage.json
src/frontend/components/UI/Anticheat/index.tsx
src/frontend/hooks/hasAnticheatInfo.ts
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx

This PR adds an extra confirmation dialog when trying to install a game that we have data about its anticheat support being broken/denied.
We keep getting users asking about Fortnite for example even with the message in both the game page and the install dialog.
This will add another barrier for users to understand these games will not work, and they have to click a button that says `I UNDERSTAND THIS WILL NOT WORK` to even install the game.
This has no impact on games where the anticheat works so it only adds one barrier to prevent extra support tickets.
You can see it working in this video:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/b3ae8035-2bb7-493e-8d52-be649acc54ff
---
Use the following Checklist if you have changed something on the Backend or …

[Improv]: Confirm installing broken anticheat games

---

src/backend/storeManagers/nile/library.ts

If no game is installed, `nile list-updates` will return an empty string. Unfortunately, this is not valid JSON and `JSON.parse()` later bails out with an error.
We're good to go if no game is installed either way, so break out early and don't try to parse an empty string.
---

[FIX] Unbreak updating games list if user is logged in to Amazon account, but has no games installed.

---

src/backend/launcher.ts

This variable breaks fall guys on systems that have dotnet sdk installed (even through flatpak)
Solution: Set it to a blank path

[FIX] Fix windows dotnet applications from improperly working through wine

---

src/backend/launcher.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/storeManagerCommon/games.ts
src/common/types.ts

This adds two environment variables when launching games: `HEROIC_APP_NAME` and `HEROIC_APP_STORE`. Wrapper commands can use these to look up the app info in the Heroic config (e.g., to get the title or Wine prefix for save backup purposes, in my case).
I tested this on Windows 11 with GOG and Epic. I don't have any Amazon games, so I wasn't able to test that.
In order to test on my system, I made the `WrappersTable` display on Windows (which I'd like to submit in a separate PR after some testing), then configured a wrapper as a Python script. Main interesting part of the script:
```python
path = Path("C:/tmp/script.log")
with path.open("a") as f:
f.write(f"{sys.argv}\n")
for k, v in os.environ.items():
if k.startswith("HEROIC_"):
f.write(f"{k} = {v}\n")
```
I verified that the new …

[Improv]: Add environment variables for use by wrappers

---

src/backend/main.ts
src/backend/storeManagers/index.ts

[FIX] Make sure game is available before auto updating

---

src/frontend/screens/Game/GamePage/components/MainButton.tsx
src/frontend/screens/Game/GamePage/index.tsx

Issue introduced in gamepage refactor, we somehow missed this.  
`handlePlay` function returned another function... 

[FIX]: gamepage play button not working

---

src/backend/storeManagers/gog/games.ts

This prevents an issue when uninstalling a GOG game while at the same time deleting the game prefix.
The uninstaller and the prefix folder deleting was happening in parallel, freezing the uninstaller execution.
Now we first wait until it's done.
---

[Fix] Await for GOG uninstaller to finish

---

src/frontend/screens/Library/components/GameCard/index.css
src/frontend/screens/Library/index.css

This PR should fix these issues for good (hopefully)
We had a problem when using a controller:
And this was reported on Discord:
To reproduce the first one, just use a gamepad and it looks like that. I couldn't reproduce the second one manually but I could artificially (removing some classes). The fix I added should fix this in any case though since now the size will only be applied if the `justPlayed` class is actually present on that first element.
---

[UI] Fix wide card being extra tall

---

src/backend/main.ts

avoids main "thread" hang when downloading of widevine components fails  
Reported on discord by user `Jiibus`  
The issue can be easily reproduced by blocking `update.googleapis.com` 
sample /etc/hosts line
```
0.0.0.0 update.googleapis.com
```

[DRM]: fix update error causing hang

---

src/backend/images_cache.ts

This PR optimizes how image cache works and prevents same images to be loaded at the same time. This speeds up loading library and future game page redesign

[IMPROV]: avoid caching same images in the same time

---

src/backend/logger/logger.ts
src/backend/main.ts
src/backend/utils/os/processes/index.ts
src/backend/utils/systeminfo/gpu/linux.ts
src/backend/utils/systeminfo/memory/linux.ts
src/backend/utils/systeminfo/osInfo/linux.ts

After the release of 2.9.2, some issues with the new system information module were found (some major, some minor). This should iron those out
---

[Fix] Several System Information improvements

---

src/backend/wine/manager/downloader/main.ts
src/backend/wine/manager/downloader/utilities.ts

This PR removes the `overwrite` flag for unzipping new proton/wine-ge versions and instead backup the old folder.
This should avoid the permission error reported in #3067.
The backup folder is restored if unzipping of the new version fails or deleted if it succeed.
---

[Fix]: Permission error on updating Proton/Wine-Ge-latest

---

src/backend/logger/logger.ts

Closes #2522 
To test:
- Run regular Heroic with `heroic | head`; for every log message pushed, one exception is thrown
- Run this version with the same pipe (to avoid having to install this PR's version globally, you can build & run with `node_modules/.bin/vite build && CI=e2e node_modules/.bin/electron build/electron/main.js | head`); exceptions are no longer thrown
---

[Fix] Add an error handler to stdout/stderr

---

src/backend/downloadmanager/utils.ts

[Fix] Installation fail when sdlList has empty elements
---
- Filter sdlList in order to remove empty elements to avoid installation failures.
It fixes an install bug on Kerbal Space Program and probably other games (I haven't any game that can select some specific downloads).

[Fix] Installation fail when sdlList has empty elements

---

tsconfig.json

This fixes a misconfiguration in `tsconfig.json` which leads to Jest functions such as `describe()`, `expect()`, etc. to not be recognized in VS Code.

Fix type errors on Jest functions in VS Code

---

src/backend/launcher.ts
src/frontend/screens/Game/GamePage/components/ReportIssue.tsx

This fixes Sideloaded games logs not showing the system info and game settings.
It also re-adds the 'Report a Problem' Link on the game page to see the logs.
---

[FIX] Sideloaded Games Logs

---

src/frontend/screens/Library/components/InstallModal/index.tsx

There was a linux logo display issue when we click on add game.
I set up the code locally and test the issue. So there was an issue with displaying of linux logo. Then I wne t through the code and found that the value assigned to linux was 'linux' but it should be 'Linux' instead.
Solved the problem !!
---

[FIX] Linux Icon when sideloading games

---

src/backend/launcher.ts

URGENT:
Fixes games/launchers that require DOTNET 6.0 and higher with linux dotnet sdk installed on the host

[FIX] Unset DOTNET_ROOT for wine

---

src/backend/shortcuts/nonesteamgame/nonesteamgame.ts

This PR adds a missing `"` character at the end of the string when adding steam shortcuts on windows as explained here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3125
Thanks @HazardousBackup
Fixes #3125 
---

[Fix] Fix missing double quote on exe value

---

src/backend/main.ts

This PR removes the configuration that enabled the chrome remote debugger access.
It was adding during the stores refactor.
We don't really need it for development since we already turn on the dev tools inside heroic, and it's insecure to have that enabled in production releases since other apps can access information without the user knowing. Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3126
---

Remove remote debugger access

---

src/backend/launcher.ts

In the prepareLaunch function we have an early return if not linux and it was only returning the discord presence flag but not the offline flag, so even with the setting the launch commands were not created with this argument. It only worked on Linux since it didn't do that early return.
---

[Fix] Fix "Run Game Offline" not working on windows and mac

---

src/frontend/components/UI/Sidebar/index.scss

The submenus for Stores and Settings when the sidebar was collapsed where not positioned correctly.
The `left` was fixed to 62px with variable width of the sidebar.
There was another related issue: because of the `drag` area of the sidebar, moving the mouse from the Settings or Store buttons to the submenu was not possible for the smallest widths of the sidebar (the mouse was not `hovering` the button anymore for a moment). This PR fixes that too by making the element be on top of the drag area.
---

[UI] Fix position of submenus of collapsed sidebar

---

src/backend/logger/__tests__/logfile.test.ts
src/backend/logger/logfile.ts

This PR changes the logic to delete old log files. Instead of deleting things older than 1 month ago, we delete everything except the last 2 launches of the app.
Older logs haven't really been useful when debugging problems, there's no need to keep them.
I did include 2 more changes:
- I moved the date to the beginning of the filename, so it's easier to see the logs for the different stores from the same date
- I removed the milliseconds from the datetime, we don't need that precision and it just makes the filename harder to read
---

Delete old logs, keep only the last 2

---

package.json

We need at least Node 16 because we use the `replaceAll` function for strings.
Adding this will prevent wasting the time I wasted trying to figure out why a call to `replaceAll` was failing for me haha.
---

[DX] Require Node 16 or greater for development

---

src/backend/logger/logfile.ts

In this PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3132 I broke the log files on Windows.
This PR fixes that by using the correct separator when creating the paths.
---

[DX] Use path.join instead of / when generating a path

---

src/frontend/screens/Game/GamePage/components/InstalledInfo.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3055.
We were showing things like install path, wine, prefix for Browser app, all things that are unrelated to browser apps. Now we just show `Installed Platform: Browser`
---

[UI] Hide wine and install info for browser apps

---

src/frontend/helpers/gamepad.ts

This was turned on at some point for debugging something and it's not really useful now, it just adds noise in the dev tools console when using a gamepad.
---

Disable gamepad console log in devtools

---

src/frontend/components/UI/ActionIcons/index.tsx
src/frontend/components/UI/LibrarySearchBar/index.tsx
src/frontend/components/UI/PlatformFilter/index.tsx
src/frontend/components/UI/StoreFilter/index.tsx
src/frontend/screens/Library/LibraryContext.tsx
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Library/components/LibraryHeader/index.tsx
src/frontend/screens/Library/index.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

I started working on implementing some redesign for the library and noticed the current state management of the library is spread all over the place:
- most state is in GlobalState
- some state is in Library
- some state is in the children of the library
The state of the library doesn't need to be global, moving that out saves extra re-renderings, like re-rendering the sidebar when the search changes. Also, decoupling the different components will make it easier for me to implement some of the design changes for the filtering. It also makes the code more consistent, ActionIcons was updating the local storage of the browser to store the values of some filters but the other filters were updated by GlobalState.
Now all these:
- search text
- platform filter
- store filter
- sorting
- layout …

[Refactor] Move the library status/filters out of the GlobalContext into a LibraryContext

---

src/backend/launcher.ts
src/backend/save_sync.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/gog/library.ts
src/backend/storeManagers/gog/user.ts
src/backend/storeManagers/legendary/eos_overlay/eos_overlay.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/legendary/library.ts
src/backend/storeManagers/legendary/user.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/nile/library.ts
src/backend/storeManagers/nile/user.ts
src/backend/storeManagers/sideload/library.ts
src/backend/storeManagers/storeManagerCommon/games.ts
src/backend/utils.ts
src/backend/utils/helperBinaries/index.ts
src/backend/wine/manager/ipc_handler.ts
src/backend/wine/manager/utils.ts
src/common/types.ts

We have this pattern in a lot of places:
```
import {
createAbortController,
deleteAbortController
} from './utils/aborthandler/aborthandler'
...
...
const abortId = 'some-id'
runSomeCommand(
...
createAbortController(abortId)
{
...options
}
)
deleteAbortController(abortId)
```
This PR is a refactor of that to only need the abortId when calling the functions and the abort controllers are created/deleted internally. It removes a lot of imports and explicit calls to `createAbortController` and `deleteAbortController`.
So now we don't need the imports and we can do
```
runSomeCommand(
...
{
abortId: 'some-id',
...options
}
```
The abortId is also now optional, if we want to run something that we don't need to abort manually we can ignore that option.
We can still abort things when needed …

[Refactor] Refactor abort controllers to simplify creation/deletion

---

src/backend/main.ts

[FIX] Should not start download queue when launched in CLI mode

---

src/frontend/App.tsx
src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/frontend/screens/WebView/index.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/758
Now the last url that we navigate to in the webview is remembered and used when clicking the `stores` icon in the sidebar.
Users can still navigate to any of the stores with the sidebar submenu or the game's `Store page` links.
---

[UX] Remember last url opened in the webview, reopen there

---

src/frontend/index.scss
src/frontend/screens/Library/index.tsx

After merging the update to Electron 27, some problems were found, this PR fixes those:
- showing the material ui context menues broke the scroll and positions:
(the sidebar is missing in that picture)
- when a vertical scroll appeared, a horizontal scroll appeared too:
- when the header height changes during a resize of the window, the library header was not properly sticky-positioned
---

[UI] Electron 27 fixes

---

src/frontend/App.css
src/frontend/screens/Library/components/GamesList/index.tsx
src/frontend/screens/Library/index.tsx

After using the latest main with Electron 27 I noticed the library felt slow and it was because the lazy loading of the elements below the fold broke with all the changes related to which element is the scroll element.
This PR fixes that to render it fast again.
I also removed a leftover console.log.
I'll keep testing to see if I find any other issue.
---

Electron 27: more fixes (gallery lazy load)

---

public/locales/en/gamepage.json
src/backend/launcher.ts
src/backend/storeManagers/legendary/library.ts
src/frontend/components/UI/UninstallModal/index.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

This PR is a replacement of https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2806 and https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3137
It includes the update of Legendary and the change to use the `LEGENDARY_CONFIG_PATH` env variable and also adds the dialog that disallows users from uninstalling an Epic game while an Epic game is being installed since that's not possible with the latest Legendary.
cc @Etaash-mathamsetty and @CommandMC 
---

Update Legendary. Replace XDG_CONFIG_HOME variable. Disallow uninstalling epic game if installing one

---

src/frontend/App.css

This PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3170 includes a change removing some CSS properties. That broke the game page when there's not a lot of content in big screens (I was testing on a small screen only).
This is how it looks when I zoom out in the current main branch:
The content is not expanding.
This PR fixes that.
---

[FIX] Electron 27: Make sure the app uses 100% of the screen for short content

---

src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3156
Currently, if you pause a download and move out of the Downloads section, the button to resume the download is missing. The only ways to get it working are either restart heroic or start new downloads.
---

[Fix] missing resume download button when returning to downloads

---

src/frontend/screens/Settings/components/ExperimentalFeatures.tsx
src/frontend/screens/Settings/sections/AdvancedSettings/index.tsx

This PR fixes a problem I noticed in some components in the Advanced screen that include the state variable as a dependency for useEffects that update that state. This can lead to infinite loops and it's not correct to do it.
This can be seen when running a clean install of Heroic and going to Settings > Advanced, there's an infinite loop in the dev tools console.
This is solved once the experimental features are modified, but we shouldn't have this loop to begin with.
The useEffect that updates the Copy to clipboard status is safe because it returns early if false so it doesn't call a state setter.
---

[Fix] Prevent useEffect infinite loops

---

.github/workflows/release_aur.yml

Github Workflow to update AUR after a new release.
---

[CI] Automate AUR Publishing

---

public/locales/en/translation.json
src/frontend/screens/Settings/components/LauncherArgs.tsx

It's really common for users trying to make a game work to read instructions for Steam and try to apply them in Heroic.
It happened many times that users would set environment variables and the `%command%` placeholder in the `Game Arguments` of Heroic and that usually creates more problems.
This PR adds some error messages when we detect env variables or the `%command%` placeholder so users can see it's incorrect.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/2c1ddb3c-aa02-40fc-8797-555dc45775d4
---

[UX] Warn about the use of %command% and env variables in game arguments

---

src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.tsx
src/frontend/screens/DownloadManager/index.tsx

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2485
* Changed cancelled items Icon to StopIcon
* Added functionality to remove individual item from completed list
* Cancelled item main action button now removes individual item from "finished" list instead of linking to game page
**Current Behavior:**
When a downloading item is cancelled, it is put into the "Completed" List.
A Download icon is then displayed with the item.
The icon's tooltip says "Remove from downloads"
When clicked, item is NOT removed from Downloads and user is taken to the software's profile page.
**Fixed Behavior**
When a downloading item is cancelled, it is put into the "Completed" List.
An "X"  icon is then displayed with the item.
The icon's tooltip says "Remove from downloads"
The item is …

[FIX] handle clear download item

---

public/locales/en/gamepage.json
src/backend/main.ts
src/backend/preload.ts
src/backend/storeManagers/sideload/library.ts
src/backend/storeManagers/storeManagerCommon/games.ts
src/common/types.ts
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx

Implements #2757 
Also added a Full-Screen option
Fullscreen setting:
Custom UA used for youtube tv: Mozilla/5.0 (PS4; Leanback Shell) Gecko/20100101 Firefox/65.0 LeanbackShell/01.00.01.75 Sony PS4/ (PS4, , no, CH)
---

[FEAT] Support Custom User Agent for browser apps

---

src/backend/storeManagers/legendary/setup.ts

Otherwise, newer Wine versions will prompt to overwrite it and loop there forever.
---

[FIX] Wine Stuck sometimes at adding registry key

---

src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/frontend/screens/WebView/index.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3200
We now store the last url visited when navigating the stores, but we can store external urls and then there's no way to go back to the store.
With this PR we now only store urls that are allowed instead of storing everything. And in case a user already has an invalid url stored, we now also check to only re-open in the url if it's one of the allowed.
---

[Fix] Prevent storing external urls for stores

---

src/frontend/components/UI/Sidebar/index.scss
src/frontend/index.scss
src/frontend/screens/Game/GamePage/index.scss
src/frontend/screens/Library/components/InstallModal/index.scss
src/frontend/screens/Settings/sections/LogSettings/index.css
src/frontend/state/GlobalState.tsx

This PR fixes most of the comments from this report https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3204
I'll add comments in the diff itself
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3204
---

[UI/UX] Fix some visual issues related to logs, dialogs, and RTL layout

---

src/backend/utils.ts

This fixes #3202 
But it also get back to using `tar` on Linux except for Snaps. so if you do not have a mac to test, just test the behavior on linux, it is the same.
---

[FIX-macOS] Wine Downloader fails to extract files 

---

.github/workflows/build-base.yml

Of course, the *one thing* I can't test locally breaks
The workflow tried to access `snapcraftEdgeId`, but the secret in question is named `snapcraftIdEdge`
---

[Fix/Tech] Fixup Snap publishing in `build-base` workflow

---

.eslintignore
index.html
package.json
src/backend/storeManagers/index.ts
src/backend/storeManagers/legendary/eos_overlay/eos_overlay.ts
src/backend/utils.ts
src/frontend/components/UI/Dialog/index.css
src/frontend/components/UI/SelectField/index.css
src/frontend/helpers/index.ts
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Library/components/GameCard/index.css
src/frontend/screens/Settings/components/BattlEyeRuntime.tsx
src/frontend/styles/_typography.scss
yarn.lock

This is an alternative PR to #2748
I didn't like the fact that we had to explicitly add the folder when invoking Prettier in the first place. It's already in our `.prettierignore`, so it should be... ignored. Newer versions of Prettier do this correctly, so this was solved by a simple update (and subsequently fixing all the new formatting rules)
In the process, I noticed that ESLint also had problems with this folder. Adding it to `.eslintignore` was all *it* needed
---

[Tech] Truly ignore `flatpak-build`

---

.github/workflows/build-base.yml

Electron-Builder tries to be smart and auto-enables publishing if if's on the main branch of a repo (at least it seems that way, it doesn't do this in the PR workflow; can't find anything about this in the docs), which then promptly fails.
Explicitly turn it off
I can't test this locally, let's hope 3rd time's the charm
---

[Fix] Workflows: Disable publishing when building the AppImage

---

src/frontend/screens/Library/components/InstallModal/index.scss
src/frontend/screens/Settings/components/SettingsModal/index.scss

After one of my last PRs, the install dialog is too tall even when not enough content. This PR fixes that by making the install modal use the height on its content while also letting the settings be bigger to use more height in small screens.
Before:
After:
---

[UI] Fix height of install and settings dialogs

---

src/frontend/screens/DownloadManager/components/ProgressHeader/index.css
src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx

Smoothed out the download status bar and fixed the width of the real time download status
---

[UI] Improve download speed chart

---

src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Game/GamePicture/index.css
src/frontend/screens/Game/GamePicture/index.tsx

Fix Issue #2466 GamePage image is missing logo when available
Add logo support in GamePage and GamePicture.
In GamePage component, add logo variable and pass it to GamePicture component. In GamePicture component, add logo parameter; add logo element (same as the CachedImage logo element in GameCard)
There was no need to add CSS, since there was  already CSS for logo in GamePicture  that positions it at the bottom center.
---

Fix Issue #2466 GamePage image is missing logo when available

---

src/frontend/App.css

After the changes needed from the Electron upgrade, the blurred background image in the game page got lost. This PR fixes that by only setting the background color IF there's no backgroundImage element in it.
Before:
After:
---

[UI] Fix regression of missing background image in game page

---

src/backend/launcher.ts

Just a quick fix to bug #3026. Without this fix, WINEPREFIX isn't set in the environment variables in the launch options, and therefore GPTK uses the user's default wine prefix (in my case ~/.wine). I doubt this fix is crazy perfect, but it's simple and it works!
Tested using Heroic latest on macOS 14.0 with Satisfactory Early Access. (The game is now using the right prefix's save files!)
----

[Fix] WINEPREFIX ignored when using GPTK

---

src/backend/api/misc.ts
src/backend/main.ts
src/backend/main_window.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/screens/Loading/index.tsx

window now has a background which should prevent flashing of white,   
window is shown after its contents are loaded - removed our custom loadingScreenReady event
additionally I replaced deprecated `protocol.registerStringProtocol` in favor of `protocol.handle`

[improv]: electron side changes to window behavior

---

package.json
yarn.lock

The version of `steam-shortcut-editor` we were using required an old version of lodash. In terms of functionality, nothing changed between 3.1.1 and 3.1.3, so we can just update it.
The last alert is about `axios`, which we can't easily update right now (we'd need #3218 for that).
---

[Fix] Resolve 7/8 dependabot alerts

---

src/backend/tools/index.ts

DXVK-NVAPI wasn't installable due to the archive extraction directory not being created. While solving this, I've made some changes to hopefully make the whole install/update function more readable
---

[Fix] DXVK-NVAPI installation

---

src/backend/launcher.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3341
Instead of failing with an error, ignore the `gamescope` setup if enabled but not found.
This can happen if gamescope was configured for a game and then uninstalled.
With this change it will just show a warning in the logs and still run the game as if the setting was disabled.
---

[Fix] Ignore gamescope if enabled and not found instead of failing

---

src/backend/shortcuts/nonesteamgame/nonesteamgame.ts

This change should make checkIfAlreadyAdded insensitive to the case of 'AppName' so if it changes it'll still be recognized and able to be removed and not double added.
Fixes #3124 
Change is based on [this StackOverflow post](https://stackoverflow.com/a/47538066)
Tested but not on a completely clean install
---

[Fix] Steam Shortcuts / Make checkIfAlreadyAdded case-insensitive

---

public/locales/en/translation.json
src/frontend/screens/Settings/sections/LogSettings/index.tsx

Added a "Join our Discord" button in the "Report a problem running this game" window. 
Fixes #3296
---

[UI] Add link to join Discord server in the "Report a problem..." dialog

---

public/locales/en/translation.json
src/frontend/components/UI/LibraryFilters/index.tsx
src/frontend/screens/Library/LibraryContext.tsx
src/frontend/screens/Library/index.tsx
src/frontend/types.ts

This PR adds a new filter to list only games flagged as supporting offline mode.
This can be really handy when deciding what to install for the steam deck for example knowing it would work on the go with no internet.
(I understand that some games are mislabeled, but we can't do anything about that)
---

[UX] Add offline support filter

---

public/locales/en/gamepage.json
src/frontend/components/UI/UninstallModal/index.tsx

When uninstalling a native game, there's no mention of the game that is going to be uninstalled:
This can be problematic, because if a user clicks the wrong card to uninstall a game, they can end up uninstalling the wrong one.
Also the copy is confusing `Do you want to uninstall this game?` but it doesn't say which
This PR adds the title of the game in the message, so it's more clear:
---

[UX] Show game title in uninstall dialog

---

src/frontend/components/UI/Dialog/components/Dialog.tsx
src/frontend/helpers/gamepad.ts
src/frontend/screens/Library/components/GamesList/index.tsx

This PR improves the UX of heroic with a controller with a few tweaks:
- Pressing the `B` button (in the steam deck layout, I think it's `O` if using a PS controller) now closes any dialog, not only the install dialog, and it doesn't go back in history if a dialog is open
This was really annoying, now we can press `B` to close the Settings dialog, Categories dialog, or the Uninstall dialog for example
- After closing a dialog, the element that was focused before opening it gains focus again
this was REALLY annoying, it feels way better now, for example when opening the settings or logs for a card, after closing the dialog we are still focused on the same card instead of nowhere
- When moving the focus in the library, now cards are scrolled into view so they are completely visible
this …

[UX] Improvements when using a controller to navigate the interface

---

src/backend/logger/logfile.ts
src/backend/logger/logger.ts
src/backend/main.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/gog/setup.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/nile/setup.ts
src/backend/storeManagers/storeManagerCommon/games.ts
src/backend/utils.ts

We currently use explicit calls to `writeFileSync` and `appendFileSync` when we want to write game logs. This PR extracts that into more descriptive logger helper methods (`initGameLog` and `appendGameLog`) to simplify the usage so we can abstract the actual file name calculation and writing of the content.
I'm doing this because I want to add more logging and make it all async in the future, so I want to first simplify the API.
Nothing is changed in the functionality, logs should work just the same as before.
---

[Tech] Refactor how we write to game logs

---

flatpak/templates/com.heroicgameslauncher.hgl.yml.template

Based on this issue: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1829
And using configuration taken from Lutris: https://github.com/flathub/net.lutris.Lutris/blob/beta/net.lutris.Lutris.yml
I couldn't fine how to install libpng though
I can confirm that Dead Cells native works with the flatpak from this PR
EDIT: PR in flathub's repo https://github.com/flathub/com.heroicgameslauncher.hgl/pull/124
---

[Flatpak] Add some libs missing for native games

---

src/backend/storeManagers/gog/library.ts
src/common/types/gog.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3272
This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3310
I saw linguin's comment in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3272#issuecomment-1850785650 and I wanted to extract that into a smaller PR to fix these 2 issues. When I did that I noticed there's was one issue with no fallback for `art_square` if undefined so I had to do some changes on top of that code.
---

[Fix] Handle possible undefined GOG images

---

src/frontend/screens/WineManager/components/WineItem/index.tsx

This PR fixes 2 problems related to the download progress of wines:
- After canceling the installation of a wine, the progress was stuck as `downloading` instead of reverting back to idle state. Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3328
- The width of the progress was not constant so it kept jumping around as wider/narrower digits changed. Now I added a new line and it's centered so it doesn't move that much:
---

[Fix/UI] Fix status after aborting wine installation. Make width of progress more stable

---

src/backend/api/helpers.ts
src/backend/main.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/legendary/library.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/nile/library.ts
src/backend/storeManagers/sideload/games.ts
src/backend/storeManagers/sideload/library.ts
src/common/typedefs/ipcBridge.d.ts
src/common/types.ts
src/common/types/game_manager.ts
src/common/types/legendary.ts
src/frontend/helpers/index.ts
src/frontend/helpers/library.ts
src/frontend/screens/Game/GamePage/components/LaunchOptions.tsx
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
src/frontend/types.ts

This PR adds support for launch-able DLCs (for Epic/Legendary), used for the recent Fortnite "Experiences" and the Unreal Editor for Fortnite
I can't test this *that* well, as I don't have a Windows system with Fortnite installed, but it appears to be working. Further tests from people on our Discord might be coming soon
---

[Feat] Support Epic's launch-able addons/DLCs

---

src/frontend/components/UI/Winetricks/WinetricksSearch/index.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3379
Using `includes` does a substring check while `match` does a regexp check which creates an error.
---

[Fix] Use 'includes' instead of 'match' to filter winetricks

---

src/backend/storeManagers/gog/setup.ts
src/backend/storeManagers/nile/setup.ts
src/backend/tools/ipc_handler.ts

This fixes 2 issues:
- we were showing the `Installing Prerequisites` for GOG games but we don't really do that yet
- we were setting the `Installing Prerequisites` status when running an exe on the prefix but never resetting that state
I also moved the `Installing Prerequisites` status for the Amazon setup to be displayed after the prefix is verified instead of before, to happen right before the post install step.
---

Fixes related to "Installing Prerequisites" status

---

src/backend/downloadmanager/utils.ts
src/backend/launcher.ts
src/backend/main.ts
src/backend/wiki_game_info/gamesdb/utils.ts
src/common/utils.ts

In https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3335 we are adding the feature to install known winetricks fixes. That downloads the `fixes` file from the https://github.com/Heroic-Games-Launcher/known-fixes repo during the installation of a game.
The problem is that we have no way or removing the file once the winetricks fix is not needed anymore, so if a game is downloaded today and a fix is not needed anymore in 2 months, if I install the game it will still run the winetricks commands.
This PR changes that so when a game is uninstalled, if a fixes file exists it gets deleted. That way, if we install the game in a few months and the fix is not needed, it won't be in the `known-fixes` repo and we don't download anything.
I did a small refactor cause I needed that map …

Remove fixes file when a game is uninstalled

---

src/backend/tray_icon/tray_icon.ts

We were using the `double-click` event but that only works on Mac and Windows, not on Linux https://www.electronjs.org/docs/latest/api/tray#event-double-click-macos-windows
This PR changes the code to use `click` instead which works on all platforms.
Other electron apps like discord or slack work like this too.
---

[UX/Linux] Open main window when clicking the Tray icon

---

src/backend/launcher.ts
src/common/types.ts

There can be scenarios where the experimental features setting is undefined (when upgrading Heroic from versions that didn't have this setting for example), an can cause this error:
```
(01:07:10) ERROR:   [Backend]:          TypeError: Cannot read properties of undefined (reading 'automaticWinetricksFixes')
at prepareWineLaunch (/home/mathis/Heroic/Source2/build/electron/main.68379776.js:7616:62)
at async Module.launch$1 [as launch] (/home/mathis/Heroic/Source2/build/electron/main.68379776.js:5069:9)
at async /home/mathis/Heroic/Source2/build/electron/main.68379776.js:35138:26
at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:88992)
```
This PR prevents that.
---

[Fix] Prevent error if experimental features setting is undefined

---

src/frontend/components/UI/Dialog/index.css

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2609 by making all dialog headers static.
Also, now that we are not closing the dialogs when clicking outside (until we figure a solution for this https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3194) it was sometimes annoying to have to scroll up to close a dialog.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/188464/a3f0cbd2-7f97-401d-b4ab-507c185f403a
This also fixes this issue with changelogs not having a height limit:
---

[UX] Fix position of dialog header

---

public/locales/en/translation.json
src/backend/launcher.ts
src/frontend/screens/Settings/components/OfflineMode.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3383
Some games seem to not have the `CanRunOffline` metadata but still work fine in offline mode. This PR allows users to toggle that on so they can still try to run the game.
When the option is turned on and the game does not allow offline mode, this warning is displayed:
This will also solve a problem that users sometimes can't find the option and they ask over Discord. Now the option will be always there. In some cases it may not work but we have the warning to let users know it's not heroic's fault but the game not supporting offline mode.
---

[UX] Allow setting offline mode even if game does not have the metadata

---

src/backend/logger/logger.ts
src/backend/main.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/gog/setup.ts
src/backend/storeManagers/legendary/eos_overlay/eos_overlay.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/nile/setup.ts
src/backend/storeManagers/storeManagerCommon/games.ts
src/backend/utils.ts
src/backend/utils/systeminfo/index.ts
src/backend/utils/systeminfo/steamDeck.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3187, and fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3186 and fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3104
This PR adds more information in the logs to make them more useful when users share them over Discord.
New info:
- Name of the game/app
- Runner
- If it's native or not
- Install dir
- If the game is running in Desktop or Game mode (only on a Steamdeck)
- If the EOS overlay is enabled or not (for epic games only)
- If there are winetricks packages installed (for non-native games)
- Also added a `===== End of game logs =====` line at the end so we know users didn't cut log when sharing
I also included a few extra changes that I needed:
- I …

[Logs] Add more info in game logs

---

public/locales/en/translation.json
src/common/types/electron_store.ts
src/frontend/components/UI/Dialog/components/Dialog.tsx
src/frontend/components/UI/Dialog/index.css
src/frontend/screens/Accessibility/index.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

This PR adds an Accessibility option to let users decide if they want the dialogs to be closed or not when clicking outside.
Clicking outside of dialogs currently (not in main but in the stable release) closes dialogs without any confirmation by the user. This is problematic because clicking outside by mistake can mean information is lost.
Current main branch disables the click outside to close the dialog, but some users might want that to work (it's a common thing to do).
This PR gives the users the option to pick which behavior they want.
One thing I noticed is that disabling the click outside also disables closing dialogs with the `Esc` key, so I added a handled for that too.
---

[UX] Add Accessibility option to disable closing dialogs when clicking outside

---

src/backend/logger/logger.ts

In a previous PR I added a line to log if the EOS overlay is enabled or not: this https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3394/files#diff-3b36a7de185377bbb618ac5e7bc20b0780c6ea78b5d5ac53c7b9a7469448a988R429-R437
This works fine when the prefix is already created but produces an error when the prefix is not ready yet. We have to log this information after making sure the prefix is initialized.
I'll revert this change for now since this other PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3356 will enable the EOS overlay by default anyway
We can include this in the log in the future (I just don't want this to be a blocker or a problem for a release).
---

Revert logging if the EOS overlay is enabled

---

src/backend/logger/logger.ts

Similar to https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3404
With the new information in the logs, one of the lines was the list of winetricks packages installed. The problem is that, when the prefix is not yet created, this call to get the winetricks packages initializes the prefix at the wrong point of the process and all the setup code is skipped.
I'll revert this for now, in the future I'll make change some of this to add the logs only after the prefix is ready.
---

Revert printing winetricks packages in logs

---

src/backend/storeManagers/legendary/commands/base.ts
src/backend/storeManagers/legendary/commands/eos_overlay.ts
src/backend/storeManagers/legendary/eos_overlay/eos_overlay.ts

Previously, trying to enable/disable/check the status of the EOS overlay for a game with an invalid prefix directory would lead to an error message.
We're now handling this correctly (not enabling/disabling it, always reporting that it's disabled)
Technically, this works by adding:
- a new type, `ValidWinePrefix`. It's an extension of the `Path` type, meaning it already makes sure the string inside it is a valid path, and it now also verifies that there's a `user.reg` file inside the directory it's pointing to
- a new function inside the EOS handler, `getWinePrefixFolder`. It deduplicates some of the logic used in the `enable`/`disable`/`isEnabled`, and now also makes sure the configured prefix path is contains a valid prefix
Error message before:
No error message now:
---
Use the …

Only try to do EOS operations on a path if there's actually a Wineprefix there

---

src/frontend/screens/Library/index.css

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3403
The content was not using the space correctly when the UpdateComponent was displayed while a top section was visible.
---

[UI] Fix extra scroll when UpdateComponent is displayed in the library

---

src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.scss

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3423
Before:
After:
---

[UI] Fix width of image in Add Game dialog

---

src/backend/utils/systeminfo/steamDeck.ts

This should fix the https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3433
I've added the new APU name to the first check. If neither is true, isDeck is set to false.

Added the second AMD APU code value to Steam Deck detection

---

src/frontend/screens/Settings/components/DisableLogs.tsx

When I implemented the option to disable logs, I copied the component used to disable the controller to have the boilerplate and I didn't remove a part of the code.
Because of that, when disabling/enabling logs, that was also enabling/disabling the controller flag.
---

[Fix] Don't disable controller when disabling logs

---

src/backend/storeManagers/legendary/library.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3450
We were not waiting for the promise to finish, so the library was not updated with the new results from legendary, we were writing the old library to the store instead, requiring a second reload to get things updated.
---

[Fix] Wait for legendary refresh to finish before storing array

---

src/backend/launcher.ts
src/frontend/screens/Settings/components/ExperimentalFeatures.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx

Currently, users have to know this experimental feature exists to enable it, but new users will most likely miss this (or skip it because it's experimental).
This PR changes the feature to be on by default instead and users then have to opt out if they want to not autoinstall fixes.
We haven't seen reports of this causing issues so far (but I don't know if it's because not many users are using this). I think it's a good default for a future release before promoting it from experimental.
---

[UX] Set the auto fixes feature ON by default

---

src/frontend/screens/Library/components/ContextMenu/index.css

after (subtle difference):
this has been triggering my OCD for like 6 months now, pls merge lol

[UI/FIX] Fix context menu font

---

src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/wiki_game_info/wiki_game_info.ts
src/common/types.ts
src/frontend/screens/Game/GamePage/components/ReleaseDate.tsx
src/frontend/screens/Game/GamePage/index.tsx

Now we'll use release dates obtained from each runners API. We were already making a requests to obtain a store URL for example, so I just re-used that.
I skipped that for Amazon for now...  
We have each game's release for each entry in nile's `library.json`, we'd probably need to include that data in GameInfo object.

[UX] Prefer using release dates from each runner

---

src/frontend/themes.scss

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2768. And fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3430
2768 was partially fixed before but it was not fixing error dialogs (only winetricks progress dialogs)
Before:
After:
---

[UI] Nord Light theme fixes

---

e2e/api.spec.ts
src/backend/api/helpers.ts
src/backend/config.ts
src/backend/constants.ts
src/backend/downloadmanager/utils.ts
src/backend/logger/logger.ts
src/backend/main.ts
src/backend/main_window.ts
src/backend/preload.ts
src/backend/storeManagers/gog/library.ts
src/backend/storeManagers/gog/user.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/helpers/index.ts
src/frontend/screens/Library/index.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

This PR does 3 cleanup/refactor tasks:
- remove some code that is not really needed anymore (I'll add comments in the diff)
- use `isWindows/Linux/Mac` constants when possible instead of `process.platform` or `platform()`
- expose the platform name in the preload file so we don't need the extra IPC calls to get that info
---

Cleanup `platform` checks. Remove old code.

---

src/backend/downloadmanager/utils.ts

This PR changes the URL used to download known fixes to use a folder for the store instead of downloading them from the root of the repo.
I already updated the repo to support downloading the files from folders https://github.com/Heroic-Games-Launcher/known-fixes
The repo will support both the root dir and the folder temporarily so it works with 2.12.0 and the next versions, and eventually we can remove the duplication of that repo once Heroic 2.12.0 is not more.
---

[Refactor] Download known fixes from store folder

---

src/backend/logger/logger.ts

There is a small an inoffensive bug with gog games and logs, but it can cause confusion during support requests:
the gogdl command prints the launch command to the output a moment after the process ends, when a game launch is aborted, this happens AFTER Heroic calls the `stopLogger` method. This causes a new logger to be initialized with that last message in the queue, and it's used in the next run, printing a message from a previous run before the actual run's logs.
This PR fixes that by only initializing the logger when calling `initGameLog` and not on appends.
This is how this can be tested in the current release:
- start a GOG game
- abort the launch as soon as possible
- launch the game again
- now let it start and close the game correctly
- open the game logs
Notice that there are 2 …

[Fix] Prevent last run output to leak to next run's logs

---

public/locales/en/translation.json
src/backend/launcher.ts
src/common/types.ts
src/frontend/screens/Settings/components/ExperimentalFeatures.tsx

This PR extends the feature that applies automatic winetricks fixes by supporting also automatic `run exe in prefix` actions.
Sometimes, some games include files that has to be executed that are not listed as prerequisites. The most common case is FallGuys that requires the installation of the EpicOnlineServices to solve the `Missing Files` error.
This can be used for any game that needs a similar tweak by adding content in the https://github.com/Heroic-Games-Launcher/known-fixes repo.
You can use Fall Guys to test this feature.
---

[UX] Add support for autoinstallation of files from game folder

---

src/frontend/components/UI/WebviewControls/index.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3399
Now we can go back to whatever opened the webview, we can go back to the game page after clicking `Store page` in the game page.
---

[UX] Allow going back to a previous screen when no more webview history

---

src/backend/launcher.ts

Not quite sure how this happened, but #3448 had some conflicts with types on the `main` branch
Joinked the change from https://discord.com/channels/812703221789097985/812703424995000361/1201963518233161788
---

[Fix] Game Status type

---

src/backend/utils/inet/downloader/index.ts
src/backend/utils/systeminfo/gpu/pci_ids.ts

We were looking at the birthtime of the file, which doesn't actually get updated when re-downloading (as such, nothing was ever cached).
A *very quick* local test suggests that this is working, but I don't have the time to properly test this on multiple systems/OSs right now.
In case this does work as-is everywhere, I've also created the [pci_ids_stable_branch](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/tree/pci_ids_stable_branch) branch from our latest release and the two commits, ideally we'd release this ASAP as a 2.12.1.
---

[Fix] Caching in `downloadFile`

---

src/backend/utils.ts

When Heroic is opened for the first time, if no wine is found it auto installs the latest available Wine-GE.
This was not filtering out the `LoL` builds.
You can test this behavior if you have other wines installed by going to main.ts and commenting out the `if` at:
```ts
setTimeout(async () => {
// Will download Wine if none was found
const availableWine = await GlobalConfig.get().getAlternativeWine()
DXVK.getLatest()
Winetricks.download()
if (!availableWine.length) {
downloadDefaultWine()
}
}, 2500)
```
like:
```ts
setTimeout(async () => {
// Will download Wine if none was found
DXVK.getLatest()
Winetricks.download()
downloadDefaultWine()
}, 2500)
```
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3511
---
Use the following Checklist if you have changed …

[Fix] Filter out -LoL build when installing wine at boot

---

src/backend/downloadmanager/downloadqueue.ts
src/backend/main.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/gog/library.ts
src/backend/storeManagers/legendary/library.ts
src/backend/storeManagers/sideload/library.ts
src/common/types/game_manager.ts

When getting the install info for legendary games, it sometimes happens that we have invalid data cached that doesn't have `manifest` info.
In the past that lead to the InstallDialog to be stuck fetching the install info forever, with the latest changes for the gogdl_refactor that produces a javascript exception killing the react app: `Error: Cannot use 'in' operator to search for 'perLangSize' in null]`
This PR addresses that with 3 changes:
- if the cached information for legendary does NOT have a `manifest` property, it doesn't use the cache and fetches a new one
- if the result of fetching the info does not have a `manifest` property, it's retried up to 3 times
- if the result of fetching the info does not have a `manifest` property after the retries, it throws an error instead of …

[Fix] Ensure manifest in install info

---

src/backend/launcher.ts

After merging the changes to make logging async I found a bug with the code that gets the `appName` from the command parts. This was not a big problem before because it was used for the the abortId and some error handling, but with the new async logs the appName is used to find the log path and it was breaking.
The original code had 3 problems:
- if the command was not `launch`, it was still always adding 1 and picking a random value for the appName
- it was only handling `launch` but not other commands like `update`, `repair`, `verify` (for nile) or `download` (for gogdl)
- the appName is only the part after `'launch'` for legendary, for gogdl and nile the position in the array is different
This PR addresses:
- if the command is not one with an appName, we ignore it
- it handles …

[Fix] Fix calculation of appName from command parts

---

src/frontend/state/GlobalState.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3359
This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3116
We have a bug in the logic that decides if the initial refresh is done in the background or not: it's only considering if we have epic games to show.
When users are NOT logged into epic, every time they open heroic the refresh is done in the foreground, taking way longer than it needs to to show the games.
This PR fixes that by considering the libraries of the 3 stores instead.
---

[UX] Initial refresh in the background if any library is ready

---

src/frontend/state/GlobalState.tsx

After installing a GOG game, the library is not updated with the new status.
We need to trigger a library refresh.
How to test:
- start installing a game
- stay in the library section until it ends
- the library is not updated
- change to different screens and go back, library still not updated
- click the refresh button, not library is updated
With this change:
- start installing a game
- stay in the library section until it ends
- a refresh is triggered in the background and the library is updated
---

[FIX] Reload library after GOG game install

---

src/backend/tools/index.ts

Before, we'd re-download Winetricks on every Heroic startup. This isn't a good idea for many reasons
`utils/inet`'s `downloadFile` function already has the option to cache if the file it's pointing to is younger than X seconds, so we can just use it.
Ideally we'd consolidate the two `downloadFile`s into one, but they have a very different featureset & function, so that'd be a larger refactor
---

[Fix] Only download Winetricks every 7 days

---

src/backend/launcher.ts

PowerShell's `Start-Process` cmdlet & its `-Wait` parameter are used to wait for a process tree to exit. This means we can now accurately track the "Playing" status of games on Windows.
TODO:
Adding a check like `if (runnerPath === 'powershell')` should  *work*, although I don't exactly like this solution
Closes #2046 
---

callRunner: Use PowerShell to run commands on Windows

---

src/backend/api/misc.ts
src/backend/main.ts
src/backend/utils.ts
src/backend/utils/systeminfo/gpu/pci_ids.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/components/UI/Sidebar/components/HeroicVersion/index.tsx

As discussed in #3483
To test this:
- Open the current Heroic release and navigate to the System Information tab. Note down the name of your GPU.
- Open this version, navigate to the same tab. The same name as before should be displayed.
I've tested this on both real and virtual machines, and on both Windows and Linux. macOS does not need testing, as detecting GPUs in the first place isn't done there.
Internally, we now keep two `CacheStore`s for (1) vendor names and (2) device names. The vendor name cache is simply indexed by their ID, device names are indexed with either `<DeviceSubID>_<VendorSubId>_<DeviceId>_<VendorId>`, if there are sub-IDs, or just `<DeviceId>_<VendorId>` if there aren't. This key format is handy, since replacing the `_` with `.` nets us the DNS query prefix.
Both …

[Ref] Use DNS text queries to resolve PCI IDs

---

src/frontend/screens/Library/index.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2001
We have code to sort games by: installed > installing > not installed, but when an installation starts it's currently not being sorted unless a re-render is triggered.
This PR fixes that.
To test this you can start installing a game and the card doesn't move to the top, then change to another screen, go back to the library and it's now sorted.
---

[UX] Update order in library when an install starts

---

src/backend/launcher.ts
src/backend/storeManagers/legendary/setup.ts
src/backend/storeManagers/nile/setup.ts
src/backend/tools/index.ts

We were using `waitforexitandrun` for setup commands, which is slow as it first ensures that wineserver exited properly.
`run` is made for exactly the purpose of setup. With that we can re-use wineserver process and in turn make it faster. 
I also made changes to legendary's setup, as it was using function that could recursively call itself in some conditions. This change is here to prevent that from happening in the future when we make changes to when game setup commands are executed.
Proton-GE relies on the verb to determine if it should apply protonfixes, which will be useful for us with introduction of ULWGL.
There is one command I'm not yet sure about - `shutdownWine` function. I'll take care of it in ULWGL PR though
Use the following Checklist if you have changed something on the …

[PROTON]: use run verb for setup commands

---

src/frontend/screens/Library/components/InstallModal/DownloadDialog/BranchSelector.tsx

Since we are loading password from backend asynchronously we need to add useEffect that will react to those changes. It's a small but annoying bug

[FIX]: set initial state properly for password modal

---

src/backend/main.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3524
We were always calling `autoUpdater.checkForUpdates` even if the setting was turned off.
---

[Fix/UX] Check config before calling autoupdater

---

src/backend/storeManagers/legendary/games.ts

If we're updating/repairing a game with SDL that was either synced from EGS or imported (or is missing SDL tags for some other reason), the command will get stuck waiting for the user to choose these tags.
Passing `--skip-sdl` resolves this issue. It'll always set the "default" tags, which might not be the user's choice, but it's better than getting stuck like this.
Testing this yourself is probably not that easy. Could of course download a game with SDL, delete the tags from Legendary's config, and then try a repair in Heroic, but that's rather involved.
I've done precisely this, and this change indeed resolves the issue.
---

[Fix] Pass `--skip-sdl` when updating/repairing Epic games

---

src/frontend/components/UI/Dialog/index.css
src/frontend/screens/Settings/sections/SystemInfo/cpu.tsx

1. Added Padding to the pop up window so it looks more consistent.
Before the change:
After the change
2. Added "spacing={1}" to cpu.tsx for consistency in logo sizes. Tested on Apple logo. Same argument can be found in gpu.tsx. The lack of this command in cpu.tsx made the logo appear just slightly bigger
Before the change:
After the change
---
- [yes ] Tested the feature and it's working on a current and clean install.
- [yes ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [yes ] Created / Updated Tests (If necessary)
- [yes ] Created / Updated documentation (If necessary)

Small Formatting Changes

---

src/backend/storeManagers/gog/library.ts

Turns out sometimes there can be a space at the end....

[GOG] trim titles for games

---

public/locales/en/translation.json
src/frontend/screens/Library/LibraryContext.tsx
src/frontend/screens/Library/components/AddGameButton/index.tsx
src/frontend/screens/Library/components/EmptyLibrary/index.css
src/frontend/screens/Library/components/EmptyLibrary/index.tsx
src/frontend/screens/Library/components/LibraryHeader/index.tsx
src/frontend/screens/Library/index.tsx
src/frontend/types.ts

This PR adds 2 messages when we have no games to show:
- If the user has no games at all in the library, we show a message so they can either log in or sideload games
- If the user has at least one game in the library but nothing is displayed, we show a message to let the user know the filters are filtering all games
I'm using this `Trans` element that supports rendering components and HTML inside it, so the `log in` and `add game` elements are interactive in the message. At the same time it provides safety against translations including unwanted HTML since it can only show the HTML we allow (check the translation strings have `<1>` and `<3>`, i18next handle that internally, so translators have to use them for elements to render. Then i18next replaces those tags with the ones from the …

[UX] Add messages when there are no games to display in the library

---

src/frontend/components/UI/Dialog/index.css
src/frontend/components/UI/ExternalLinkDialog/index.tsx
src/frontend/screens/Library/components/InstallModal/index.tsx

There was a regression with this change https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/commit/bda0871bb1e2d324091154549f2842be864cfe14#diff-d9b11fef9fc96a7cf2707aa13652ab1309131d88dcdba70f00cd97fcccc25830R16 causing all dialogs to have extra top padding.
Causing this visual glitch:
This PR fixes that by applying the padding only to the external link warning dialog.
I also changed the hardcoded `20px` to the css property that's used at the bottom so it's more theme-friendly.
(we should re-write this component in the future, it's using margin properties as padding)
---

[FIX] Apply top padding only to external link warning dialog

---

src/frontend/components/UI/Dialog/index.css

This PR fixes a small visual issue in the dialog: when the content is scrolled, icons have a z-index that is display above the header:
This PR fixes that by setting a higher z-index for the header and close elements.
(In the future I'll refactor the input elements to not use z-index at all, but for now this is a quick fix for the release)
---

[FIX] Fix z-index of folder icons in install dialog

---

public/locales/en/gamepage.json
src/frontend/components/UI/PathSelectionBox/index.tsx
src/frontend/components/UI/TextInputField/index.css
src/frontend/components/UI/TextInputWithIconField/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
src/frontend/screens/Library/components/InstallModal/WineSelector/index.tsx
src/frontend/screens/Library/components/InstallModal/index.scss

It's really common to see support requests of users that clicked the `Use Default Wine Settings` without understanding what it is for.
This PR aims to solve that with 2 things:
- the wine settings are hidden behind a checkbox (most users don't really need to touch those fields ever, the install dialog is simpler)
- then, if they check `Use Default Wine Settings` a warning is displayed to tell them to not use this option if they don't know what they are doing
Also, now when checking the `Use Default Wine Settings` option, the wine and prefix field are not hidden so users can see what that check box is doing (the fields are disabled so they don't change them).
---

[UX] Simplify install dialog hiding wine settings by default. Warn about shared wine directory

---

src/backend/utils.ts

This PR fixes an issue when calculating the install size of GOG games if the game includes symlinks that can't be followed.
This happens with the linux version of FlatOut (the latest giveaway) that includes a wine prefix in the game files and symlinks to drives that are not on all computers.
Without these changes, the game is fully downloaded but it fails to add the game as `installed` to heroic because it fails to calculate the install size:
```
(16:56:58) INFO:    [Gog]:              Got install info from cache for 1207658693 on linux platform
(16:56:59) ERROR:   [DownloadManager]:  Installation of 1207658693 failed with: Error: ENOENT: no such file or directory, stat '/home/ariel/Games/Heroic/FlatOut/prefix/dosdevices/a::'
(16:56:59) WARNING: [DownloadManager]:  Installation of …
```

[Fix] Skip symlinks during size calculation

---

src/backend/storeManagers/gog/setup.ts

I think we should QA things more on Windows. Basically gog setup was trying to get paths from wine.... this PR fixes that

[FIX] don't run getWinePath on windows

---

src/frontend/components/UI/LibraryFilters/index.tsx

Username might be empty for amazon, we handle it everywhere by using user_id but for some reason not here

[FIX] amazon filters not displaying when username is empty

---

package.json
public/locales/en/translation.json
src/backend/updater.ts

Hello, guys! Recently I've made some changes on the update dialog (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3583) and @arielj noticed a problem with the UX and suggested a solution (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3583#issuecomment-1955328702), here it is the pull request with the improvements:
---

[UX] Improve update Dialog

---

src/backend/storeManagers/gog/setup.ts

As we noticed in https://github.com/Heroic-Games-Launcher/known-fixes/pull/7  
the PHYSXLEGACY setup doesn't have a silent switch, or at least it doesn't respect it.
I came up with this simple solution, it should make the experience more hands free.

[WORKAROUND]: run physxlegacy setup without user input

---

e2e/webview_controls.spec.ts
src/frontend/components/UI/WebviewControls/index.tsx

After this https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3426, the back arrow for the webview was actually broken to process the webview's history.
This PR fixes that by adding the `webviewGoBack` dependency to `useCallback` so the function gets updated (honestly I don't see the point of using `useCallback` here, seems like an over-optimization).
Without this fix, the back arrow always takes you to the last heroic screen instead of navigating back inside the webview
---

[FIX] Broken behavior of webview back arrow

---

public/locales/en/translation.json
src/common/types.ts
src/frontend/components/UI/WebviewControls/index.tsx
src/frontend/screens/WebView/index.tsx

When user has blocked the adtraction we should fallback to load gog url directly  
I also changed types to `Electron.WebviewTag` in places where webview was used, to avoid types issues in the future.

[FIX] Adtraction fallback

---

src/backend/launcher.ts
src/backend/storeManagers/storeManagerCommon/games.ts
src/backend/utils.ts

With my changes to callRunner (to use PowerShell on Windows), sideloaded games actually broke on Windows (for two different reasons!)
This fixes both of those problems (details as always in commit messages)
To test:
Well, try to run sideloaded games on Windows. Won't work on 2.13.0, will work with this PR.
---

[Fix] Sideloaded games on Windows

---

src/backend/launcher.ts

Proton 9.0 enables NVAPI by default, so we have to set the variable to 0 to disable it

[FIX] Disabling DXVK-NVAPI on Proton 9.0

---

e2e/webview_controls.spec.ts

The test seems to be flaky (I guess moving between webview pages is not consistent in speed). There are many PRs failing in this test and re-running the e2e tests sometimes solves the problem.
This adds a small timeout before pressing `Go back` that seems to solve the flakyness, I tested locally and it's green consistently with this.
---

[Test] Add a small timeout to fix flaky webview e2e spec

---

src/backend/logger/logger.ts

This PR fixes an issue with sideloaded games printing `Installed in: undefined` instead of the real app folder.
---

[Fix] Print sideload game install dir in logs

---

src/frontend/App.tsx
src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/frontend/screens/Game/GamePage/components/DotsMenu.tsx
src/frontend/screens/Game/index.tsx
src/frontend/screens/Login/index.tsx
src/frontend/screens/Settings/index.tsx
src/frontend/screens/WebView/index.tsx

Our Routes were a bit of an organically grown mess, with different approaches to do the same things, and generally using outdated React Router features. This PR cleans those up, and improves Heroic startup time in the process.
I did remove one route when "converting" from Route elements to objects: `/last-url`, I couldn't find any components navigating to it, so it seems like this was always unreachable?
Other than that, I think we should look into making our WebView component less reliant on specific `location.pathname` values, instead just *telling it* what it's supposed to do (I've opted to choose params over props there, but I don't have any preference really, just seemed more convenient). Didn't want to touch too many things before a release though.
---
Use the following Checklist if …

[Ref/Feat] Clean up our routing and make it faster

---

package.json
src/backend/api/helpers.ts
src/common/typedefs/ipcBridge.d.ts
yarn.lock

[TECH]: update electron

---

public/locales/en/gamepage.json
src/backend/utils.ts
src/frontend/screens/Game/GamePage/components/GameStatus.tsx

Nothing too significant, just 3 quick improvements to the "Move Game" functionality:
- Progress reports are dispatched to the Frontend more frequently
- There were multiple `if (percent)` checks, which erroneously filtered out the case where percent might be 0 (aka we just started copying a new file)
- On Linux, we now tell `rsync` to delete source/old files after they're copied to the new location
- This should help in scenarios with very little disk space being available. Before, we first copy and then delete, now we delete files while copying, and then the entire directory (which should be using virtually no space anymore) at the end
- The types for the `progress` property of the progress update are now correct (`percent` should be a number instead of a string, and `eta` and `bytes` …

[Feat] Improve the "Move Game" experience a bit

---

package.json
src/backend/api/helpers.ts
src/backend/api/library.ts
src/backend/api/misc.ts
src/backend/api/wine.ts
src/backend/backend_events.ts
src/backend/logger/logger.ts
src/backend/main_window.ts
src/backend/progress_bar.ts
src/backend/protocol.ts
src/backend/tools/ipc_handler.ts
src/backend/utils.ts
src/backend/wine/manager/ipc_handler.ts
src/common/types.ts
src/common/types/frontend_messages.ts
src/frontend/components/UI/Sidebar/index.tsx
src/frontend/state/GlobalState.tsx
yarn.lock

This adds typechecking for `backendEvents` and `sendFrontendMessage`. I've already caught a few issues with this (see #3648, some smaller issues are also corrected here)  
Typechecking is done with the usual pattern of an interface holding all possible events/messages, and their corresponding function definitions (similarly to how IPC works, for example)
This is entirely a dev change, no actual code is altered
Requires #3648 
---

[Tech] Type-check Backend & Frontend events

---

src/backend/main.ts
src/backend/utils/filesystem/__tests__/unix.test.ts
src/backend/utils/filesystem/__tests__/windows.test.ts
src/backend/utils/filesystem/index.ts
src/backend/utils/filesystem/unix.ts

In my checkDiskSpace refactor (#3440), I used the `root` property of the object returned by Node's [`path.parse`](https://nodejs.org/api/path.html#pathparsepath), thinking that it'd, logically, give me the root folder (or in other words the mount point) of the disk the path is on. This is not the case on Linux/macOS, it's just simply always `/` there.
This issue would manifest itself in the wrong disk space info being displayed when installing a game onto a drive other than the primary one.
Resolving this was somewhat tricky. Since this function runs on both macOS and Linux, we can't use commandline tools like `findmnt` to help us here, so I went back to what we did before the refactor: Going up the directory tree and using the first path that exists. This works just fine on Unix, since …

[Fix] Make checkDiskSpace look at the correct drive again

---

src/backend/wine/manager/downloader/main.ts
src/backend/wine/manager/utils.ts

Wine-GE-latest or Proton-GE-latest updates do not work because of two problems:
1. When Heroic starts up, new Wine/Proton updates are checked in background but the user is not notified, you have to go to "Wine Manager" screen to see them, unfortunately the update button disappears the next time you restart Heroic or if you reload the versions list and so they go unnoticed.
2. The update fails because the Wine installation folder is renamed with "_backup" suffix (to restore it in case of problems) and the unzip does not find the original folder where to install the new version.
I fixed it by preventing the override of "hasUpdate" field in the wine-downloader-info.json file until Wine is updated and recreating the Wine folder after the backup.
For me I would show somewhere an indicator for …

[FIX] Wine/Proton-GE-latest not updatable after Heroic relaunch or Wine manager refresh

---

public/locales/en/translation.json
src/backend/launcher.ts
src/common/types.ts
src/frontend/screens/Settings/components/Gamescope.tsx

Funny story behind this PR: I was trying to play some random Styx game from GOG that had broken mouse capture on kwin wayland, I opened it through gamescope, it works but on the wrong monitor this time, then I wrote the code for this PR really quickly to change the displays, and guess what ... gamescope doesn't support changing the displays. I will have to make a PR there as well

Support additional gamescope options

---

.github/workflows/build-main.yml

Our Snap credentials need renewing, and I don't know whether we even want to continue publishing Snaps (they never really worked 100%, and no-one in the core team uses them AFAIK)
I've kept most of the infrastructure in-place, in case we do decide on enabling it again in the future
---

Disable Snap for now

---

src/backend/tools/index.ts
src/backend/utils.ts

Multiple little things amounted to Proton no longer being usable while ESYNC/FSYNC were turned on. This resolves those little things by (1) setting the correct env vars when launching Winetricks and (2) no longer launching Winetricks on game launch
---

[Fix] Proton with ESYNC/FSYNC

---

src/backend/launcher.ts

Backslashes are *mostly* fine to just include without escaping, but there are certain cases where they can cause issues. One of those would be when specifying just a drive letter (`X:\`) as one argument (for example as the install path for a game). In that case, when adding the necessary escape characters around the argument, we'd end up with ```"`"X:\`""```. PS would then see that the backtick is escaped by a \\ (even though it's not supposed to be), and the whole thing would fall apart
Resolving this is luckily rather easy, we can simply replace every one \\ with two \\ to end up with one escaped \\, which can then no longer break anything around it
To test:
- Be on Windows
- Try to install a game onto a "bare" drive letter (for example `D:\`)
- Won't work on main, will work here
~~This …

[Fix] Escape backslashes in PowerShell ArgumentList

---

src/frontend/screens/WebView/index.tsx

When opening the Epic Games Store while not being logged in and clicking the "Go to Login" button, the login webview was never displayed. Additionally, doing the same thing with the GOG/Amazon stores would lead to the login warning being displayed twice.
This was, I believe, caused by #3540. When changing locations that point to the same element (in this case from WebView to WebView), instead of throwing away the old element and re-rendering a completely new one, React Router now re-renders the current one (at least it seems like that's how it works)
This exposed a couple issues with the state handling on that component:
- The `useEffect` fetching the Epic Preload path did not rely on `isEpicLogin`, even though `isEpicLogin` being true without a preload path being set results in us …

[Fix] Epic login prompt empty when navigating to it from store

---

public/locales/en/translation.json
src/common/types/electron_store.ts
src/frontend/screens/Accessibility/index.tsx
src/frontend/screens/Library/components/GameCard/index.css
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Library/components/GamesList/index.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

This PR adds a new accessibility toggle to always show the cards' titles without having to hover/focus the card.
This can make finding games easier and it's particularly useful when using a screen with though capabilities where hover doesn't always make sense.
---

[UX] Accessibility option to always show titles in library without having to hover

---

public/locales/en/gamepage.json
public/locales/en/translation.json
src/frontend/components/UI/Anticheat/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx

It's really common for users to install games like Fortnite with broken anticheat and they see the game opens after the installation even with Heroic saying "I understand it will not work". After that they think the game actually works and ask for help getting the game to be playable.
This PR updates the copy of the 2 messages to be more clear that the game will open, but the multiplayer features are what won't work.
This should also help to avoid confusion when a game works for single player and has denied/broken anticheat and only the multiplayer part won't work.
I changed the translation keys to required them to be all updated so we don't have old outdated strings.
---

[UX] Be more explicit about broken anticheat affecting multiplayer in copy

---

README.md

README does not provide clear description of how to install and use wine with Heroic for casual users. 
When I first tried to use HGL, I faced the problem that wine installation is not working to launch games. I tried several time to reinstall HGL and different games. This led me to join the discord channel and ask for support. I found out in the topic of *Frequently Asked Questions* (with the help from channel members) that wine dependencies should be installed.
This simple warning in description should save time for casual users, who don't have deep knowledge of wine. Also they won't bother other people with issues that are obviously easy to fix (like in my case described above).
---

Add important warning about wine dependencies to readme description

---

src/backend/downloadmanager/utils.ts
src/backend/utils.ts

When trying to download the `known-fix` file for a game that has no known fixes file, an error is printed in the logs:
```
(22:28:24) ERROR:   [DownloadManager]:  Downloader: Failed to get headers for https://raw.githubusercontent.com/Heroic-Games-Launcher/known-fixes/main/epic/4656facc740742a39e265b026e13d075-epic.json. 
Error: Error: Request failed with status code 404
(node:184327) UnhandledPromiseRejectionWarning: Error: Failed to get headers
at downloadFile (/home/ariel/dev/oss/HeroicGamesLauncher/build/electron/main.565caa16.js:21710:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `electron --trace-warnings ...` to show where the warning was created)
```
Not finding a fixes file is totally harmless and in the majority of cases it is actually …

[UX] Ignore error message fetching non-existent known-fix json

---

src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/gog/library.ts
src/frontend/screens/Game/GamePage/components/DownloadSizeInfo.tsx
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx

This should resolve number of issues, but also allow players with pre-release access to actually download their games.

[GOG]: don't check for notInstallable during library sync

---

src/frontend/screens/Settings/sections/SyncSaves/gog.tsx
src/frontend/screens/Settings/sections/SyncSaves/legendary.tsx

We have a bug in the logic, we are disabling the input when we are NOT syncing and we are enabling the field while we ARE syncing. This prevents fixing the path if it's wrong.
This PR fixes that by toggling the condition
---

[Fix] Cloud save path input field can't be manually edited

---

src/backend/utils.ts

Trying to launch a game with an invalid Wine version presents the user with an option to choose the default version instead, if that's valid. This is also logged in the game log, but had two issues:
- A missing newline character caused the message to be on the same line as the next log messages (currently a Winetricks package listing)
- We would log that we're changing the version, but wouldn't log the version that we changed to
Both of those issues are now resolved
---

[Fix] "Wine version is not valid" clarifications

---

src/backend/tools/index.ts

Fix support for DXVK installation on 32-bit prefixes.
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3705.
---

[Fix] Support DXVK installation on 32-bit prefixes

---

src/frontend/screens/Library/components/InstallModal/DownloadDialog/BuildSelector.tsx

Fixes #3668
Turns out passing the locale from i18n isn't that good idea, it's just date formatting so now it will be done based on system locale.

[FIX] build selector exception on some locales

---

package.json
pnpm-lock.yaml
src/backend/api/wine.ts
src/backend/utils.ts
src/backend/wine/manager/downloader/__tests__/utilities/unzip.test.ts
src/backend/wine/manager/downloader/main.ts
src/backend/wine/manager/downloader/utilities.ts
src/backend/wine/manager/ipc_handler.ts
src/backend/wine/manager/utils.ts
src/common/typedefs/ipcBridge.d.ts
src/common/types.ts
src/common/types/frontend_messages.ts
src/frontend/screens/WineManager/components/WineItem/index.tsx
src/frontend/screens/WineManager/state.ts

This is a proof-of-concept of using Zustand (https://github.com/pmndrs/zustand) for one of our many states-to-be-managed
I don't know how much I have to explain here, the code looks very straight-forward *to me*, but it's probably confusing in some places if you're not used to the syntax. Please ask questions! With that said, a general explanation:
First off, we've had somewhat of a code split here before (with some state being updated by the Frontend and some by the Backend). This *would* work just fine now as well, but I thought I might as well move everything over to the Backend while I'm at it. Thus, the `installWineVersion` and `removeWineVersion` IPC callbacks no longer return anything, instead settings state directly themselves
On the Frontend side, we first create a store to hold …

[Tech/Demo] Migrate Wine Manager status state to Zustand

---

src/backend/storeManagers/gog/library.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/nile/library.ts
src/common/types.ts
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Game/GamePicture/index.css
src/frontend/screens/Library/components/GameCard/index.tsx

This makes Amazon games look better on new design, since now we are using Amazon's background and horizontal image. Additionally I made it so Heroic will display genres incoming from given provider whenever possible (GOG, Amazon).

Adapt amazon games metadata to new design

---

README.md
index.html
package.json
pnpm-lock.yaml
src/backend/main.ts
vite.config.ts

Adopting #3302
Now that the Zustand PR is merged, this is the only thing missing to truly start battling the re-render issues :^)
---

[Tech] External React Dev Tools application

---

e2e/categories.spec.ts
src/frontend/screens/Library/components/CategoriesManager/index.tsx

Currently we can add empty categories and also rename categories for an empty string.
This is just a small fix to prevent those cases.
I also did another one change to disable the "confirm rename button" when the name was not changed.
Before:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/33737137/9c392ba2-eadd-4231-9dfc-08d9f00b2a7e
After:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/33737137/51b0d6f3-883e-4190-878b-b140fc923e2e
---

[Fix] Prevent empty name category from being added

---

src/backend/launcher.ts

This PR goal is to pass additional game information (title and executable path) to the pre-post launch script using environment variables. This would allow to use the same script with different games, taking actions based on the game title value or executable path.
Tries to fulfill the alternative solution proposed in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3691.
---

[Feat] Pass additional game information to the pre-post launch script using environment variables

---

src/backend/launcher.ts

This is how gamescope docs say to use mangohud with gamescope

[FIX] Use mangoapp when using mangohud with gamescope

---

src/backend/main.ts

See comment message
This resolves a race condition when uninstalling sideloaded games. After clicking the button, if the rendering order of library and game card is just right, the game card for the just-uninstalled game still tries to request & use that game's info, which fails (since the game is uninstalled), but isn't caught (since the returned GameInfo is an empty object, which isn't falsy). The game card then tries to access `gameInfo.install.platform`, which raises an exception and leads to React Router's "Unexpected Application Error" screen.
This issue is very hard to reproduce, as the library rendering before the game card in question avoids it, which seems to be the case most of the time.
---

[Fix] Hand `null` to the Frontend if we can't fetch a game's info

---

src/backend/launcher.ts
src/backend/storeManagers/sideload/games.ts
src/backend/wine/runtimes/ipc_handler.ts
src/backend/wine/runtimes/runtimes.ts
src/common/typedefs/ipcBridge.d.ts

IsInstalled now returns false when the runtime is outdated, which then will cause a redownload the next time a game is launched

Automatically update runtimes

---

src/backend/save_sync.ts
src/backend/utils.ts

The way arguments are passed to PowerShell already handles spaces in the path and the additional quotation marks added by `getShellPath()` causes the path to be truncated at the first space (if present).
For example, 'C:\Users\User\Documents\The Witcher 3\' gets interpreted as 'C:\Users\User\Documents\The'.
Using `.replaceAll()` should be safe since files/folders in Windows can't contain quotes anyway.
(Apologies if there's a better way to do this - Most of my experience is in bash and this is the first I've looked at the heroic codebase)
---

[Fix] Account for spaces in GOG game save paths on Windows

---

src/frontend/screens/WebView/index.tsx

Fixes fallback issues introduced after recent changes in how GOG does redirects

[GOG]: ignore port provided in adtraction url

---

public/locales/en/gamepage.json
src/frontend/components/UI/UninstallModal/index.tsx
src/frontend/screens/Game/GameSubMenu/index.tsx
src/frontend/screens/Library/components/GameCard/index.tsx

This PR disables the "Uninstall" button while a game is running so it cannot be uninstalled by mistake.
Other games can be uninstalled (though we still have the limitation if not uninstalling an Epic game while another Epic game is being installed, but that's unrelated to this fix).
Apart from disabling the buttons, I also made the Uninstall dialog no-op when the game is playing, so if we add an uninstall button and we forget to disable it, it still won't allow the user to uninstall the game while it's running.
---

[Fix] Prevent uninstalling a game while it's running

---

src/frontend/components/UI/LibraryFilters/index.css

This PR fixes this issue reported in Discord https://discord.com/channels/812703221789097985/1253620445224112159/1253620445224112159
when adding categories, a user can add many categories and not fit the screen when opening the dropdown. This adds a scroll and a height limit.
---

Add scroll to categories dropdown when too many categories

---

src/frontend/components/UI/SearchBar/index.scss

While using Heroic, I noticed two small UI bugs (or what I believe to be bugs). 
1. The "x" button to clear the search bar didn't set the cursor to a pointer on hover, so I added that.
2. The autocomplete dropdown underneath the search bar would still be present when there were no results, which looked kind of strange. Here's before and after photos of this:
Let me know if anything needs to be changed, but I thought I'd just do this really quick in case it was something you guys could benefit from. Thanks!
---

Fix UI bugs in search bar

---

src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx

Clicking "Finish" in the "Edit App/Game" dialog made Heroic "forget" the Wine Version associated with that game. That's now fixed.
The problem here is that the configured Wine version is initially undefined, only being updated by the version selector. That's not rendered in editMode, so we're just always saving undefined.
It seems this issue was thought about for the Wine prefix, as *it* is set by an effect above (so the whole spiel ends up doing nothing). This is no longer needed now, so I've removed that part of the effect's functionality.
To test: Edit a sideloaded game (making sure to click "Finish" to save your changes), head to the game settings. Before, notice your Wine Version being reset to the first one in the list. Now, notice your Wine Version is not altered.
Note: The …

[Fix] Sideload: Don't update game settings if we're in editMode

---

src/backend/storeManagers/gog/setup.ts

Tested with `Alone in the Dark 1` (dosbox) and `Beneath the Steel Sky` (scummvm)
gogdl will pick available versions with following conditions
- alternative executable isn't set (Game Settings -> Advanced)
- executable is either dosbox.exe or scummvm.exe
possible executables gogdl will look for
|  | Flatpak | PATH |
|--------|--------|--------|
| DOSBox | `io.github.dosbox-staging` | `dosbox` |
| ScummVM | `org.scummvm.ScummVM` | `scummvm` |
when gogdl is in flatpak container it will attempt to call `flatpak-spawn` available through `org.freedesktop.Flatpak` session bus.
If none of the above are available default wine runner will be called
updated to gogdl 1.1.0 that includes this change

[GOG]: use native builds of ScummVM and DOSBox when available

---

src/backend/config.ts
src/backend/utils.ts
src/backend/utils/compatibility_layers.ts
src/backend/wine/manager/downloader/constants.ts
src/backend/wine/manager/downloader/main.ts
src/backend/wine/manager/downloader/utilities.ts
src/backend/wine/manager/utils.ts
src/common/types.ts
src/frontend/screens/Settings/components/WineVersionSelector.tsx
src/frontend/screens/WineManager/index.tsx

This adds Apple's Gaming porting toolkit download support from the Wine Manager.
The GTPK build is hosted by Gcenx on Github and should contain all the necessary file to be able to run the games.
---

[Feat-macOS] Download GPTK from Wine Manager

---

flatpak/templates/com.heroicgameslauncher.hgl.yml.template

Related to https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3480 and depends on the updated Flatpak support in ULWGL aka umu to be merged/reviewed. After the Flatpak umu is installed in the user's system, the Heroic Games Launcher will need to allow explicit access to umu's `$XDG_DATA_HOME/umu` and the system `/app/share` directory to run games through the launcher. 
The reason is because, without going into the details, umu will currently copy files from `/app/share` to its private Flatpak directory, and Valve's Steam Runtime tools (e.g., Pressure Vessel) are designed to only be executed from the user's home directory. Without explicit visibility to these directories defined in Heroic's manifest, it's likely that umu will fail to launch games successfully due to …

[Flatpak] Update manifest for UMU support

---

src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/storeManagerCommon/games.ts

Fixes issues with hanging rpc client.

[Fix] cleanup discord rpc on launch failures

---

src/frontend/screens/WebView/index.tsx

This bug affected only amazon and gog.
The WebView never triggered auth flow when it was required.  

[FIX]: login flow not working when redirected from store tab

---

src/backend/storeManagers/storeManagerCommon/games.ts

If the additional command line arguments are unset/set to an empty string, the wine command launcher will likewise pass an empty argument to the launched application.
While that is usually harmless, some applications try to parse this argument and (rightfully) complain and usually exit with an error.
Make sure that we only pass additional arguments if they are actually set, fixing that issue.
This has been encountered with Palia's launcher.
---

[Tech] Skip empty arguments in sideload and frontend command launcher

---

src/backend/utils/compatibility_layers.ts
src/frontend/screens/Settings/components/ExperimentalFeatures.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx

as discussed we are going to disable umu out of the box, since before it releases it requires additional steps to get working

[TECH]: disable umu by default

---

src/backend/utils/compatibility_layers.ts

Overview:
- This PR hides the `UMU-Latest` symbolic link from the wine version dropdown menu to prevent users from intentionally selecting it and to avoid unexpectedly upgrading the game's wine prefix. 
Context:
- This file is intended to be used for clients like Lutris, who use umu as a wine manager, so that they can find the wine binaries associated with the current running Proton build and it's only created when either `PROTONPATH=GE-Proton` is set or `PROTONPATH` is unset. It is completely useless for Heroic's use case, as they only use umu for its runtime. At best, it will only cause confusion or mislead users when displayed in the dropdown menu as it gives the impression that an up-to-date Proton build will be used. At worst, when selecting `UMU-Latest`, it may even trigger Proton …

[Fix] Hide UMU-Latest from dropdown menu

---

src/backend/tools/index.ts
src/backend/utils.ts
src/backend/wine/manager/downloader/utilities.ts
src/backend/wine/runtimes/util.ts

This brings back part of the function that was removed before & uses that function everywhere it's applicable
`extractFiles` can now also be easily extended to support more file types (e.g. .zip)
---

Consolidate tar file extraction into one function again

---

src/frontend/screens/Login/components/LoginWarning/index.tsx

Added an onClick handler, called closeOnClick, to close the LoginWarning popup once the login path redirecting button on the popup is clicked so that users don't have to click both the button and the "x" when redirecting to the proper login path.
---

LoginWarning Popup Automatic Close

---

src/backend/api/misc.ts
src/backend/main.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/state/GlobalState.tsx

Title, I think this is reason why the power saver blocker doesn't work

[FIX] Power saver blocker disabling after library updates

---

src/backend/storeManagers/gog/games.ts
src/frontend/screens/Game/GamePage/components/DotsMenu.tsx
src/frontend/screens/Game/GameSubMenu/index.tsx
src/frontend/screens/Game/ModifyInstallModal/GOG/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/GameLanguageSelector.tsx

also automatically run post install script after completed download

[GOG]: add support for linux native dlcs in modify install dialog

---

src/backend/main.ts

`logError` can handle `Error` objects just fine, and will give us more information than just the name & message (which can be crucial to debug exceptions caught by this handler)
No need to review this before the release, mainly just creating this to help users with unexplained uncaught exceptions
---

[Fix] Log the full error in the uncaughtException handler

---

src/backend/tools/index.ts

32 bit dlls can run on mac os thanks to the wow64 implemented in crossover (and upstream wine). 

[FIX] Remove isMac check for 32 bit dxvk

---

appveyor.yml

AppVeyor script was missing this instruction, meaning our release builds lacked helper binaries
---

[Fix] Run `pnpm download-helper-binaries` in the AppVeyor setup

---

src/backend/storeManagers/gog/library.ts
src/common/types/gog.ts

Apparently some games lack this
Closes #3932
---

[Fix] Make `GamesDBDataInner`'s `square_icon` optional

---

electron-builder.yml

[DIST] don't include build-id files in rpm

---

public/locales/en/translation.json
src/backend/api/misc.ts
src/backend/electron_store.ts
src/backend/logger/__tests__/uploader.test.ts
src/backend/logger/ipc_handler.ts
src/backend/logger/logger.ts
src/backend/logger/uploader.ts
src/common/typedefs/ipcBridge.d.ts
src/common/types.ts
src/common/types/electron_store.ts
src/common/types/frontend_messages.ts
src/frontend/App.tsx
src/frontend/components/UI/Dialog/components/DialogHeader.tsx
src/frontend/components/UI/LogFileUploadDialog/index.tsx
src/frontend/screens/Settings/sections/LogSettings/components/UploadedLogFilesList/index.css
src/frontend/screens/Settings/sections/LogSettings/components/UploadedLogFilesList/index.tsx
src/frontend/screens/Settings/sections/LogSettings/index.tsx
src/frontend/state/GlobalStateV2.ts
src/frontend/state/UploadedLogFiles.ts

When displaying a game log, a new button to directly upload the log file to a pastebin service is now presented. This button will upload the log file to `https://0x0.st` and copy the resulting sharable URL into the user's clipboard.
To alleviate privacy concerns, logs are (1) only kept valid for 24 hours and (2) can be deleted from within Heroic:
In the "Settings" -> "Logs" tab specifically, a new button to view uploaded logs was added. It lists all logs which are still valid, the user can then open the sharable URL again or request file deletion
Behind the scenes, two new Zustand states have been added:
- `useGlobalState`, which is my attempt at slowly migrating the current Global State to Zustand. It holds global information (specifically, whether the log file upload dialog or the …

[Feat] Offer option to upload logs to a pastebin

---

public/locales/en/translation.json
src/frontend/screens/Accessibility/index.tsx

Replace string concatenation with i18n interpolation in `actions_font_family_no_default` and `content_font_family_no_default` keys.
This should help eliminate translation errors, as currently many languages have incorrect translation for those keys, even `en` has an incorrectly placed parenthesis there, resulting in this displayed in UI: `Actions Font Family (Default): "Rubik")`.
---

Make actions_font_family_no_default and content_font_family_no_default more translation-friendly

---

src/backend/tools/index.ts

Fix DXVK uninstallation by restoring Wine/Proton DLLs after DXVK DLL overrides are removed. Otherwise `wineboot -u` will have to be executed to achieve the same result.
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3707 .
---

[Fix] Fix DXVK uninstallation from prefix

---

public/locales/en/translation.json
src/backend/launcher.ts
src/common/types.ts
src/frontend/screens/Settings/components/ExperimentalFeatures.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx

We've had the auto installation of known winetricks fixes as an experimental feature enabled by default for a long time and there has not been any big issue reported. I think it's about time for that to be not experimental anymore.
---

[UX] Make auto install of known fixes not experimental anymore

---

src/backend/storeManagers/gog/setup.ts

On Linux we were looking at the windows version of the path which was always false.

[FIX]: gog setup regression for v1 games

---

src/backend/launcher.ts

This caches the used wine version to better detect a wine version change on the prefix. From 9.14 and onward, wineboot does not print the updated message on stdout, which breaks the update detection and eventually causes initial setups to never fire: 
This will result in what what I reported in discord some time ago: [Missing DOSBox config file for GOG games](https://discord.com/channels/812703221789097985/1283469664902578279)

[Fix] Cache installed wine version on prefix

---

src/frontend/screens/Game/GamePage/components/LaunchOptions.tsx

This PR fixes 2 issues with the `Launch Options` selector in the game page:
- it was not possible to unselect options once something was selected (apart from going out and back to the game page)
- the select was not showing up if the installation of a game finished while in the game page screen
---

[Fix] Allow unselecting Launch Options. Show selector after a game finishes installation

---

src/backend/utils/compatibility_layers.ts

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3728#issuecomment-2105946706
Use the same version detection method as [Whisky](https://github.com/Whisky-App/Whisky/blob/57082e3187a4b4481f1c80c85506f939e41bbded/WhiskyKit/Sources/WhiskyKit/WhiskyWine/WhiskyWineInstaller.swift)
Ping @ahmed2m. I do not have Whisky installed. Please download the [CI build](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/9049401139) to see if this works.
---

chore: improve whisky discoverability on mac

---

.github/workflows/build-base.yml

Also updated macOS runner to macos-13 and added error handling and compression options to a lower level than default due to the size of artifacts.
Context:
---

[CI] Upgrade upload-artifact action to v4

---

src/backend/storeManagers/legendary/library.ts

Resolves this issue reported on Discord: https://discord.com/channels/812703221789097985/1308977164619747429
We are already checking for the `namespace` property being `ue`, but it seems this is not actually set for some UE items (specifically assets, plugins, and projects)
---

[Fix] Epic: Hide UE-related items from the user's library

---

e2e/api.spec.ts
e2e/helpers.ts
e2e/settings.spec.ts
src/backend/anticheat/utils.ts
src/backend/main.ts
src/backend/online_monitor.ts
src/backend/storeManagers/gog/e2eMock.ts
src/backend/storeManagers/gog/library.ts
src/backend/storeManagers/legendary/e2eMock.ts
src/backend/storeManagers/legendary/library.ts
src/backend/storeManagers/nile/e2eMock.ts
src/backend/storeManagers/nile/library.ts
src/backend/utils.ts
src/common/typedefs/ipcBridge.d.ts
src/common/types.ts

This PR is an initial implementation to be able to stub binaries during e2e tests.
The current `e2e/api.spec.ts` tests are not really doing an e2e test: those tests are testing that the `window.api` functions return a version for each binary but are not really testing the boundaries of the app from the user point of view. They are more like an API test.
With this PR we can test navigating Heroic as a user would, going to Settings > Advanced where the versions are displayed, and we can now stub the binaries to test different outcomes. The current tests only stub a single stdout value, but the subbing supports setting a response Promise if we want to do something more complex to mimic a download progress for example?
I also added a few `if (process.env.CI === 'e2e')` guards in commands that …

[Test/e2e] Add a mechanism to stub binaries

---

public/locales/en/gamepage.json
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
src/frontend/screens/Library/components/InstallModal/index.scss

This PR adds a small InfoBox at the top of the `Add Game` dialog to tell the users that if they are trying to add an Epic/GOG/Amazon game they own from a store, they should actually use the Import Game feature.
it's small so it's not too invasive for the people that understand the difference, but hopefully it gets the attention of new users and prevents them from using Add Game when they actually want to import.
Closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3902
---

[UX] Show 'import game' hint/instructions in 'add game' dialog

---

src/frontend/screens/Settings/components/EgsSettings.tsx

We have the logic backwards, it should be editable when NOT `isSyncing` (current logic makes it always disabled cause isSyncing starts as false)
---

Fix: egs-sync path field is always disabled

---

public/locales/en/translation.json
src/backend/config.ts
src/backend/launcher.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/tools/index.ts
src/backend/utils.ts
src/backend/utils/compatibility_layers.ts
src/common/types.ts
src/frontend/screens/Settings/components/DisableUMU.tsx
src/frontend/screens/Settings/components/ExperimentalFeatures.tsx
src/frontend/screens/Settings/sections/GamesSettings/index.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx

UMU has been experimental for a while now and it's been working fine for some time already (the issue with the steamdeck in gaming was solved, and the issue with winetricks was solved too).
This PR changes 3 things:
- UMU support not experimental anymore
- UMU always enabled when using Proton by default
- UMU can be disabled as needed on a game-by-game basis for any edge case that doesn't work
Once this is merged we could change the Wine Manager screen to recommend Proton-GE instead of Wine-GE.
---

[UX] UMU used by default if linux and proton, not exprimental anymore, allow disabling as needed

---

src/backend/tray_icon/tray_icon.ts

Implements support for macOS Dock Menus.
Original text:
A terrible two liner that I didn’t put through the linter to show that support for Dock Menu’s would be easy to implement.
I should probably improve it, but I first wanted to know if the devs are open to this at all before I actually spend time on this.
Closes #4156.
---

macOS Dock Menu support

---

src/backend/launcher.ts
src/backend/main.ts

We were checking if the Epic server was offline for some actions when the game was not an Epic game (when importing, updating, and to check if we should add the `--offline` flag). This PR fixes that.
---

Fix: Do not check Epic server status if not an Epic game

---

src/frontend/screens/Settings/components/AfterLaunchScriptPath.tsx
src/frontend/screens/Settings/components/BeforeLaunchScriptPath.tsx
src/frontend/screens/Settings/sections/GamesSettings/index.scss

Adds missing input text fields in advanced game default settings for scripts to run before and after a game is launched feature.
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4044.
---

[Fix] Add missing input text fields in advanced game default settings for scripts

---

src/frontend/screens/Game/GamePage/index.scss

Fixes #4212 
On Game Info SVG tags, we are currently applying a cursor `text` style, which is a bit jarring on SVGs inside button tags.
https://github.com/user-attachments/assets/3b2b4b0e-b839-4646-bdcc-a78907cb4895
https://github.com/user-attachments/assets/4b207baf-a92c-4800-bd54-a4208e336272
---

[Fix] Maintain proper cursor over SVGs on Game page

---

flatpak/com.heroicgameslauncher.hgl.desktop

As [discussed on Discord](https://discord.com/channels/812703221789097985/812703424995000361/1317975825827500093), the WM Class is incorrect in the Desktop Entry.
For whatever reason this has not caused problems in the flatpak itself, likely because flatpak or the DE is able to deduce that there is only one desktop entry and one app in the flatpak?
However for downstream packages that use this file as a base template, this subtle inconsistency can lead to issues.
See https://github.com/NixOS/nixpkgs/pull/365460 for example.
Downstream, the window is _untracked_ due to the wmclass mismatch:
Without that PR:
With that PR:
I've also set `SingleMainWindow=true`. This is a new key added in [Desktop Entry Spec v1.5](https://specifications.freedesktop.org/desktop-entry-spec/1.5/recognized-keys.ht …

[Dist] set the correct WM Class in the flatpak Desktop Entry

---

public/locales/en/translation.json
src/frontend/components/UI/Winetricks/index.tsx

When opening the Winetricks dialog, if a user starts typing too fast in the input field before we get the list of valid components/fonts then it will look like nothing is found. Many users reported that in discord.
This PR changes the dialog to show a message while we are loading the list of things available so users can't type while it's loading, and then we allow searching only once it's ready.
This should make it less confusing for users.
---

[UX] Wait until winetricks lists before allowing the user to search

---

src/frontend/screens/Game/GamePage/components/InstalledInfo.tsx

We have a bug on Mac, when using Crossover, the game details page shows the wineprefix instead of the bottle name in the Installed Info area, when wine prefix makes no sense in that case.
There was code already for that but it was bugged.
---

[Fix] Show Crossover bottle in installed info details

---

src/backend/api/library.ts
src/backend/launcher.ts
src/backend/main.ts
src/backend/protocol.ts
src/frontend/state/GlobalState.tsx

We've always had a weird/complicated flow to start a game when using the `heroic://launch` protocol: main.ts would call the `handleProtocol` function, that would eventually call `sendFrontendMessage`, then the frontend would receive a message to launch the given game and that will trigger another call to the backend to then be handled by `ipcMain.on('launch', ...)`
We can avoid all that extra work by calling the launch code directly from the backend.
I used this opportunity to extract the logic of the `launch` handler and put it into `launcher.ts` where it makes more sense, that helps removing imports and code from `main.ts` that is already too big and complicated.
The `launchEventCallback` function is just the code from `main.ts` as a function, there's nothing to review in there cause …

Launch game from the backend when processing launch protocol without sending a message to the frontend

---

public/locales/en/translation.json
src/backend/utils.ts
src/frontend/screens/WineManager/index.tsx

The other day I made a PR enabling UMU by default.
With that in place we can now make Proton-GE the recommended/preferred compatibility layer to be used.
I updated:
- the default if no wine is present
- updated the wine manager to make it the first tab
- changed the copy at the top of that page to reflect the new recommendation
---

[UX/Tech] Use Proton-GE instead of Wine-GE as default and as recommended

---

src/backend/launcher.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/storeManagerCommon/games.ts
src/common/types.ts

This PR adds support to define env variables in the `known-fixes` repo https://github.com/Heroic-Games-Launcher/known-fixes/issues/6
The env variables are applied to the launch command if present in the fixes file.
I known that in that issue in the known-fixes repo there's a comment by @imLinguin about adding this information to ULWGL/UMU, but we still need to support Mac games or any env variable that could be specific for Heroic and not generic enough to add to UMU's database.
---

Feature: support env variables in known fixes

---

.github/workflows/test.yml

So... e2e tests have been failing consistently for the last week or so in CI but they work just fine locally.
I added some debugging code in this test branch/PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4256 and the output shows this weird sandbox issue:
```
[pid=2422][err] [2422:0110/021426.940726:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/runner/work/HeroicGamesLauncher/HeroicGamesLauncher/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
```
So this PR is changing the ownership and mode of the chrome-sanbox binary so it doesn't exit and now tests are working.
I really don't know what …

Fix chrome-sandbox ownership/mode so e2e tests can run

---

src/backend/launcher.ts
src/backend/storeManagers/gog/setup.ts
src/backend/storeManagers/legendary/setup.ts

fix(gog): make sure game directory is mounted in container

---

src/backend/downloadmanager/utils.ts

This PR prevents an issue that happens when a user tries to install a GOG game but a manifest file already exists in the `manifests` folder. The installation finishes immediately and there's no clear reason for the user.
The solution on discord is always to tell the user to delete this file, we can delete the file automatically before installation just in case.
---

[FIX] Delete GOG manifest if present before install

---

src/backend/config.ts

This has been the default since Proton 9

[FIX] Enable dxvk-nvapi by default

---

src/backend/storeManagers/gog/user.ts

this should prevent false positive emails from GOG that users are on old version of Galaxy

fix: avoid using GOGGalaxyClient user agent

---

src/backend/backend_events.ts
src/backend/main.ts
src/backend/tray_icon/__tests__/tray_icon.test.ts
src/backend/tray_icon/tray_icon.ts

This PR fixes 2 issues:
- The `TrayIcon` was listening to the wrong event to re-render the context menu, it was listening for the event to change the language (before the change) and not an event AFTER the change. Because of that it was always showing the old language when changed. This adds that new event so it's updated at the right time.
- Another problem was that we were NOT storing the language setting in the backend when changed, only in the frontend, so, after a restart, the language in the backend was always `en` while the frontend had the correct value (frontend language is stored in the chrome store). I added that fix so the TrayIcon shows the correct language when started.
One thing I didn't include was updating the backend value with the frontend value cause it's not really …

[Fix] Tray icon language doesn't follow config

---

public/locales/en/translation.json
src/backend/config.ts
src/backend/game_config.ts
src/backend/launcher.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/storeManagerCommon/games.ts
src/backend/utils.ts
src/common/types.ts
src/frontend/screens/Settings/components/VerboseLogs.tsx
src/frontend/screens/Settings/sections/GamesSettings/index.tsx

Currently, we can only enable/disable logs globally to log game output.
This has some issues:
- the setting to disable all logs is not next to the game's settings, so it's not easy to find for users
- logs can impact performance (specially for games with a lot of output) and disk usage, having to enable logs for all games to debug one game means a user can forget to disable it after debugging one game and it will silently apply to all games, logging unnecessary information for games that are already working
- we were enabling all logs by default, which meant users had to know they can disable them
This PR changes that so we can enable `verbose logs` in a game-by-game basis. Some benefits:
- If I forget the logs "on" for a game, it won't affect the other games
- The setting is now in the …

[UX] Enable/disable logs game-by-game instead of globally

---

public/locales/en/gamepage.json
src/backend/api/misc.ts
src/backend/downloadmanager/utils.ts
src/backend/launcher.ts
src/backend/main.ts
src/common/typedefs/ipcBridge.d.ts
src/common/types.ts
src/frontend/hooks/hasKnownFixes.ts
src/frontend/screens/Game/GamePage/index.scss
src/frontend/screens/Game/GamePage/index.tsx

This PR adds support of adding a wiki page link in the known fixes repo so we can display it in the game page of a game to show the user there's known information they should read about that particular game.
This example is for `Heroes of Might and Magic 3 Complete` that (currently) needs a fix that we can't automate for the game to open, so we can point to the detail in our Wiki:
- known fix entry https://github.com/Heroic-Games-Launcher/known-fixes/blob/main/gog/1207658787-gog.json
- our Wiki link: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Game-Workarounds#heroes-of-might-and-magic-3-complete-from-gog
This way users can find out known solutions and workarounds without having to do the research or ask on discord.
Since Wiki pages can also be useful for Windows …

[UX] Add support for wiki links in known fixes to display in game details page

---

src/backend/logger/logger.ts

This PR adds new information in the logs to help both users and support, this is more important now that we are going to default to umu and we already recommend umu to users over discord.
When using umu on the SteamDeck's gaming mode, it looks for the `steam app id` in different environment variables that are only defined when the Steam's `Shader Pre-Cache` is enabled.
When all those conditions are met, the logs will now include a warning message to instruct the users that this is not enabled and the game may not work properly.
More details: https://github.com/Open-Wine-Components/umu-launcher/wiki/Frequently-asked-questions-(FAQ)#why-am-i-not-able-to-see-my-game-when-using-my-launcher-from-steam-mode-gaming-mode
---
Use the following Checklist if you have changed something on the Backend …

[UX] Warn when Shader Pre-Cache is disabled and using umu in SD's gaming mode

---

public/locales/en/gamepage.json
public/locales/en/translation.json
src/frontend/components/UI/DialogHandler/components/MessageBoxModal/index.tsx
src/frontend/screens/Library/components/EmptyLibrary/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
src/frontend/types.ts

This PR improves two messages that were not super clear based on the number of questions in discord.
The message displayed in the library when Heroic is started the first time now explains a bit what the `Log in` and `Add Game` options do, so users can understand what to do to see their games.
The other message I changed is the one that we display when a user tries to install a game with broken/denied anticheat. Currently, the terms used in the copy are based on what AreWeAnticheatYet uses, but it's not clear for new users. Instead, now it explains what that actually means and also tells the user that there's nothing to do about the multiplayer/online features.
---

[UX] Improve empty library instructions and denied anticheat copy

---

public/locales/en/translation.json
src/frontend/screens/Settings/sections/GamesSettings/index.tsx
src/frontend/screens/Settings/sections/SyncSaves/gog.tsx
src/frontend/screens/Settings/sections/SyncSaves/index.tsx
src/frontend/screens/Settings/sections/SyncSaves/legendary.tsx

Currently, we do not display the `Cloud Saves Sync` tab in the game's settings if the game shows that it doesn't support cloud saves in the metadata and if the game is linux native.
It had happened many times in the past that users can't find the `Cloud Saves Sync` tab and they think there's some bug when, in reality, they may be hitting one of those conditions.
So, instead of hiding the tab and letting the user figure out why they can't see it, it's more user-friendly to show the tab and explain why it doesn't work. And in the case of a GOG linux-native game we can also instruct the user to use the Windows version instead so they don't need to figure that out.
I did leave the tab ignored for Amazon games and Sideloaded apps/games because I understand Amazon doesn't cloud saves at all and …

[UX] Show tab and message when Cloud Saves are not supported

---

src/backend/shortcuts/nonesteamgame/steamhelper.ts

Switch Headerart url from "library_hero.jpg" which is used for the backgroundArt and instead use "header.jpg"
Example using ESO Online:
**Before**
**After**
Icons Downloaded:
- https://cdn.cloudflare.steamstatic.com/steam/apps/306130/library_600x900_2x.jpg
- https://cdn.cloudflare.steamstatic.com/steam/apps/306130/logo.png
- https://cdn.cloudflare.steamstatic.com/steam/apps/306130/header.jpg
- https://cdn.cloudflare.steamstatic.com/steam/apps/306130/library_hero.jpg
This fixes #4150 
---

Update SteamApp HeaderArt Url

---

public/locales/en/translation.json
src/backend/launcher.ts
src/common/types.ts
src/frontend/screens/Settings/components/Gamescope.tsx

This PR is to add a QOL toggle that I've been using locally for awhile on multiple devices, it seems to be a common enough issue that a toggle would save people looking up the CLI arg and add it to the additional options.
Appends --force-grab-cursor to gamescope launch command, enabling will force the use of relative mouse mode at all times instead of flipping depending on cursor visibility. In games which flip visibility often can leave the mouse in the wrong mode, which will eventually cause the window to lose focus once the mouse escapes its bounds.
---

Added new Gamescope toggle: Enable Force Grab Cursor

---

src/backend/storeManagers/legendary/library.ts
src/common/types/legendary.ts

With the new Epic mobile app, they are giving away mobile games like the do on PC, but those can't really be handled by legendary yet (fetching game info fails, and it shows no version in the logs).
So we should skip them from now to not show them in the library (it just crashes the install dialog and the details page)
Maybe in some future they can be installed but not yet.
Note that I only own an Android phone, I don't know how things look like for iOS devices so I don't have a fix for that
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4354
---

[UX] Skip games that can only be installed on Android devices

---

src/backend/game_config.ts
src/backend/utils/compatibility_layers.ts
src/common/types.ts

A few days ago I made this PR https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4175 making UMU the default when running games with Proton.
There's a problem with that PR: if a game was running with Proton and UMU disabled, updating heroic will make the game run with UMU incorrectly (affecting its prefix irreversibly, maybe breaking it if the game is incompatible with UMU).
To avoid that, we have to also check if UMU was not used before for games that are already installed.
So: for new games, the `disableUMU` setting will be `false` by default or `true` if changed by the user, so it will ignore the old experimental feature value. For games installed before this change, the `disableUMU` setting will be `undefined` so we check the experimental feature value.
How to test:
- …

[UX/Fix] Respect experimental UMU support disabled

---

src/backend/storeManagers/sideload/games.ts

We have an issue that we can only manually remove elements from the recent list in the tray icon when they are either installed or part of the games in the library, but uninstalled sideloaded games disappear completely.
This PR doesn't fix the full problem but I think it's good enough for most use cases:
- It does remove the item when uninstalled
- It does NOT cleanup the list if it has old items (I don't think it's worth including code to check the list and remove entries, we can handle those cases manually)
To clean the list with already old elements, we can instruct users to edit the file at `~/.config/heroic/store/config.json` and remove elements they don't want from the `"recent"` key.
Fixes #4170 
---
Use the following Checklist if you have changed something on the Backend or …

Fix: Remove sideloaded games from recent list when uninstalled

---

src/backend/config.ts
src/backend/constants.ts
src/backend/utils.ts
src/frontend/screens/WineManager/index.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

Currently, Heroic defaults to using the Game Porting Toolkit for any mac machine, even though it doesn't support Intel mac. Also, because of that default, DXVK is turned off by default.
The default experience for Intel mac users is really poor because Heroic was setting an invalid configuration from the beginning, leading to a lot of support threads.
This PR changes that to default to Wine-Crossover and DXVK turned on when the computer is an Intel mac.
---

[UX] Default to WineCrossover and DXVK on for Intel macs

---

electron-builder.yml
public/locales/en/translation.json
public/webviewPreload.js
src/backend/api/misc.ts
src/backend/main.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/screens/WebView/index.tsx

Instead of routing through legendary.gl/epiclogin we will call different url directly, this should prevent any issues with corrective actions etc..
I have also modified our useragent to contain mention about Heroic

fix: use egs's flow for epic login

---

src/backend/launcher.ts

Back in November, an `installed_games` metadata file was introduced to detect when a new game is installed in an already created prefix. This was not handling Crossover bottles properly, since it was always using the configured winePrefix of the settings that is not used for Crossover.
This PR adds the handling of that, creating the `installed_games` file inside the bottle's folder (essentially a wine prefix) by using some verbose crossover output.
One thing to note is that this will trigger the installation of redistributables once for each game that's already installed since the `installed_games` file is not there yet, but the same is happening now in linux.
This fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4369
---
Use the following Checklist if you have …

[FIX] Handle checking 'installed_games' file for Crossover

---

src/backend/launcher.ts
src/backend/logger/logger.ts

Only tested with UMU enabled so far

Fix logging with proton

---

src/backend/utils.ts

Returning a Promise from `Array.find` causes it to match the first element (as promises are truthy). This caused two issues:
1. Wine was downloaded on Windows
2. The first available Wine version (CrossOver on macOS, Wine-GE on Linux) was always downloaded
---

[Fix] Wine downloading on Windows

---

README.md

Trivial typo fixes in README.md

docs: typo fixes in the .deb installation instructions

---

electron-builder.yml
meta/downloadHelperBinaries.ts

Basically just full arm64 support now :)
Tested on a raspberry pi 4

Add arm64 gogdl, nile, and legendary

---

meta/downloadHelperBinaries.ts
package.json
pnpm-lock.yaml

Not sure how to test this, but this should make the Snap build work
---

[Fix] Respect `HTTPS_PROXY` env var in downloadHelperBinaries script

---

src/frontend/screens/WebView/index.tsx

This should address the login issue. In the meantime simply going through Heroic's Manage Accounts page will let users log in. 
This PR fixes the regression when going to login through Stores tab
Closes #4477 
Closes #4460
Closes #4433 
Closes #4419 
Closes #4289
Closes #4223
Closes #4430

fix: change user-agent at runtime

---

public/locales/en/gamepage.json
public/locales/en/translation.json
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx

Hey, I have added the ability to pick local files with file picker for Game Image (issue #4464)

Pick local files with file picker for Game Image

---

public/locales/en/translation.json
src/backend/main.ts
src/common/types.ts
src/frontend/screens/Accessibility/index.tsx

There's now a new toggle in the "Accessibility" screen to disable smooth scrolling
This was already possible by starting Heroic with `--disable-smooth-scrolling`, but in the long run that's rather clunky
Resolves #4502 
---

[Feat] "Disable smooth scrolling" accessibility option

---

src/backend/protocol.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/common/types.ts
src/frontend/screens/Game/GamePage/components/LaunchOptions.tsx

Closes #4411
A path supplied via the `altExe` parameter will be used just like the "Alternative EXE" option in the game settings
---

[Feat] Make it possible to specify an alternative EXE when launching games from the protocol

---

src/backend/protocol.ts

When creating a shortcut, Windows automatically adds a trailing `/` to the path. This caused Heroic to assume its parsing the old-style protocol URL, while it was actually getting a new-style one. Because of this, shortcuts created on Windows since Heroic 2.16 wouldn't actually work
Note that this is a change on the handling side, meaning previously-non-working shortcuts will now just work again
---

[Fix] Protocol handling on Windows

---

package.json
pnpm-lock.yaml

Direct updates:
- `@vitejs/plugin-react-swc`: `3.6.0` -> `3.9.0`
- `electron-vite`: `2.0.0` -> `3.1.0`
- `vite-plugin-svgr`: `4.2.0` -> `4.3.0`
Important peer dependency updates:
- `vite`: `5.2.8` -> `6.3.5`
- `rollup`: `4.17.2` -> `4.41.0`
Note: I've removed our explicit `vite` dependency, since it's pulled in by `electron-vite` (& we only ever run Vite through electron-vite). This doesn't do *much* (we were already protected from peer dependency version mismatches by pnpm), but it makes the package slightly easier to update
I've tested starting the app normally (`pnpm start`) and AppImage & Windows builds on Linux. I don't think further testing is necessary, since the bundler should behave the same way on all platforms (and `electron-builder` wasn't updated)
---
Use the following …

Update Vite & related packages

---

src/backend/utils/compatibility_layers.ts

It becomes disabled with no indication that it is disabled, so get rid of this check. Proton 10 requires UMU to run as well, causing confusion for users

[FIX] Do not check for UMU experimental feature

---

src/backend/main.ts
src/common/types.ts
src/frontend/App.css
src/frontend/components/UI/ControllerHints/index.tsx
src/frontend/components/UI/Dialog/components/Dialog.tsx
src/frontend/components/UI/Dialog/components/DialogContent.tsx
src/frontend/components/UI/Dialog/components/DialogHeader.tsx
src/frontend/components/UI/LanguageSelector/index.tsx
src/frontend/components/UI/SelectField/index.css
src/frontend/components/UI/SelectField/index.tsx
src/frontend/components/UI/ThemeSelector/index.tsx
src/frontend/helpers/gamepad.ts
src/frontend/screens/Accessibility/index.tsx
src/frontend/screens/Game/GamePage/components/LaunchOptions.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/BranchSelector.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/BuildSelector.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/GameLanguageSelector.tsx
src/frontend/screens/Library/components/InstallModal/WineSelector/index.tsx
src/frontend/screens/Library/components/InstallModal/index.tsx
src/frontend/screens/Settings/components/CustomWineProton.tsx
src/frontend/screens/Settings/components/EnableFSR.tsx
src/frontend/screens/Settings/components/Gamescope.tsx
src/frontend/screens/Settings/components/LibraryTopSection.tsx
src/frontend/screens/Settings/components/MaxRecentGames.tsx
src/frontend/screens/Settings/components/MaxWorkers.tsx
src/frontend/screens/Settings/components/SettingsModal/index.scss
src/frontend/screens/Settings/components/WineVersionSelector.tsx
src/frontend/screens/Settings/sections/SyncSaves/gog.tsx
src/frontend/screens/Settings/sections/SyncSaves/legendary.tsx
src/frontend/state/GlobalState.tsx

This renders most drop-down selection prompts inside Heroic. In turn, these dropdowns now work inside the Gamescope session.
Current issues:
---

Render SelectFields as MUI Selects

---

src/backend/logger/logger.ts
src/common/types.ts

This PR changes the behavior of the Game logger to remove settings from the output when the settings don't make sense for a given game and platform.
For example: it will filter out all the wine-related settings for native games, or hide the gamescope settings when the parent gamescope setting is disabled.
The idea behind this is that these settings that don't make any sense for a given situation are still displayed in the logs, adding noise and confusing the users and during support.
I think this is a good enough first iteration, I think there are probably more settings that can be removed specially on windows, but I don't have a machine with windows to verify (I was looking at the code of the different settings only).
Note: I know the code is kinda verbose, but it was intentional to make …

[UX] Filter settings that don't apply to current platform and game

---

src/backend/tools/index.ts

[FIX] Update DXVK on new releases

---

src/frontend/screens/Library/components/InstallModal/index.tsx

This currently causes the platform selector to be empty on installing a Linux-native GOG game
Before:
After:
Error message:
---

[Fix] Make sure `AvailablePlatforms.value` is an InstallPlatform

---

src/backend/utils/compatibility_layers.ts

Proton is the preferred runner now, so incentivize selecting it by displaying it before Wine
This also moves the "Wine Default" option behind any versions installed by Heroic. The system Wine is usually standard Wine(-Staging at best), which isn't helpful to run games most of the time
---

[Feat] Return Proton first in the Wine version list

---

pnpm-lock.yaml

#4497 seems to have accidentally reverted back to Vite 5
The changes in this PR were made by running `pnpm install vite@latest`, then removing the entry from `package.json` again and running `pnpm install` to remove the explicit dependency from the lock file
---

[Fix] Add Vite 6 to lock file

---

src/backend/storeManagers/legendary/library.ts
src/common/types/legendary.ts
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx

Back then I made a PR [ignoring Android games](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4364) but I had no iOS games to implement the same thing.
This PR finally solves that by also filtering out iOS games
Closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4441
---

[UX] Ignore iOS games in library

---

public/locales/en/translation.json
src/backend/launcher.ts
src/backend/main.ts
src/common/types/ipc.ts
src/frontend/screens/Settings/components/EacRuntime.tsx
src/frontend/screens/Settings/components/GameMode.tsx
src/frontend/screens/Settings/components/Gamescope.tsx
src/frontend/screens/Settings/components/UseFramelessWindow.tsx
src/frontend/types.ts
src/preload/api/wine.ts
src/preload/index.ts

When using Heroic as a Flatpak and mangohud or gamescope are not found, the message only told the user to install them and add them to the PATH, when the solution is to actually install the flatpak packages of those tools (because users might see they actually have the tools installed and in the PATH, but they might not know they need the flatpak version)
Since they also have to install the correct version matching the Flatpak runtime, I included that in the message to make it more obvious.
This should solve many issues of users not knowing how to solve the missing mangohud/gamescope problems.
Also, since `isFlatpak` is a static value that can never change, we don't need an api endpoint, we can just inject the value into the window object at boot using the preload script (we are already …

[UX] Show Flatpak's runtime version when missing mangohud/gamescope

---

src/backend/constants/environment.ts
src/backend/logger/logger.ts
src/frontend/screens/Settings/sections/GamesSettings/index.tsx
src/frontend/types.ts
src/preload/index.ts

The `DXVK-NVAPI` option makes no sense on a SteamDeck since it's always an AMD GPU. We can hide it to remove noise from the settings.
Not sure what's the best way to detect if the devise is a steamdeck (I just checked a few env variables looking at my steamdeck's `printenv` output). We have the `getSteamDeckInfo` function that checks CPU/GPU information against some predefined values but I can't really use it cause it's an async function and I need the code to be sync to use it in the preload/index.ts file.
Closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3861
---

[UX] Hide DXVK-NVAPI option on the SteamDeck

---

public/locales/en/gamepage.json
src/frontend/screens/Game/GamePage/components/LaunchOptions.tsx

The empty prompt select element got lost in the last version. This PR adds that back so users can unselect any `Launch option`.
Some games like Ghostrunner only show the Launch Option to run with DX12 but no option to NOT launch with DX12, so we need a generic/empty option to be able to run the game without an extra game argument
This closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4583 and closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3751
---

[Fix] Add back option to unselect `Launch option`

---

src/backend/storeManagers/legendary/games.ts

The latest release included the automatic fix for Rockstar games using the fake EpicGamesLauncher.exe file but the code has a bug, it tries to use a `wine` path even on windows, causing things to fail with an `TypeError: Cannot read properties of undefined (reading 'type')` trying to fine the `wine type` for when the wine information is undefined in windows.
For users with this issue, as a workaround, deleting the `known fix` file `C:\Users\<your user>\AppData\Roaming\heroic\fixes\8769e24080ea413b8ebca3f1b8c50951.json` should get rid of the error and then the manual steps of the wiki should be usted instead https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Rockstar-Games-from-Epic-Games
I don't have a windows machine to test if just pointing to the fake exe for legendary …

[FIX] Do not use wine path for rockstar fix on windows

---

src/backend/__tests__/protocol.test.ts
src/backend/protocol.ts

This change addresses the bug reported in #4535, namely the issue with the install dialog appearing to just hang because
gui is missing to prompt the user to continue. Instead we exit cleanly if the user doesn't want to install or show them the
gui so that they can proceed with the install otherwise.
---

Ensure install dialog show gui or exits when started with --no-gui

---

src/backend/shortcuts/nonesteamgame/nonesteamgame.ts

Reverts a change from commit 747ff3e59dc0598f333c843c3db842a9982bd4dc which broke exposing the correct path to the running appimage when creating non-steam game shortcuts for export to the Steam library as reported in issue #4597 under v2.17.x.
---

Fix busted appimage path for non-steam shortcuts

---

src/backend/storeManagers/legendary/games.ts
src/frontend/screens/Settings/components/EnvVariablesTable.tsx

I tried this in a VM and it seems to work kind of, the game fails to open but I think it's because I'm inside a VM, but it seems to be doing the correct workflow (not showing the `buy now` screen of the rockstar launcher)
I included a fix for the fake exe integration and also enabled env variables to be configurable and applied in windows.
Please, if anyone has a windows machine not in a VM, can you try this with either GTAV, GTAV enhanced or RDR2?
Steps:
- go to the game's settings > advanced tab
- set the env variable `USE_FAKE_EPIC_EXE = true`
- launch the game
---

[UX] Support Env variables on windows and rockstar tweak

---

src/backend/logger/logger.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/storeManagers/storeManagerCommon/games.ts

This PR fixes some issues with logs for sideloaded games:
- the logs didn't have the warning for verbose logs disabled
- the logs for native games were not always consistent (it was not respecting the verbose logs option and it could end up printing logs at the wrong part of the file)
- the `======= End log ========` line could end up at the end of another line instead of in its own line.
This PR closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4615 (the reported issue was not a bug, but it was missing the disabled verbose logs warning)
---

[UX] Improve log info for sideloaded games

---

src/backend/utils/filesystem/windows.ts

With a single drive connected, the PowerShell command we run will return a single object instead of an array. Account for this by allowing both a single `Win32_LogicalDisk` or an array of them to be the parse result, then handle both cases accordingly
---

[Fix] Fixup getDiskInfo on Windows when only a single drive is connected

---

src/frontend/components/UI/LogFileUploadDialog/index.tsx
src/frontend/screens/Settings/sections/LogSettings/components/UploadedLogFilesList/index.tsx
src/frontend/screens/Settings/sections/LogSettings/index.tsx
src/frontend/state/GlobalStateV2.ts

@arielj recently asked me some questions about `useGlobalState` usage, which revealed some potential DX traps one can fall into when using it
- `useGlobalState` now automatically wraps the provided selector in `useShallow`
- `useShallowGlobalState` was renamed to `useGlobalStateKeys` to clarify what it does
- Documentation for both functions was added
- Export is done as a single default export. This is done (1) to preserve the `setState` function on `useGlobalState` (technically that's possible by just assigning a property, but that seems like a bad idea to me) and (2) since most state consumers need all methods anyways
- `useGlobalStateKeys` is exported as `keys`, to be used as `useGlobalState.keys`
---
Use the following Checklist if you have changed something on the Backend or …

[Tech] DX improvements to `useGlobalState`/`GlobalStateV2`

---

src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
src/frontend/screens/Library/components/InstallModal/index.scss

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4660
Because entire form overlaps with the button we can add right margin just to the InfoBox to prevent overlapping with the dialog's close button.
---

[Fix] Add margin to sideload import Infobox

---

src/backend/main.ts

use `did-finish-load` event in wayland environments for showing main window
---
Currently, when running the launcher with native wayland (`ELECTRON_OZONE_PLATFORM_HINT=auto`), the `ready-to-show` event that we normally wait for to open the window is not fired.
Instead, for environments where the `WAYLAND_DISPLAY` environment variable is set, we can use the `did-finish-load` event instead. https://www.electronjs.org/docs/latest/api/web-contents#event-did-finish-load
It is reached at a similar point as `ready-to-show`.
Other apps also seem to use this similar workaround for Wayland environments, as it seems like a bug in Electron that has existed for a while now. One example is signal messenger, who added this workaround in this commit: …

[TECH] Improve app loading when on Wayland on Linux

---

public/locales/en/translation.json
src/backend/config.ts
src/backend/launcher.ts
src/backend/main.ts
src/backend/tray_icon/__tests__/tray_icon.test.ts
src/backend/tray_icon/tray_icon.ts
src/common/types.ts
src/frontend/screens/Settings/components/MinimizeOnGameLaunch.tsx
src/frontend/screens/Settings/components/TraySettings.tsx

This PR closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2819
A new option to start heroic with no Tray icon (on mac they it can still be accessed from the dock for example)
Toggling the option disables the other tray-related options.
---

[UX] Option to have no tray icon

---

public/locales/en/translation.json
src/frontend/screens/Settings/components/WineVersionSelector.tsx

A few fixes:
- Only show the warning on linux (it was showing on mac)
- Only show the warning if the user actually have Non-GE protons
- Show an InfoBox object that can be clicked for mode details so it doesn't look that off
Before:
After:
---

[UX] Change ignored protons warning

---

public/locales/en/translation.json
src/frontend/screens/WineManager/index.tsx

Re-adds the option since it keeps getting updated and some users said some games works better with it then with wine-crossover.
---

[macOS] Add Wine-Staging-macOS to WineManager

---

src/backend/launcher.ts

Filter out a few more settings per platform to make logs easier to read for support threads
---

[UX] Cleanup logs per platform

---

src/frontend/components/UI/TwoColTableInput/index.tsx

Looks like my changes in [this PR](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3961) produced a [regression in the tables](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4777)
This PR fixes that by splitting the 2 strings we store for name/value as different state variables instead of one.
The issue was that the `onChange` callbacks were not updated after a change of the input, creating issues using always the `{key: '', value: ''}` initial state every time it had to set values.
Splitting this in 2 prevents that and (in my opinion) makes the code a bit easier to read (`newVarName` is closer to what it is than `valueInputs.key` for example)
Closes #4777 
---

[FIX] Env variables and Wrappers tables is broken

---

src/frontend/screens/Game/GamePage/components/CloudSavesSync.tsx
src/frontend/screens/Game/GamePage/components/InstalledInfo.tsx
src/frontend/screens/Game/GamePage/index.css

Noticed there's not a lot of breathing space for the buttons in the game page, which is especially noticeable if you're using a gamepad or keyboard navigation. Details below for comparisons:
<details>
Before:
After:

[UX] Added extra bit of padding for inner buttons in game page

---

src/frontend/components/UI/SelectField/index.tsx

Noticed the SelectField component was getting selected two times when navigating with a gamepad. Details below show before and after change:
<details>
Before:
https://github.com/user-attachments/assets/02fe764a-01e7-4f7c-a648-04e5b8e9fe71
After: 
https://github.com/user-attachments/assets/f6503915-84a1-4dd0-8122-28cf9c9e54d0
</details>

[UX] Improved SelectField navigation with gamepad

---

src/frontend/screens/Library/components/AlphabetFilter/index.css

Dynamic adjust button width and margin Alphabet Filter in Library to get more compact look.\
This feature added in <https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4643>.
Previous:
Now:
On a wide window still like the previous:
This PR equivalent to the following override. You can try it in settings awa:
```css
.alphabet-filter-container {
margin: 8px var(--space-md-fixed);
}
.alphabet-filter-button {
padding: 8px 6px;
margin: 0 min(0.4%, 4px);
min-width: 24px;
width: 2.5%;
max-width: 42px;
vertical-align: middle;
}
```
Only tested on my current install.
---

[UI] Optimize the Alphabet Filter in Library look like on narror window

---

src/frontend/screens/Library/index.tsx

This fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4811
We used to have this, but it broke at some point. We scroll the body element, not the window now.
---

[FIX] Remember scroll position of library when changing screens

---

src/frontend/components/UI/SelectField/index.css

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4776
Make sure text don't wrap to multiple lines in the Categories and Filters buttons.
Before
After
---

[UI] Fix text wrapping for non-alphabetic scripts

---

public/locales/en/translation.json
src/backend/constants/environment.ts
src/backend/main.ts
src/backend/updater.ts

1. We can safely enable the auto-updater for AppImage setups, since those (usually) live in a user-writable location
2. If we don't have the auto-updater, we still want to notify the user about the update being available
Can't really test this
---

[Feat] (Auto-)Updater improvements

---

src/backend/main.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4783
There's an issue on windows (and I think mac too) when opening a second instance of Heroic (from a shortcut for example)
In linux this is not an issue because it uses the `heroic://` protocol, but in window it opens the second instance and detects the previous one running, then it tries to write to the logs which are not initialized yet for that instance.
---

[FIX] Fix logger error opening second instance of Heroic

---

src/backend/storeManagers/legendary/games.ts

Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4794
I understand we were picking either the appName or `legendary` for the pattern as a linux vs windows difference?
on MacOS, the `legendary` process is not there while the game runs so we were just trying to kill a legendary process that either didn't exist OR if any other legendary command was in progress we would kill that instead of the game, and the button didn't really work on MacOS
I checked and the game process on MacOS also has the `appname` command argument just like on linux, so we should use that instead
I only changed this on legendary, I don't have an amazon account to know what the command looks like, but it might need the same change cause it has similar code with the `isLinux` check.
---
Use the …

[FIX] Kill epic game with appName pattern in Mac too

---

src/backend/utils/systeminfo/osInfo/index.ts

Originally I thought "OS:  X.Y.Z (darwin)" would be fine to output temporarily, but since the codename detection FIXME doesn't seem easy to solve, let's at least do "OS: macOS X.Y.Z" for now
To test:
1. Look at any macOS log, note the OS part of the system info message says "OS:  X.Y.Z (darwin)"
2. Run this PR & again check the log, now the message says "OS: macOS X.Y.Z (darwin)"
---

[Fix] Return "macOS" as the OS name on macOS
