Heroic-Games-Launcher/HeroicGamesLauncher

package-lock.json
package.json
public/main.js
src/components/UI/GameConfig.tsx

Added Legendary to the build folder so now Heroic won't need Legendary to be installed to work.
Also added options to build for deb, tar.xz and pacman.

Heroic with legendary

---

PKGBUILD

Correct depends() array for PKGBUILD

---

package.json
public/main.js
public/utils.js
src/components/GamePage/GamePage.tsx
src/helper.ts
src/state/GlobalState.tsx

- Added Notification for when a game finishes downloading.
- Added Tray Icon with a few options for now.

Notification +  Tray Icon

---

README.md

Initial package for [COPR](https://copr.fedorainfracloud.org/coprs/atim/heroic-games-launcher/). To install:
```
sudo dnf copr enable atim/heroic-games-launcher -y
sudo dnf install heroic-games-launcher-bin
```
Would be nice to improve build in future and build whole app from sources.

docs: Add Fedora installation notes

---

electron/main.ts
electron/types.ts
electron/utils.ts
i18next-parser.config.js
public/locales/en/gamepage.json
public/locales/en/login.json
public/locales/en/translation.json
public/locales/pt/gamepage.json
public/locales/pt/login.json
public/locales/pt/translation.json
src/App.css
src/components/GamePage/GamePage.tsx
src/components/Login.tsx
src/components/Settings/GeneralSettings.tsx
src/components/Settings/index.tsx
src/components/UI/GameCard.tsx
src/helper.ts
src/index.tsx
src/state/ContextProvider.tsx
src/state/GlobalState.tsx
src/types.ts

- Added Max Workers Setting to limit download, ram and cpu consumption.
- Finished Translating to Portuguese
- Option to change language on the login screen
- Fixes #137 
- Styling fixes
- Sometimes when cancelling one download, others were cancelled as well
- Several optimizations

New translation + Bug fixes + Max Workers

---

public/locales/en/gamepage.json
public/locales/en/login.json
public/locales/en/translation.json

I fixed some grammar errors and typos in the English translation. Should be fine, tell me if something doesn't fit.

Fix some grammar errors and typos in English translation

---

electron/main.ts
public/locales/de/gamepage.json
public/locales/de/login.json
public/locales/de/translation.json
src/components/Login.tsx
src/components/Settings/GeneralSettings.tsx

I am a native German speaker and I created translations for Heroic.
If you need more strings in the future, you can contact me :smiley: 
You probably have to adjust some CSS there:

Add German translation

---

package.json
public/index.html
src/App.css
yarn.lock

Now uses local font assets. I hope this will not conflict with #180
(pertains #174)

Use local fonts instead of Google fonts

---

src/App.css
src/components/UI/Header.tsx

Fix CSS issues

---

README.md
electron/main.ts
public/locales/tr/gamepage.json
public/locales/tr/login.json
public/locales/tr/translation.json
src/components/Login.tsx
src/components/Settings/GeneralSettings.tsx

Hi! I translated Heroic to Turkish. Some screenshots:

Add Turkish translation

---

README.md
electron/main.ts
public/locales/es/gamepage.json
public/locales/es/login.json
public/locales/es/translation.json
src/components/Login.tsx
src/components/Settings/GeneralSettings.tsx

I have added the support to the Spanish language, here I have some screenshots so that it is appreciated in detail.

Add Spanish translation

---

public/locales/pl/gamepage.json

Saw in PR #218 some Dutch translations appear in the Polish locales.

fix: Dutch in Polish translations

---

electron/main.ts
src/components/GamePage/GamePage.tsx
src/helper.ts

~~Also fixes an issue with a ghost installation process.
`sendKill` was being called after `removeFolder` was invoked.
This caused residual files to remain in some cases.
This made the app think installation was still ongoing when it wasn't.~~
This isn't true, but it still simplifies the code and presents more recent progress than before.

GamePage: Show file size and amount downloaded.

---

electron/main.ts
electron/utils.ts
public/locales/de/gamepage.json
public/locales/de/translation.json
public/locales/en/gamepage.json
public/locales/en/translation.json
public/locales/es/gamepage.json
public/locales/es/translation.json
public/locales/fr/gamepage.json
public/locales/fr/translation.json
public/locales/nl/gamepage.json
public/locales/nl/translation.json
public/locales/pl/gamepage.json
public/locales/pl/translation.json
public/locales/pt/gamepage.json
public/locales/pt/translation.json
public/locales/ru/gamepage.json
public/locales/ru/translation.json
public/locales/tr/gamepage.json
public/locales/tr/translation.json
src/App.css
src/components/GamePage/GamePage.tsx
src/components/Library.tsx
src/components/UI/GameCard.tsx
src/components/UI/UserSelector.tsx
src/helper.ts
src/state/ContextProvider.tsx
src/state/GlobalState.tsx
src/types.ts

- Added Function to get game updates
- Added Update Status Badge on the game card
- Added Update status message on game page
- Added Discord Link
- Adjust some styles

Check game updates

---

CONTRIBUTING.md

Adds a stub CONTRIBUTING file so that the wiki is more discoverable.

Add CONTRIBUTING file.

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/main.yml

Currently runs on PRs and pushes to `main`.
Builds and lints code.

Add GitHub Actions.

---

electron/config.ts

Thanks to Nocccer for reporting this on Discord.

Hotfix for Heroic not launching.

---

electron/legendary_utils/library.ts

Assign a default value to `keyImages`.

---

package.json

I guess we're ready to release v1.5.8 now.

Bump package version to 1.5.8.

---

electron/utils.ts
package.json
src/screens/Settings/components/index.tsx
yarn.lock

This might break stuff. Also I'm currently incapable of regenerating the lockfile due to complications of going from yarn 2 to yarn 1 again (locally).

electron: Replace isOnline with navigator.onLine.

---

electron/constants.ts
electron/games.ts
electron/main.ts
electron/types.ts
i18next-parser.config.js
public/locales/cs/gamepage.json
public/locales/de/gamepage.json
public/locales/en/gamepage.json
public/locales/es/gamepage.json
public/locales/fr/gamepage.json
public/locales/hu/gamepage.json
public/locales/it/gamepage.json
public/locales/ml/gamepage.json
public/locales/nl/gamepage.json
public/locales/nl/translation.json
public/locales/pl/gamepage.json
public/locales/pt/gamepage.json
public/locales/ru/gamepage.json
public/locales/sv/gamepage.json
public/locales/tr/gamepage.json
public/locales/tr/translation.json
src/components/UI/Header/index.tsx
src/components/utils.ts
src/helpers/index.ts
src/screens/Game/GamePage/index.tsx
src/screens/Library/components/GameCard/index.tsx
src/types.ts

Improve the logic for the continuous download and:
Fix #367 
Probably fix #195

UI Improvements + Fixes

---

electron/games.ts

Just a small fix to an issue I noticed after releasing 1.8,0RC1 on Windows.
The EXE there is fixed already.

Fix Update and Repair functions on Windows

---

electron/legendary/games.ts
electron/main.ts

Some small errors slipped through review. Should be fixed now.

backend: Hotfixes.

---

.github/pull_request_template.md

Just added a PR template with some relevant information and checklist

Created a Pull Request Template

---

electron/protocol.ts

Fix launch protocol

---

electron/jest.config.js
jest.config.js
src/jest.config.js
yarn.lock

Added new jest configs

---

electron/legendary/games.ts
public/locales/cs/gamepage.json
public/locales/de/gamepage.json
public/locales/el/gamepage.json
public/locales/en/gamepage.json
public/locales/es/gamepage.json
public/locales/fr/gamepage.json
public/locales/hu/gamepage.json
public/locales/it/gamepage.json
public/locales/ml/gamepage.json
public/locales/nl/gamepage.json
public/locales/pl/gamepage.json
public/locales/tr/gamepage.json
src/components/UI/ToggleSwitch/index.tsx
src/screens/Game/GamePage/index.tsx
src/screens/Settings/components/GeneralSettings/index.test.tsx
src/screens/Settings/components/GeneralSettings/index.tsx
src/screens/Settings/components/OtherSettings/index.tsx
src/screens/Settings/components/WineSettings/index.tsx
src/screens/Settings/index.tsx
src/state/ContextProvider.tsx
src/test_helpers/testTypes.ts
src/types.ts

This hides some settings that are useless to MacOS and also get back some commits that were 'erased'  in some other merge conflicts in the main branch 😫 

Mac settings

---

.github/workflows/test.yml
electron/main.ts
package.json
src/screens/Settings/components/Tools/index.test.tsx
src/screens/Settings/components/Tools/index.tsx
src/test_helpers/mock/electron.ts

Small changes to how the tools works and some fixes.

WineTools improvements

---

electron/constants.ts
electron/legendary/games.ts
electron/main.ts
electron/tsconfig.json
src/screens/Game/GameSubMenu/index.tsx

-------------------------------------

Linux: Improve Desktop/Applications Shortcuts

---

electron/config.ts
electron/legendary/games.ts
electron/main.ts
package.json
public/locales/cs/translation.json
public/locales/de/translation.json
public/locales/el/translation.json
public/locales/en/translation.json
public/locales/es/translation.json
public/locales/fr/translation.json
public/locales/hu/translation.json
public/locales/it/translation.json
public/locales/ml/translation.json
public/locales/nl/translation.json
public/locales/pl/translation.json
public/locales/pt/translation.json
public/locales/ru/translation.json
public/locales/sv/translation.json
public/locales/tr/translation.json
public/locales/zh_Hans/gamepage.json
public/locales/zh_Hans/login.json
public/locales/zh_Hans/translation.json
src/constants.ts
src/screens/Game/GamePage/index.tsx
src/screens/Library/components/GameCard/index.tsx
src/screens/Settings/components/SyncSaves/index.tsx
src/screens/Settings/index.tsx
src/test_helpers/testTypes.ts
src/types.ts

Fixes all issues found on the latest RC Release so far: #502 

1.8.0 rc2 fixes

---

electron/utils.ts

I insert a check to match against same version. This does not work and also was checked in checkCommandVersion before. 
Removed it.

Fix semverGt

---

electron/config.ts
electron/types.ts
electron/utils.ts
package.json
src/screens/Settings/components/GeneralSettings/index.tsx
src/screens/Settings/index.tsx
src/test_helpers/testTypes.ts
src/types.ts

Add Setting to check for Heroic Updates

---

package.json

Changed GitHub URL to the current one
- Created / Updated documentation
Not needed

Changed GitHub URL to the current one

---

electron/legendary/games.ts

Persist Game Extra Info to improve game page loading

---

src/screens/Game/GameSubMenu/index.css
src/screens/Game/GameSubMenu/index.tsx

Added a small text with the wine prefix and version on the game page:

Added Wine/Prefix info on GamePage

---

README.md

Fixed some typos, added Windows and macOS install instructions, and probably some other things

README.md: General improvements.

---

src/index.css
src/screens/Login/index.css
src/screens/Login/index.tsx

Closes #432
Updated primary, secondary, hover colors with new ones from Figma, and of course whole Login Screen.
One thing left is to adjust translations to new elements positioning change for example `input box below` to `box beside` etc.

Login Screen Update with new Design Specs

---

src/screens/Login/index.css

Changed to more descriptive selector, so it doesn't affect buttons on other screens

More descriptive selector on Login Button

---

CHANGELOG.md
electron/main.ts
src/App.css
src/components/Navbar/components/UserSelector/index.css
src/components/Navbar/index.tsx
src/components/UI/Header/index.css
src/components/UI/SearchBar/index.css
src/index.css
src/screens/Game/GamePage/index.css
src/screens/Game/GamePage/index.tsx
src/screens/Library/components/GameCard/index.css
src/screens/Library/components/GameCard/index.tsx
src/screens/Library/index.css
src/screens/Settings/components/GeneralSettings/index.test.tsx
src/screens/Settings/components/GeneralSettings/index.tsx
src/screens/Settings/components/OtherSettings/index.test.tsx
src/screens/Settings/components/OtherSettings/index.tsx
src/screens/Settings/components/WineSettings/index.tsx
src/screens/Settings/index.css
src/screens/Settings/index.tsx
src/state/GlobalState.tsx

New Default Theme

---

electron/legendary/games.ts
electron/types.ts
public/locales/ca/translation.json
public/locales/cs/translation.json
public/locales/de/translation.json
public/locales/el/translation.json
public/locales/en/translation.json
public/locales/es/translation.json
public/locales/fr/translation.json
public/locales/hu/translation.json
public/locales/it/translation.json
public/locales/ml/translation.json
public/locales/nl/translation.json
public/locales/pl/translation.json
public/locales/pt/translation.json
public/locales/ru/translation.json
public/locales/sv/translation.json
public/locales/tr/translation.json
public/locales/zh_Hans/translation.json
src/screens/Settings/components/GeneralSettings/index.test.tsx
src/screens/Settings/components/GeneralSettings/index.tsx
src/screens/Settings/components/OtherSettings/index.test.tsx
src/screens/Settings/components/OtherSettings/index.tsx
src/screens/Settings/components/WineSettings/index.tsx
src/screens/Settings/index.tsx
src/test_helpers/testTypes.ts
src/types.ts

Added Resizable bar and Sharpness Strenght options

More fsr options

---

electron/config.ts
electron/main.ts
electron/protocol.ts
electron/types.ts
electron/updater.ts
package.json
yarn.lock

[Backend] Add updater (2nd attempt)

---

electron/legendary/games.ts
i18next-parser.config.js
public/locales/pt_BR/gamepage.json
public/locales/pt_BR/login.json
public/locales/pt_BR/translation.json
src/screens/Game/TimeContainer/index.tsx
src/screens/Settings/index.tsx

This fixes an error when passing the wrong locale to Intl.DateTimeFormat() was breaking the game page after playing games.

Fix Locale Time Conversion error on PT-BR and Simplified Chineses

---

package.json
src/screens/Library/components/GameCard/index.css
src/screens/Library/components/GameCard/index.tsx
src/state/GlobalState.tsx
yarn.lock

Fix update issues

---

electron/legendary/games.ts

Fix move install function on windows

---

src/App.css
src/App.tsx
src/components/UI/Header/index.css
src/components/UI/InfoBox/index.css
src/components/UI/Sidebar/index.css
src/components/UI/SmallInfo/index.css
src/components/UI/ToggleSwitch/index.css
src/screens/Game/GamePage/index.css
src/screens/Game/GamePage/index.tsx
src/screens/Game/GamePicture/index.css
src/screens/Game/GamePicture/index.tsx
src/screens/Game/GameRequirements/index.css
src/screens/Game/GameRequirements/index.tsx
src/screens/Game/GameSubMenu/index.css
src/screens/Game/GameSubMenu/index.tsx
src/screens/Library/index.css
src/screens/Settings/components/Tools/index.css
src/screens/Settings/index.css

This PR is built on top of the `sidebar` branch adding a new design for the GamePage and refactoring some general layout CSS.
I tried to refactor the GamePage a bit extrating the requirements to another component too.
Any feedback is welcomed.
I'll add some comments in the diff

Implement new gamepage design and refactor general css

---

.eslintrc
.prettierrc.json
electron/legendary/library.ts
package.json
public/locales/en/gamepage.json
src/App.css
src/components/UI/Sidebar/index.css
src/helpers/helpers.test.ts
src/helpers/library.ts
src/index.css
src/screens/Game/GamePage/index.css
src/screens/Game/GamePage/index.tsx
src/screens/Game/GameSubMenu/index.tsx
src/screens/Library/components/GameCard/index.tsx
src/screens/Library/components/InstallModal/index.css
src/screens/Library/components/InstallModal/index.tsx
src/screens/Settings/index.css
src/state/GlobalState.tsx
src/types.ts
yarn.lock

Removes the Install options under GamePage and call the same modal we have on the library:
Also adds the install path selection to the Modal.
Fixes other UI inconsistencies.
Update Legendary and other packages.
Re-introduces Prettier rules.

Modal improvements

---

README.md
package.json
yarn.lock

Downgraded Electron from 16 to 15.3.4 and upgraded electron-builder to latest version.
---

Downgrade Electron to Fix Bug on Debian Systems

---

electron/legendary/user.ts
src/App.css
src/screens/Settings/components/GeneralSettings/index.tsx
src/screens/Settings/components/OtherSettings/index.tsx
src/screens/Settings/components/SyncSaves/index.tsx
src/screens/Settings/components/WineSettings/index.tsx
src/state/ContextProvider.tsx
src/state/GlobalState.tsx
src/types.ts

Fix #834 
Heroic now will change layout of settings to RTL once the Persian Language is selected:
---

[General] Fix RTL Languages

---

electron/legendary/user.ts

Fix a problem that seems to have been caused when merging the lastest changes from different PRs
---

Fix syntax issues with latest main branch

---

electron/legendary/user.ts
electron/main.ts

Implementation for #893.
Just simple store the window bounds on closing and reuse them before the creation of main window.
---

[General] Remember Window Size

---

.gitignore
.prettierignore
electron/utils.ts
package.json
src/screens/WineManager/components/WineItem/index.tsx
yarn.lock

- Fixed the Reset Heroic function making it more specific to delete the settings only.
- Update GOGDL to fix import and install.
- Update Electron to v17 (tested on PopOS and it seems the issue on v16 was fixed)
---

[General] Fix Reset Heroic + Update Electron

---

README.md

Pretty much self explanatory. Update README with information about GOG support.

Update README for release with GOG

---

electron/gog/games.ts
electron/gog/library.ts

Hotfix for #999 and other reports on Discord

[Hotfix] Library not loading, games not installing

---

src/components/UI/Sidebar/index.css
src/index.css
src/screens/Library/components/GameCard/index.css

- Add blur effect on gamecard title.
- Add drop shadow on sidebar.
- Make colors fit together better.
- Disable user select on UI to remove accidental select when navigating.
---
Screenshots:

UI improvements and additions

---

electron/config.ts
electron/constants.ts
electron/launcher.ts
electron/legendary/games.ts
electron/legendary/library.ts
electron/legendary/user.ts
electron/main.ts
electron/utils.ts
flatpak/local.heroic.yml

[General] Add Legendary and GOGDL binaries to env.PATH

---

src/App.css
src/components/UI/FormControl/index.css
src/components/UI/Header/index.css
src/index.css
src/screens/Game/GamePicture/index.css
src/screens/Login/index.css

Recent PR removed some css variables which were used:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1064
I changed code to not to used them in some places and restored variables that were still missing

[Tech] Restore missing css variables

---

electron/gog/games.ts

[Fix] Cancel/pause downloading of GOG games

---

package.json

This adds a German translation to the .desktop file. This has already be done for Flatpak in flathub/com.heroicgameslauncher.hgl#10. This PR adds the translation for the other deployment methods.

Add German translation to .desktop

---

src/screens/Library/components/InstallModal/index.tsx

- Changed the Wine Prefix folder to use the same name as the Install Folder. This seems to fix the issue.
---

[Linux] Fix Special characters on Wine Prefix Folder

---

src/components/UI/FormControl/index.css
src/screens/Library/index.tsx

A few small fixes to the platform filter icons.
---

[UI] Small fixes

---

electron/main.ts
package.json
src/screens/Settings/components/FooterInfo/index.tsx
src/screens/Settings/index.tsx

Small PR to show the heroic version on the settings footer. 
---

[UI] Show heroic version on Settings

---

src/state/GlobalState.tsx

[Fix] Epic library empty after coming from a Linux Native GOG filter

---

electron/main.ts

[Linux/UX]: Make Winetricks Quiet

---

package.json
public/locales/en/translation.json
public/locales/hr/translation.json
src/App.css
src/components/UI/Dialog/components/DialogHeader.tsx
src/components/UI/Dialog/index.css
src/components/UI/Header/index.css
src/components/UI/ThemeSelector/index.tsx
src/components/UI/ToggleSwitch/index.css
src/components/UI/ToggleSwitch/index.tsx
src/index.css
src/index.tsx
src/screens/Accessibility/index.css
src/screens/Game/GamePage/index.css
src/screens/Game/GamePage/index.tsx
src/screens/Library/components/InstallModal/index.css
src/screens/Library/components/InstallModal/index.tsx
src/screens/Settings/components/AdvancedSettings/index.tsx
src/screens/Settings/components/GeneralSettings/index.tsx
src/screens/Settings/components/OtherSettings/index.tsx
src/screens/Settings/components/SyncSaves/index.tsx
src/screens/Settings/components/WineSettings/index.tsx
src/screens/Settings/index.css
src/screens/Settings/index.tsx
src/state/ContextProvider.tsx
src/themes.css
yarn.lock

Fixes some styling, and icons, and improved consistency across the settings.
---

[UI/UX] Settings UI adjustments

---

electron/config.ts
flatpak/local.heroic.yml
package.json
src/screens/Library/components/ContextMenu/index.css
src/screens/Settings/components/SyncSaves/index.tsx
src/screens/WineManager/index.css
yarn.lock

[Fix] UI Fixes 

---

electron/launcher.ts
electron/legendary/games.ts
electron/main.ts
electron/tools.ts
electron/utils.ts
src/screens/Settings/components/Tools/index.tsx
src/screens/Settings/index.tsx

Fixes relating to Proton & the Steam Runtime

---

electron/config.ts
electron/game_config.ts
electron/launcher.ts
electron/legendary/library.ts
electron/logger/logger.ts
electron/main.ts
electron/updater.ts
electron/utils.ts
package.json
src/components/UI/Header/index.tsx
src/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/screens/Library/constants.ts
src/screens/Library/index.tsx
src/screens/WebView/index.tsx
src/state/ContextProvider.tsx
src/state/GlobalState.tsx
src/types.ts

- Disable most verbosity that I added on previous PRs
- Fix wrong runner when refreshing the library that was setting the category wrong.
- Now Category will be same as Runner: `legendary` or `gog`, instead of `epic`
- Disabled auto-update on macOS
---

[Fix] Library not showing and Corrupted config dialog

---

electron/gog/setup.ts
electron/launcher.ts

Added the patch to fix ScummVM windows games on linux and also quote proton/wine binaries on setup if necessary.
---

[Fix] Setup GOG games with Proton + ScummVM patch

---

electron/gog/setup.ts

Backported the fixed that are on the `beta` branch to release a possible new stable.
---

[Fix] Doxbox Setup + ScummVM Windows games

---

electron/legendary/games.ts

[General] Add launcherArgs to native games again

---

src/screens/WineManager/components/WineItem/index.tsx

Fixed digits could not be resolved, because package filesize does not offer such option.
---

[Linux] Wine-Manager format ETA to HH:MM:SS

---

public/locales/en/translation.json
src/screens/Settings/components/OtherSettings/index.tsx

Fix the duplicate description of both help boxes and use the correct description for each help box.
Before-
Now-
---

[UI] Fix Other Help Icon Boxes

---

electron/tools.ts

[Fix] vkd3d and dxvk tar commands

---

electron/gog/library.ts
electron/main.ts
src/components/UI/ActionIcons/index.tsx
src/components/UI/SearchBar/index.tsx
src/components/UI/Sidebar/components/QuitButton/index.tsx
src/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/helpers/library.ts
src/screens/Game/GameSubMenu/index.css
src/screens/Library/components/GameCard/index.tsx
src/screens/Library/components/GamesList/index.tsx
src/screens/Library/components/LibraryHeader/index.tsx
src/screens/Library/index.css
src/screens/Library/index.tsx
src/screens/Settings/components/AdvancedSettings/index.tsx
src/screens/WebView/index.tsx
src/state/ContextProvider.tsx
src/state/GlobalState.tsx
src/types.ts

Fix some issues we found during the first tests for the new beta:
---

[Fix] Beta 2 Fixes

---

electron/constants.ts
electron/main.ts

[Hotfix/Steam Deck] Ignore fullscreen if --no-gui is passed

---

src/helpers/gamepad_layouts/ps.ts

fix the dualsense controller mappings
closes #1584

[Fix] Update dualsense controller mappings

---

src/screens/Settings/index.tsx

[General/Hotfix] Store default steam path on change

---

electron/main.ts
electron/protocol.ts

This fixes starting of gog games via protocol. 
After the beta becomes stable, we will take @CommandMC refactor of protocol (https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1602)
---

[General/Hotfix] Fix gog games not launching via protocol

---

electron/__tests__/utils.test.ts
electron/utils.ts

- `quoteIfNecessary` and `unquoteIfNecessary` didn't catched `undefined`
- `unquoteIfNecessary` didn't catched single `"`
---

[Fix] Quote util functions 

---

src/helpers/gamepad.ts
src/helpers/virtualKeyboard.ts
src/index.css
src/themes.css

The OSK has some minor CSS problems, so this PR fixes them
it also fixes a minor bug from my previous PR regarding the OSK (oops)

[Fix] Fix some bugs with the OSK

---

electron/gog/library.ts
electron/gog/user.ts
electron/main.ts

Added checks for `isOnline` in places where heroic requests gog servers. I think I found all possible cases.

[GOG] Fix errors when offline

---

README.md

Readme file had a weird duplication

[Fix] Fix the readme file

---

flatpak/local.heroic.yml
flatpak/patches/p7zip/gcc10-conversion.patch

Adding dependencies winetrick needs.
Copied over from: https://github.com/flathub/com.valvesoftware.Steam.Utility.protontricks/blob/master/com.valvesoftware.Steam.Utility.protontricks.yml
---

[Fix] Add winetricks dependencies for Flatpak

---

public/locales/ca/translation.json
public/locales/cs/gamepage.json
public/locales/cs/translation.json
public/locales/de/translation.json
public/locales/et/translation.json
public/locales/fa/translation.json
public/locales/fr/gamepage.json
public/locales/fr/translation.json
public/locales/ko/translation.json
public/locales/pt_BR/gamepage.json
public/locales/ru/translation.json
public/locales/zh_Hans/gamepage.json
public/locales/zh_Hans/translation.json

Reverts Heroic-Games-Launcher/HeroicGamesLauncher#1728

Revert "[i18n] Updated Translations"

---

src/helpers/library.ts

[Fix] Empty screen because of recent games undefined

---

src/frontend/components/UI/CachedImage/index.tsx
src/frontend/screens/Game/GamePage/index.tsx

The issue was due to the dependencies inside `useEffect` on the Game Page.
---

[Fix] Game status not updating on uninstall

---

src/backend/legendary/games.ts

This backports #1919 onto the `beta` branch
Resolves #2035 
---

`--offline` flag fix for beta

---

src/frontend/screens/DownloadManager/components/DownloadManagerItem/index.css
src/frontend/screens/DownloadManager/components/ProgressHeader/index.css
src/frontend/screens/DownloadManager/index.css
src/frontend/screens/Library/index.css

There were these white borders around all the items in downloads view, I changed a small thing in the CSS so that now it's not an ugly white :D

[UI] Fix downloads styling

---

src/backend/legendary/games.ts
src/frontend/components/UI/CachedImage/index.tsx
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.scss
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
src/frontend/screens/Library/components/InstallModal/index.css
src/frontend/screens/Settings/components/Tools/index.scss
src/frontend/screens/Settings/index.css
src/frontend/screens/Settings/sections/FooterInfo/index.tsx

A few UI fixes and improvements:
---

[UI] Small Improvements

---

.github/ISSUE_TEMPLATE/bug_report.yaml

This makes logs in bug reports better readable

[Bug template]Put logs in codebox

---

src/backend/legendary/games.ts
src/backend/main.ts

fix: pass skip-version-check only for legendary

---

.github/ISSUE_TEMPLATE/config.yaml

This will disable the ability to create issues without using the template.
As well as add a Discord link for support with launching games.

github: add discord link on new issue page

---

.github/workflows/create-pr-from-stable.yml

Better Description, title and add a label to automated PRs
---

chore: better message, title and label to automated prs

---

src/frontend/App.tsx
src/frontend/components/UI/ExternalLinkDialog/index.tsx
src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

Added dialog with warning, while user click on external link in menu.
---

[UI/UX] Added warning dialog for external links

---

i18next-parser.config.js
src/backend/main.ts
src/frontend/index.tsx

[Tech] Only parse english on `yarn i18n`

---

src/backend/gog/setup.ts

This PR makes all games I tested and had issues with before, **working**. Additional testing of V1 games is welcome of course. 
Some code is duplicated here, but I nevertheless want to change handling of those instructions in the future  
And use cached manifests instead of getting them online
Also fixed issues with some V2 games like `The Witcher`, by looking for executable in support directory, when it doesn't exist in game dir

[GOG] add support for V1 setup instructions

---

CODE_OF_CONDUCT.md

Since d33139a2413787f744a64e3a7201c34c7b084d20 was committed directly to main, no style verification was done.
This PR simply includes the changes made by `prettier --write .`, so all other PRs don't have to do it on their own
---

[Fix] Run `prettier-fix`

---

src/backend/save_sync.ts

Small fix, so I also updated gogdl binaries that should resolve multiple issues, that created unexpected behavior for some V1 games (up to this commit https://github.com/Heroic-Games-Launcher/heroic-gogdl/commit/216bad0f96837bf3b2dfa0e76b68ea850853e07a)

[Tech] Update gogdl, fix appdata typo

---

src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx

[Fix] Should block install on install platform change

---

public/locales/en/translation.json
src/frontend/App.css
src/frontend/App.tsx
src/frontend/components/UI/Sidebar/components/CurrentDownload/index.tsx
src/frontend/components/UI/Sidebar/components/HeroicVersion/index.tsx
src/frontend/components/UI/Sidebar/components/QuitButton/index.tsx
src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
src/frontend/components/UI/Sidebar/index.css
src/frontend/components/UI/Sidebar/index.scss
src/frontend/components/UI/Sidebar/index.tsx
src/frontend/screens/Login/components/SIDLogin/index.css
src/frontend/screens/Settings/index.tsx
src/frontend/screens/Settings/sections/LogSettings/index.css
src/frontend/screens/WebView/index.css

Changed the way we resize the sidebar to use the mouse instead of the collapse button.
https://user-images.githubusercontent.com/26871415/212356230-424d647e-3275-4dff-b7c0-a9129b532970.mov
---

[UI] Resize sidebar on drag event

---

CODE_OF_CONDUCT.md
src/backend/gog/setup.ts

Should fix this problem reported here:
https://discord.com/channels/812703221789097985/1061633792823001098
---

[Bug] Fix TypeError if input for getRegDataType is undefined

---

src/backend/__tests__/legendary/games.ts
src/backend/legendary/__tests__/games.ts
src/backend/legendary/games.ts

[Fix] Don't trim save path & add test for it

---

package.json
yarn.lock

[Tech] update electron to 22.0.2

---

public/locales/en/gamepage.json
public/locales/en/translation.json
src/backend/games.ts
src/backend/gog/games.ts
src/backend/legendary/games.ts
src/backend/legendary/library.ts
src/backend/main.ts
src/backend/utils.ts
src/common/types.ts
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Game/GameSubMenu/index.tsx

- Add moving progress for each file.
- Split moving functions and refactor them so we can use the same for both GOG and Epic.
- Use `robocopy` on windows instead of `mv`
- Use `rsync` on mac and linux when available, if not, use `mv` (without progress)
---

[UI/UX] Improve moving install feedback + Fixes and Refactor

---

src/backend/tools.ts
src/frontend/screens/Game/GamePage/index.tsx

The old upstream repository is abandoned.

Fix the broken VKD3D-Proton Auto update

---

src/frontend/screens/Game/GamePage/index.tsx

Someone was requesting this on the heroic discord, so I decided to implement it

[UI] Installing text links to download manager

---

public/locales/en/translation.json
src/backend/utils.ts
src/common/types/electron_store.ts
src/frontend/screens/Library/components/InstallModal/index.tsx

- Do not show platform selection on Windows
- Show 'Don't ask again' button when checking for Windows VCRuntime
---

[Fix/Windows] Some small Windows fixes

---

src/backend/utils.ts

Implements #1194
Tested it on Manjaro Linux + AppImage

Log Electron, Chrome and NodeJS versions

---

package.json
yarn.lock

Update binaries with the latest commit in main.
---

[Tech] Update GOGDL binaries

---

src/backend/constants.ts
src/backend/main.ts

Small but important fix for clean installs
---

[FIX] Missing GamesConfig Folder

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/workflows/build-prs-mac.yml
.github/workflows/build.yml
appveyor.yml
package.json
public/locales/en/gamepage.json
src/backend/gog/games.ts
src/frontend/App.css
src/frontend/components/UI/LanguageSelector/index.tsx
src/frontend/helpers/index.ts
src/frontend/hooks/constants.ts
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Library/components/GameCard/constants.ts
src/frontend/screens/Library/components/GameCard/index.css
src/frontend/screens/Library/components/GameCard/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
src/frontend/screens/Library/components/InstallModal/WineSelector/index.tsx
src/frontend/screens/Library/components/InstallModal/index.tsx
src/frontend/screens/Settings/components/CustomWineProton.tsx
src/frontend/screens/Settings/index.css
src/frontend/screens/Settings/sections/GamesSettings/index.scss
src/frontend/screens/Settings/sections/GamesSettings/index.tsx
src/frontend/styles/_buttons.scss
src/frontend/styles/_colors.scss
src/frontend/themes.scss

[Fix] Fixes for 2.6 release

---

src/frontend/components/UI/Anticheat/index.scss
src/frontend/screens/Settings/sections/GamesSettings/index.scss

After:
(my mouse was over the play button when I took this screenshot)
Before:

[UI] Fix minor styling bugs

---

src/backend/legendary/games.ts

title, previous code didn't work at all lol (I could have sworn it did)

[Fix] Fix auto enabling of anti cheat runtimes

---

src/frontend/screens/Login/index.css

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1967
The CSS of the login page was leaking to other places.
---

[UI] Fix CSS of language selector in settings

---

src/frontend/components/UI/LanguageSelector/index.tsx

[UI] Make recognition of traditional chinese easier

---

src/backend/utils.ts

Since the icon was updated in a recent release, I have added it as an asset in the Discord developer portal and updated the code in Heroic to reflect this new icon.
---

[Fix] Update Discord rich presence icon

---

.husky/pre-push
package.json

Some small changes to make working with translation files more convenient
- When generating locales with `yarn i18n`, there now is *less* logspam
- The pre-push hook will now fail if i18next had to update translation files, meaning you don't have to do the song-and-dance of "translation files updated while pushing -> add changes -> make new commit -> push again"
---

[Tech] i18next QoL changes

---

src/backend/main.ts

basically what the title says, untested

[FIX] Make sure games are available before auto updating them.

---

src/backend/api/helpers.ts
src/backend/gog/library.ts
src/backend/main.ts
src/common/typedefs/ipcBridge.d.ts
src/common/types.ts
src/common/types/gog.ts
src/common/types/legendary.ts
src/frontend/helpers/index.ts
src/frontend/helpers/library.ts
src/frontend/screens/Game/GamePage/index.tsx

This PR enables launch options for GOG games like in Legendary, except here we are loading the file every time when we open game page

[GOG] Support launch options

---

src/backend/launcher.ts
src/backend/main.ts
src/backend/tools.ts
src/common/types.ts
src/frontend/screens/Settings/components/AutoDXVK.tsx
src/frontend/screens/Settings/components/AutoVKD3D.tsx

this fixes various issues with wine and how esync and fsync are handled, makes winetricks and winecfg open more consistently, enabling and disabling dxvk and vkd3d now always work, no matter if fsync and esync are enabled, it just works significantly better and is less broken

[FIX] Fix various issues with wine management

---

src/backend/main.ts
src/backend/storeManagers/storeManagerCommon/games.ts

The big refactoring PR broke this again :p
and it broke it for all runners, sideloaded or not

FIX: Fix playing status (again)

---

.github/workflows/flatpak-build.yml

Updated flatpak builder to v6 from v4

flatpak-build.yml: bump version

---

src/frontend/themes.scss

This PR fixes 2 issues with the Nord Light theme:
Before
Winetricks dialog logs:
Context menu:
After
Winetricks:
Context menu:
---

[UI] Fixes in Nord Light theme

---

src/frontend/screens/Library/components/GameCard/constants.ts
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx

[Fix] Missing Sideload game cover when no was URL provided

---

public/locales/en/login.json
src/backend/storeManagers/legendary/user.ts
src/frontend/screens/Login/components/SIDLogin/index.css
src/frontend/screens/Login/components/SIDLogin/index.tsx

Show Loading message and spinning arrow like it used to be before.
Also handle errors when the Code is invalid
---

[UI/UX] Show LogIn feedback on alternative Epic login

---

src/backend/config.ts
src/backend/launcher.ts
src/common/types.ts

This lets me use my custom wine builds again! (after symlinking wineserver)

[FIX] don't require wineboot for wine installations.

---

README.md

Update SignPath Links

---

src/backend/storeManagers/gog/library.ts
src/common/types/gog.ts

This PR addresses https://github.com/Heroic-Games-Launcher/heroic-gogdl/issues/34  
Here we are making sure we use builds from main branch only. This is temporal change and branching will be further customizable in slowly progressing gogdl refactor. 

[GOG]: Get game builds only from main branch

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Update heroic version in issue template

---

public/locales/el/translation.json
public/locales/en/translation.json
public/locales/fi/translation.json
public/locales/gl/translation.json
public/locales/hr/translation.json
public/locales/hu/translation.json
public/locales/ko/translation.json
public/locales/ml/translation.json
public/locales/nl/translation.json
public/locales/pt/translation.json
public/locales/sk/translation.json
public/locales/ta/translation.json
src/frontend/screens/Settings/sections/LogSettings/index.tsx

This fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2193
Instructions to report issues were wrong/outdated
---

[UX] Update 'report a problem' message/instructions

---

package.json
yarn.lock

[CI]: change url syntax for electron dependency

---

src/frontend/components/UI/LanguageSelector/index.tsx

'简化字' is not a commonly used term,
'简体中文' is the term accepted by most people.
---

[FIX]: Modify the language label of zh-hans

---

src/backend/tools.ts

Removes a whole lot of unnecessary "garbage" and hacks that didn't need to be there in the first place

[FIX] Speed up the disabling of DXVK and VKD3D.

---

src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts
src/backend/utils/compatibility_layers.ts

[Fix] Specify `--wrapper` only if there are wrappers

---

src/backend/storeManagers/gog/library.ts
src/common/types/gog.ts

[GOG]: fix issues with missing games metadata

---

README.md
package.json

Changed a few lines to add Amazon Games support. A few prob still missing.

Changed a few lines to add Amazon Games support.

---

src/backend/storeManagers/legendary/games.ts

This has already been merged in the past, but got reverted in some refactoring

[FIX] Auto enabling anti cheat runtimes

---

src/backend/utils/os/path/index.ts

The function `searchForExecutableOnPath` had two major bugs:
- It resolve with null on stderr, even `which` reported the correct path. This happens for example inside steam, where calling `which` throws this Error `ERROR: ld.so: object '/home/niklas/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.` before but reports the correct path afterwards.
- It does not hang indefinitely if neither `stdout`, `stderr` or `error` is called
The solution is to wait till spawn calls `close` and resolve with null. If `stdout` is called we resolve earlier with the given path.
---

[FIX]: `searchForExecutableOnPath` hanging or false failing

---

src/backend/storeManagers/nile/library.ts

[FIX] Update nile to not use XDG_CONFIG_HOME

---

src/backend/tools.ts
src/backend/utils/graphics/vulkan/index.ts

[FIX] Use older vkd3d when vulkan 1.1 is detected

---

src/backend/main.ts

[TECH] Add Ozone Flag

---

src/frontend/components/UI/ToggleSwitch/index.css
src/frontend/screens/Library/index.css
src/frontend/screens/Login/components/SIDLogin/index.css
src/frontend/screens/Settings/sections/SystemInfo/index.scss
src/frontend/screens/Settings/sections/SystemInfo/index.tsx
src/frontend/themes.scss

This PR fixes a few issues with some themes:
Most themes currently don't show the anticheat component with color:
Copy to clipboard in the new system info page is also invisible in Dracula and Old School:
Cyberspace has some dark stripes in the library:
Nord-Light has issues showing commands output in dialogs:
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2768
Also fixes:
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2993
Fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2552
---

[Fix] Some themes fixes

---

.github/workflows/build-prs-linux.yml
.github/workflows/build-prs-mac.yml
.github/workflows/build.yml
.github/workflows/codecheck.yml
.github/workflows/lint.yml
.github/workflows/test-e2e-dev.yml
.github/workflows/test-e2e-packaged.yml
.github/workflows/test.yml

I added more verbose logs [here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3098) and I found this:
```
2023-09-30T15:29:45.5106740Z [4/4] Building fresh packages...
2023-09-30T15:29:45.8530223Z verbose 78.974883324 Font Awesome Free 6.3.0 by @fontawesome - https://fontawesome.com
2023-09-30T15:29:45.8558808Z License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
2023-09-30T15:29:45.8559883Z Copyright 2023 Fonticons, Inc.
2023-09-30T15:29:45.8744154Z info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
2023-09-30T15:29:45.9076564Z verbose 79.028974562 TypeError: …
```

[CI] Install node-gyp in CI to fix error related to fontawesome-svg-core

---

src/backend/tools.ts

[FIX] Increase winetricks timeout

---

src/backend/storeManagers/legendary/library.ts

[FIX] Repair in legendary

---

src/frontend/App.css
src/frontend/screens/Game/GamePage/components/HLTB.tsx
src/frontend/screens/Game/GamePage/index.scss

This PR fixes 3 small visual issues in the game page in both designs:
Before: In the old design, the proton db rating had no space
After:
Before: In the new design, the time played popover was behind the next elements
After:
Before: In the new design, the How Long To Beat row didn't match the design of the other rows
After:
---

[UI] Some small game page fixes

---

src/backend/utils.ts

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3231
The `Finished downloading ...` line was duplicated
---

[Fix] Remove duplicated log

---

src/frontend/App.tsx

This PR fixes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3444
Everything is non-draggable now except for the sidebar resizer which still works as expected (I think there's no other element that is draggable.
---

[Fix/UX] Disable dragging elements

---

src/backend/game_config.ts
src/backend/launcher.ts

Title, and code is pretty self explantory. I also removed some duplicate code here as well

[Fix] Some default settings not being applied

---

src/backend/downloadmanager/downloadqueue.ts

Updated gogdl and added a check if gog redist directory exists - in order to make sure ISI is always installed

Tech: gogdl update 

---

src/backend/__tests__/utils.test.ts
src/backend/anticheat/utils.ts
src/backend/storeManagers/gog/library.ts
src/backend/storeManagers/gog/redist.ts
src/backend/storeManagers/legendary/library.ts
src/backend/tools/index.ts
src/backend/utils.ts
src/backend/wiki_game_info/applegamingwiki/__tests__/utils.test.ts
src/backend/wiki_game_info/applegamingwiki/utils.ts
src/backend/wiki_game_info/gamesdb/__tests__/utils.test.ts
src/backend/wiki_game_info/pcgamingwiki/__tests__/utils.test.ts
src/backend/wiki_game_info/pcgamingwiki/utils.ts
src/backend/wiki_game_info/protondb/__tests__/utils.test.ts
src/backend/wiki_game_info/protondb/utils.ts
src/backend/wiki_game_info/steamdeck/__tests__/utils.test.ts
src/backend/wiki_game_info/steamdeck/utils.ts
src/backend/wine/manager/downloader/__tests__/main/getter.test.ts
src/backend/wine/manager/downloader/main.ts
src/backend/wine/manager/downloader/utilities.ts
src/backend/wine/runtimes/__tests__/runtimes/utils.test.ts
src/backend/wine/runtimes/runtimes.ts
src/backend/wine/runtimes/util.ts

[FIX]: reuse axios connections

---

src/backend/storeManagers/storeManagerCommon/games.ts

[FIX] fix logs for sideloaded games

---

flathub/update-flathub.ts
package.json
yarn.lock

Update XML npm package to fast-xml-parser to fix issues with formating of the XML.
---

[CI] Fix Flathub Workflow

---

src/backend/utils/compatibility_layers.ts

[Chore] Use waitforexitandrun instead of run command for Proton

---

.github/actions/install-deps/action.yml
README.md
pnpm-lock.yaml

Arch is now shipping 9.1, so I'm considering that our target now :^)
---

Update to pnpm 9

---

src/backend/launcher.ts
src/backend/storeManagers/gog/library.ts
src/backend/utils.ts
src/common/types.ts

Made a Discord RPC a bit nicer, and added a new field in GameInfo struct for providing best images for icons.
So it turns out we can give the URL instead of the key too...
Closes #3179
Closes #2869

[MISC]: prettify discord rich presence

---

src/frontend/screens/Library/components/InstallModal/WineSelector/index.tsx
src/frontend/screens/Library/components/InstallModal/index.tsx

Closes #3745 
From now on Nile will use game id as a name of directory.  
yes...

[AMAZON]: Fix issues when title is unset

---

src/backend/game_config.ts

[FIX] Include gamescope when applying default settings

---

src/backend/launcher.ts

[FIX] add missing await

---

meta/downloadHelperBinaries.ts

* adds support for working directory, fixing game compatibility

[TECH]: update nile to v1.1.1

---

src/backend/launcher.ts

[FIX] Only use steam runtime with proton

---

electron-builder.yml
meta/downloadHelperBinaries.ts
public/bin/.gitignore
src/backend/launcher.ts
src/backend/wine/runtimes/runtimes.ts
src/common/types.ts

This will give us more control over the service we install in prefix.

[TECH]: ship comet's communication service dummy with Heroic

---

src/backend/storeManagers/gog/library.ts

Instead of spawning so many async functions let's just run a for loop, the wait time may be a little longer, however it's already miles better than the one in 2.14 

[GOG]: simplify library fetching

---

src/backend/launcher.ts

[FIX] Sideloads with proton without umu

---

src/backend/launcher.ts
src/backend/storeManagers/gog/library.ts

[FIX] issues with offline support

---

eslint.config.mjs
src/backend/constants.ts
src/backend/downloadmanager/downloadqueue.ts
src/backend/game_config.ts
src/backend/logger/logger.ts
src/backend/preload.ts
src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/gog/library.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/legendary/library.ts
src/backend/storeManagers/sideload/library.ts
src/backend/utils/compatibility_layers.ts
src/backend/utils/systeminfo/heroicVersion.ts
src/backend/utils/systeminfo/index.ts
src/common/typedefs/ipcBridge.d.ts
src/frontend/components/UI/Dialog/components/Dialog.tsx
src/frontend/components/UI/LibraryFilters/index.tsx
src/frontend/components/UI/Sidebar/index.tsx
src/frontend/screens/Game/GamePage/components/CompatibilityInfo.tsx
src/frontend/screens/Game/GamePage/index.tsx
src/frontend/screens/Game/GameSubMenu/index.tsx
src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
src/frontend/screens/Library/index.tsx
src/frontend/screens/Settings/components/Tools/index.tsx
src/frontend/screens/Settings/sections/AdvancedSettings/index.tsx
src/frontend/screens/Settings/sections/GamesSettings/index.tsx
src/frontend/state/GlobalState.tsx

ESLint auto-fixes some of these problems, so in the interest of not making everyone *not* include these in their PRs (since it's most likely changing something unrelated), I figured I'd make a dedicated PR for them.
---

[Tech] Fix some of the smaller ESLint warnings

---

src/backend/tools/index.ts

[Fix] Use upstream Winetricks on macOS

---

meta/downloadHelperBinaries.ts

[CHORE]: update binaries

---

package.json

[Release]: Heroic 2.15.2

---

src/backend/wine/runtimes/runtimes.ts

[FIX] Runtime isInstalled potential crash

---

src/backend/main.ts

Resubmitted after technical difficulties. Accidentally ruined the branch I'd submitted previously.
On my machine, this resolves the problems described in https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2156
On recent Heroic versions, whether the problem is present at all seems to vary by Linux distro. I had the problem on Ubuntu 24.04 LTS.
On machines that don't have the issue my changes should just add redundancy. I only have my machine to test with but my symptoms were identical to what others were describing, so hopefully this helps everyone affected.
Closes #3418
---

[Fix] Zoom now always retained after minimize, restore, etc.

---

src/backend/utils/helperBinaries/index.ts

[FIX] comet version string has extra newline

---

src/backend/shortcuts/shortcuts/shortcuts.ts
src/backend/wiki_game_info/gamesdb/__tests__/utils.test.ts

Not quite sure how the lint issue wasn't found before (the code has not changed for a year now), but the tests broke in #3917
---

[Fix] Lint & test failures

---

src/backend/main.ts

It's not needed for people purely using proton, so avoid installing it for everyone. 

Stop automatically downloading dxvk

---

src/frontend/screens/Game/GameSubMenu/index.tsx

fixes #3378 partially. Another PR will add a setting for adding shortcuts automatic.

Allow adding steam shortcut for uninstalled games

---

src/backend/tools/index.ts

Otherwise, it doesn't install randomly

[FIX] Await promises for DXVK installation

---

meta/downloadHelperBinaries.ts

tech: update comet to v0.2.0

---

e2e/webview_controls.spec.ts
public/locales/en/translation.json
src/frontend/helpers/gamepad.ts
src/frontend/helpers/shortcuts.ts
src/frontend/screens/Settings/components/ResetHeroic.tsx
src/frontend/state/GlobalState.tsx

I noticed it while translating.
---

Fix capitalisation of Heroic in GlobalState.tsx

---

src/backend/storeManagers/gog/games.ts
src/backend/storeManagers/legendary/games.ts
src/backend/storeManagers/nile/games.ts

Many users are struggling to find this new option, so we can be more explicit in the message.
---

[UX] Improve `disabled verbose logs` message to mention where to enable them

---

src/frontend/state/GlobalState.tsx

Editing the name of a category selects the category bug fix
---

[Fix] Editing the name of a category selects the category

---

meta/downloadHelperBinaries.ts
snap/snapcraft.yaml

[Fix] Try to fix Snap build 

---

src/frontend/screens/Settings/sections/GamesSettings/index.tsx

Remove Other tab for native Mac games.

---

src/backend/main.ts
src/backend/updater.ts

It will fix the issue some people are having with RPM and DEB asking to auto-update and then failing due to permissions or something else.
---

[Fix] Prevent auto-update checks on Linux

---

.github/workflows/flatpak-build.yml
flatpak/templates/com.heroicgameslauncher.hgl.metainfo.xml.template
flatpak/templates/com.heroicgameslauncher.hgl.yml.template

This pull request updates the Flatpak build process and configuration for the Heroic Games Launcher. Key changes include updating dependencies and runtime versions, adding new permissions, and modifying the source of certain modules. These updates aim to enhance compatibility, improve functionality, and ensure the use of the latest tools and libraries.
* Updated the Flatpak runtime and base versions from `23.08` to `24.08` in `flatpak/templates/com.heroicgameslauncher.hgl.yml.template`. This includes changes to `runtime-version`, `base-version`, and various `add-extensions` entries. [[1]](diffhunk://#diff-0740092bbb0bd393a1c8963ca415145f1ceb9fb10b3c547f5e10b602a9ca1e08L4-R6) [[2]](diffhunk://#diff-0740092bbb0bd393a1c8963ca415145f1ceb9fb10b3c547f5e10b602a9ca1e08L92-R128)
* Updated the …

[FIX] Flatpak workflow

---

public/locales/en/translation.json
src/backend/config.ts
src/backend/game_config.ts
src/backend/launcher.ts
src/common/types.ts
src/frontend/screens/Settings/components/AdvertiseAvxForRosetta.tsx
src/frontend/screens/Settings/components/index.ts
src/frontend/screens/Settings/sections/GamesSettings/index.tsx

Implements: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4193
This pull request introduces a new feature to enable AVX instruction set support for Windows games running through Rosetta on Apple Silicon Macs. The changes span backend, frontend, and localization updates to implement and expose this functionality to users.
* Added a new `advertiseAvxForRosetta` property to the `GameSettings` interface in `src/common/types.ts` to store the setting.
* Updated `GameConfigV0` in `src/backend/game_config.ts` to initialize `advertiseAvxForRosetta` based on the platform and wine version.
* Modified the `setupWineEnvVars` function in `src/backend/launcher.ts` to set the `ROSETTA_ADVERTISE_AVX` environment variable when the feature is enabled.
* Created a new …

[FEAT - macOS] Add Rosetta AVX Setting

---

src/frontend/screens/Game/GamePage/index.scss

4K:
Narrow (~1200px):
Masoquist:
---

[FEAT] Enhance responsive design for game page

---

README.md
public/locales/en/translation.json

Also updated a translation that stops the git push verification stuff failing on my machine

Update build instructions in readme

---

public/locales/en/translation.json
src/backend/main.ts
src/backend/storeManagers/legendary/games.ts

It is the fix of #1364 bug.
---

[Fix]: Improve error handling for game import failures

---

CONTRIBUTING.md

TLDR
Corrected CLA url in Contributing.md
Fixes #4713 
---

fix: corrected url to CLA

---

src/frontend/components/Tour/Tour.scss
src/frontend/components/UI/Dialog/components/Dialog.tsx
src/frontend/components/UI/Header/index.css
src/frontend/components/UI/WindowControls/index.scss
src/frontend/screens/Game/GamePage/index.css
src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.scss
src/frontend/screens/Settings/index.css
src/frontend/screens/Settings/sections/LogSettings/index.css
src/frontend/themes.scss

This PR fixes a few style issues, I'll add notes with screenshots in the diff
I can split this in different PRs if needed, but if we merge this without squashing, each commit has one fix
---

[UI/UX] Some themes and style fixes

---

README.md
shell.nix

Well, a project either dies or lives long enough to have Nix nerds start contributing. So here we go!
This PR adds installation instructions, as well as a shell.nix to allow developers on Nix(OS) to get all needed dependencies/set up the correct environment.
---

[Docs] Nix installation & development environment

---

flatpak/templates/com.heroicgameslauncher.hgl.yml.template
public/locales/en/translation.json
src/backend/constants/environment.ts
src/backend/launcher.ts
src/frontend/screens/Settings/components/Gamescope.tsx
src/frontend/types.ts
src/preload/index.ts

Update it to use parameter instead of hardcoded runtime version.
---

Chore: update Gamescope and Mangohud runtime version messages

---

src/frontend/components/UI/TextInputField/index.tsx

In the latest release I introduced a bug, I tried to fix it here https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4787 but it was not the right fix, it was just working around the actual problem.
The issue was also affecting the Gamescope settings for example.
So, this is the correct fix, I forgot to update the event listener when the `onChange` prop changed, this was the actual fix.
---

[FIX] Inputs onChange callback bug

---

public/locales/en/translation.json
src/common/types.ts
src/common/types/electron_store.ts
src/frontend/App.css
src/frontend/App.tsx
src/frontend/screens/Accessibility/index.tsx
src/frontend/state/ContextProvider.tsx
src/frontend/state/GlobalState.tsx
src/frontend/types.ts

Allow disabling all transitions and animations in the Accessibility settings.
Closes https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4052
---

[UX/A11y] Disable animations
